function outputPath = generate_function_inventory()
%GENERATE_FUNCTION_INVENTORY Generate a read-only Markdown MATLAB function list.
%   OUTPUTPATH = GENERATE_FUNCTION_INVENTORY() scans core/, app/plotting/,
%   and tools/ for MATLAB source files. It extracts each first function
%   declaration and writes docs/generated/FUNCTION_INVENTORY.md. Source files
%   are read only; data, results, and ignored local directories are not scanned.

projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
scanRoots = {fullfile(projectRoot, 'core'), ...
    fullfile(projectRoot, 'app', 'plotting'), ...
    fullfile(projectRoot, 'tools')};
entries = strings(0, 2);

for rootIndex = 1:numel(scanRoots)
    root = scanRoots{rootIndex};
    files = dir(fullfile(root, '**', '*.m'));
    for fileIndex = 1:numel(files)
        fullPath = fullfile(files(fileIndex).folder, files(fileIndex).name);
        relativePath = erase(fullPath, [projectRoot filesep]);
        firstLine = firstFunctionLine(fullPath);
        if strlength(firstLine) > 0
            entries(end + 1, :) = [string(relativePath), firstLine]; %#ok<AGROW>
        end
    end
end

entries = sortrows(entries, 1);
outputDir = fullfile(projectRoot, 'docs', 'generated');
if ~isfolder(outputDir)
    mkdir(outputDir);
end
outputPath = fullfile(outputDir, 'FUNCTION_INVENTORY.md');

fid = fopen(outputPath, 'w', 'n', 'UTF-8');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '# Function Inventory\n\n');
fprintf(fid, '> This file is generated. Do not edit manually.\n\n');
fprintf(fid, 'Generated by `tools/docs/generate_function_inventory.m`. ');
fprintf(fid, 'It scans MATLAB source under `core/`, `app/plotting/`, and `tools/`; it does not inspect data or result directories.\n\n');
fprintf(fid, '| File | First function declaration |\n| --- | --- |\n');
for index = 1:size(entries, 1)
    signature = replace(entries(index, 2), '|', '\\|');
    fprintf(fid, '| `%s` | `%s` |\n', entries(index, 1), signature);
end
end

function declaration = firstFunctionLine(filePath)
declaration = "";
lines = splitlines(string(fileread(filePath)));
for index = 1:numel(lines)
    candidate = strtrim(lines(index));
    if startsWith(candidate, "function ")
        declaration = candidate;
        return;
    end
end
end
