function scenario = quadriga_scenarios(scenario_name)
%QUADRIGA_SCENARIOS Return 3GPP scenario physical parameter defaults.
%   scenario = quadriga_scenarios("3GPP_38.901_UMi") returns the default
%   physical parameters for the Urban Micro NLOS scenario.

arguments
    scenario_name {mustBeTextScalar}
end

scenario_name = upper(string(scenario_name));

switch scenario_name
    case "3GPP_38.901_UMI"
        scenario = struct( ...
            'name', "3GPP_38.901_UMi", ...
            'description', "Urban Micro NLOS", ...
            'bs_height_m', 10, ...
            'ue_height_m', 1.5, ...
            'ue_speed_mps', 0.833, ...
            'num_clusters', 12, ...
            'num_rays_per_cluster', 20, ...
            'ds_mean_ns', -7.19, ...
            'ds_std_db', 2.88, ...
            'as_mean_deg', 17.0, ...
            'as_std_db', 6.0, ...
            'sf_std_db', 4.0, ...
            'kf_mean_db', 9.0, ...
            'kf_std_db', 5.0, ...
            'delay_spread_range_ns', [10, 500], ...
            'scenario_type', "NLOS", ...
            'environment', "urban");

    case "3GPP_38.901_UMI-LOS"
        scenario = struct( ...
            'name', "3GPP_38.901_UMi-LOS", ...
            'description', "Urban Micro LOS", ...
            'bs_height_m', 10, ...
            'ue_height_m', 1.5, ...
            'ue_speed_mps', 0.833, ...
            'num_clusters', 12, ...
            'num_rays_per_cluster', 20, ...
            'ds_mean_ns', -7.49, ...
            'ds_std_db', 2.88, ...
            'as_mean_deg', 17.0, ...
            'as_std_db', 6.0, ...
            'sf_std_db', 3.0, ...
            'kf_mean_db', 15.0, ...
            'kf_std_db', 5.0, ...
            'delay_spread_range_ns', [5, 300], ...
            'scenario_type', "LOS", ...
            'environment', "urban");

    case "3GPP_38.901_UMA"
        scenario = struct( ...
            'name', "3GPP_38.901_UMa", ...
            'description', "Urban Macro NLOS", ...
            'bs_height_m', 25, ...
            'ue_height_m', 1.5, ...
            'ue_speed_mps', 0.833, ...
            'num_clusters', 12, ...
            'num_rays_per_cluster', 20, ...
            'ds_mean_ns', -6.62, ...
            'ds_std_db', 3.0, ...
            'as_mean_deg', 19.0, ...
            'as_std_db', 6.0, ...
            'sf_std_db', 4.0, ...
            'kf_mean_db', 7.0, ...
            'kf_std_db', 5.0, ...
            'delay_spread_range_ns', [10, 800], ...
            'scenario_type', "NLOS", ...
            'environment', "urban");

    case "3GPP_38.901_UMA-LOS"
        scenario = struct( ...
            'name', "3GPP_38.901_UMa-LOS", ...
            'description', "Urban Macro LOS", ...
            'bs_height_m', 25, ...
            'ue_height_m', 1.5, ...
            'ue_speed_mps', 0.833, ...
            'num_clusters', 12, ...
            'num_rays_per_cluster', 20, ...
            'ds_mean_ns', -6.72, ...
            'ds_std_db', 3.0, ...
            'as_mean_deg', 19.0, ...
            'as_std_db', 6.0, ...
            'sf_std_db', 3.0, ...
            'kf_mean_db', 13.0, ...
            'kf_std_db', 5.0, ...
            'delay_spread_range_ns', [5, 500], ...
            'scenario_type', "LOS", ...
            'environment', "urban");

    case "3GPP_38.901_RMA"
        scenario = struct( ...
            'name', "3GPP_38.901_RMa", ...
            'description', "Rural Macro", ...
            'bs_height_m', 35, ...
            'ue_height_m', 1.5, ...
            'ue_speed_mps', 8.333, ...
            'num_clusters', 10, ...
            'num_rays_per_cluster', 20, ...
            'ds_mean_ns', -7.19, ...
            'ds_std_db', 2.88, ...
            'as_mean_deg', 10.0, ...
            'as_std_db', 4.0, ...
            'sf_std_db', 4.0, ...
            'kf_mean_db', 7.0, ...
            'kf_std_db', 5.0, ...
            'delay_spread_range_ns', [10, 1000], ...
            'scenario_type', "NLOS", ...
            'environment', "rural");

    case "3GPP_38.901_INH"
        scenario = struct( ...
            'name', "3GPP_38.901_INH", ...
            'description', "Indoor Hotspot", ...
            'bs_height_m', 3, ...
            'ue_height_m', 1.5, ...
            'ue_speed_mps', 0.833, ...
            'num_clusters', 12, ...
            'num_rays_per_cluster', 20, ...
            'ds_mean_ns', -7.68, ...
            'ds_std_db', 2.0, ...
            'as_mean_deg', 25.0, ...
            'as_std_db', 6.0, ...
            'sf_std_db', 3.0, ...
            'kf_mean_db', 10.0, ...
            'kf_std_db', 5.0, ...
            'delay_spread_range_ns', [5, 200], ...
            'scenario_type', "LOS/NLOS", ...
            'environment', "indoor");

    otherwise
        error("quadriga_scenarios:UnknownScenario", ...
            "Unknown scenario: %s. Valid: 3GPP_38.901_UMi, UMi-LOS, UMa, UMa-LOS, RMa, INH", ...
            scenario_name);
end
end
