function result = create_frequency_axis_calibration()
%CREATE_FREQUENCY_AXIS_CALIBRATION Placeholder calibration for Frequency tasks.
%   The Frequency-axis prediction is a deterministic in-band recovery
%   (linear interpolation of known subcarriers) and never consumes
%   generator-parameter calibration. Running the Step-8 optimizer on a
%   Frequency task is both useless and impossible: the known region is a
%   hole-y (non-uniform) subcarrier grid, so no reliable wideband PDP fit
%   target can be built (CTF->CIR needs a uniform grid).
%
%   This placeholder satisfies the platform's "calibrate before generate"
%   flow gate while recording the honest reason. It never reads
%   target-region samples and never runs the optimizer.

frozen = struct( ...
    "DS_sigma", 0.35, "KF_sigma", 2.0, "r_DS", 2.66, ...
    "LNS_ksi", 3.33, "num_clusters", 12, "num_rays", 20);
result = struct( ...
    "schema_version", "v3.2-4a-frequency-axis-calibration.1", ...
    "success", true, ...
    "status", "PASS", ...
    "complete", true, ...
    "cancelled", false, ...
    "formal_eligible", true, ...
    "requested_strategy", "none", ...
    "selected_strategy", "frequency_deterministic_recovery", ...
    "selection_source", "v32_4a_frequency_axis_policy", ...
    "selection_reason", ...
        "频率轴预测为确定性带内恢复（线性插值），不依赖生成器参数标定；" + ...
        "已知区为洞状非均匀子载波网格，无法构建宽带 PDP 拟合目标，故跳过参数优化。", ...
    "best", struct("parameters", frozen, "score", NaN), ...
    "manifest", struct( ...
        "schema_version", "v3.2-4a-frequency-calibration-manifest.1", ...
        "best_score", NaN, ...
        "config", struct()), ...
    "config", struct("generator_config", struct("backend", "full_6gpcm")), ...
    "errors", strings(0, 1), ...
    "warnings", strings(0, 1));
end
