function probe_v32_1_all_axes(engineRoot)
%PROBE_V32_1_ALL_AXES Unified three-axis v3.2-1 synthesis validation.
%   Time/Space: generate route -> per-snapshot DS_mu/KF_mu -> 16->4 windows.
%   Frequency: generate static CIR -> CTF -> 3 missing patterns.
%   Also verifies Full 6GPCM core hash is unchanged before/after.

arguments
    engineRoot (1, 1) string = ""
end

if engineRoot == ""
    engineRoot = resolve_full_6gpcm_root().root;
end

hashBefore = hash_full_6gpcm_tree(engineRoot).aggregate_sha256;
names2 = ["DS_mu", "KF_mu"];
bounds2 = [-9.0, -5.0; -20, 30];
dataConfig = default_predictor_data_config();

%% Time axis
timeRoute = generate_v32_1_time_route(engineRoot, ...
    ScenarioName="sub-6 GHz_UMa_LoS", SpeedMps=8.0, ...
    SnapshotIntervalS=0.100, TxCount=2, RxCount=4, Nt=96, Seed=7100);
timeSeq = estimate_v32_1_time_p8_sequence(timeRoute.dataset);
timePS = create_parameter_sequence(timeSeq.values, names2, struct( ...
    "group_id", repmat("time-01", 96, 1), ...
    "parameter_sample_index", (1:96).', "bounds", bounds2, ...
    "label_source", "direct_channel_observed", ...
    "quality_status", repmat("PASS", 96, 1), ...
    "provenance", timeSeq.provenance));
timeDS = build_predictor_dataset(timePS, "extrapolation", dataConfig);
assert(timeDS.summary.N_example == 77, "Time must yield 77 windows");
assert(size(timeDS.inputs, 3) == 2 && size(timeDS.targets, 3) == 2, ...
    "Time tensors must have P=2");
assert(all(max(timeDS.input_parameter_sample_index, [], 2) < ...
    min(timeDS.target_parameter_sample_index, [], 2)), "Time must be causal");
assert(std(timeSeq.values(:, 1), "omitnan") > 0 || ...
    std(timeSeq.values(:, 2), "omitnan") > 0, "Time DS/KF must vary");
fprintf("Time   : 77 windows, P=2, causal, slow-varying  OK\n");

%% Space axis
spaceRoute = generate_v32_1_space_route(engineRoot, ...
    ScenarioName="sub-6 GHz_UMa_LoS", SpeedMps=8.0, ...
    SnapshotIntervalS=0.100, TxCount=2, RxCount=4, NSample=96, Seed=7101);
spaceSeq = estimate_v32_1_space_p8_sequence(spaceRoute.dataset);
spacePS = create_parameter_sequence(spaceSeq.values, names2, struct( ...
    "group_id", repmat("space-01", 96, 1), ...
    "parameter_sample_index", (1:96).', "bounds", bounds2, ...
    "label_source", "direct_channel_observed", ...
    "quality_status", repmat("PASS", 96, 1), ...
    "provenance", spaceSeq.provenance));
spaceDS = build_predictor_dataset(spacePS, "extrapolation", dataConfig);
assert(spaceDS.summary.N_example == 77, "Space must yield 77 windows");
assert(size(spaceDS.inputs, 3) == 2 && size(spaceDS.targets, 3) == 2, ...
    "Space tensors must have P=2");
assert(std(spaceSeq.values(:, 1), "omitnan") > 0 || ...
    std(spaceSeq.values(:, 2), "omitnan") > 0, "Space DS/KF must vary");
assert(isfield(spaceRoute.dataset.axes, "sample_position_m"), ...
    "Space must have sample_position_m");
fprintf("Space  : 77 windows, P=2, position coords, slow-varying  OK\n");

%% Frequency axis
for pattern = ["uniform_half", "random_half", "block_8"]
    spectrum = generate_v32_1_frequency_spectrum(engineRoot, ...
        ScenarioName="sub-6 GHz_UMa_LoS", Nf=64, ...
        MissingPattern=pattern, Seed=7102);
    assert(spectrum.ctf_dataset.dimensions.Nf == 64, "Frequency Nf must be 64");
    assert(isempty(intersect(spectrum.known_subcarrier_index, ...
        spectrum.target_subcarrier_index)), "Frequency known/target overlap");
    assert(numel(spectrum.known_subcarrier_index) + ...
        numel(spectrum.target_subcarrier_index) == 64, ...
        "Frequency known+target must cover all subcarriers");
    assert(all(isfinite(real(spectrum.ctf_dataset.ctf.H(:)))), ...
        "Frequency CTF must be finite");
end
fprintf("Frequency: 3 missing patterns, Nf=64, no overlap  OK\n");

%% Core unchanged
hashAfter = hash_full_6gpcm_tree(engineRoot).aggregate_sha256;
assert(hashBefore == hashAfter, "Full 6GPCM core changed during synthesis");
fprintf("Core    : Full 6GPCM tree hash unchanged  OK\n");

fprintf("PASS: unified three-axis v3.2-1 synthesis validation.\n");
end
