function result = run_v32_frequency_generation(channelDataset, prediction, options)
%RUN_V32_FREQUENCY_GENERATION v3.2-4a Frequency-axis product generation.
%   Deterministic in-band recovery of the missing subcarriers of the
%   imported CTF (linear interpolation of known subcarriers, the v3.2-2b
%   recommended Frequency method), then IFFT to CIR, the shared
%   characteristic engine, and a canonical prediction result. Full 6GPCM is
%   NOT involved.
%
%   Mirrors run_prediction_generation's result contract so the App
%   module-three flow is unchanged (success / status / outcome /
%   formal_eligible / prediction_result / errors / warnings / events /
%   runtime). The prediction must come from run_v32_axis_prediction's
%   frequency branch, which already verifies that target subcarriers are
%   masked (NaN) in the imported dataset.

arguments
    channelDataset (1, 1) struct
    prediction (1, 1) struct
    options (1, 1) struct = struct()
end

started = utcNow();
clock = tic;
result = emptyResult(started);
events = repmat(emptyEvent(), 0, 1);

try
    emit("validate", 0.01, "Validating frequency recovery inputs");
    report = validate_channel_dataset(channelDataset);
    if ~report.is_valid
        error("run_v32_frequency_generation:InvalidDataset", ...
            "%s", strjoin(report.errors, " | "));
    end
    if ~strcmpi(string(channelDataset.domain), "ctf")
        error("run_v32_frequency_generation:NotCtf", ...
            "Frequency axis generation requires a CTF-domain import.");
    end
    knownIndices = double(prediction.known_context_parameter_sample_index(:));
    targetIndices = double(prediction.target_parameter_sample_index(:));
    if isempty(knownIndices) || isempty(targetIndices)
        error("run_v32_frequency_generation:MissingIndices", ...
            "Prediction carries no known/target subcarrier indices.");
    end

    emit("recover", 0.30, "Recovering missing in-band subcarriers");
    H = channelDataset.ctf.H;              % [Tx, Rx, Nf, Nt, N_sample]
    if size(H, 4) > 1 || size(H, 5) > 1
        error("run_v32_frequency_generation:NotStaticSpectrum", ...
            "Frequency axis import must be a static spectrum (Nt=1, N_sample=1).");
    end
    H = reshape(double(H), size(H, 1), size(H, 2), size(H, 3));
    % The imported CTF may carry values at every subcarrier; the task
    % partition decides known/target. Recovery reads only the known
    % subcarriers (indexed access inside the recovery helpers), so
    % target-subcarrier input values are never read (leakage-free).
    % v3.2-4a 1A: structure-based dispatch (contiguous block -> delay-domain
    % OMP sparse; otherwise complex linear interpolation).
    [HRecovered, recoveryMethod] = recover_inband_ctf_hybrid( ...
        H, knownIndices, targetIndices);

    emit("assemble", 0.55, "Assembling complete CTF dataset");
    frequencyHz = double(channelDataset.axes.frequency_hz(:));
    HCanonical = reshape(HRecovered, ...
        [size(H, 1), size(H, 2), size(H, 3), 1, 1]);
    axes = struct("frequency_hz", frequencyHz, "sample_index", 1);
    metadata = channelDataset.metadata;
    metadata.source = "full_6gpcm_public_api_frequency_recovered";
    metadata.sample_semantics = "ordered_frequency";
    metadata.center_frequency_hz = mean(frequencyHz);
    metadata.subcarrier_spacing_hz = median(diff(frequencyHz));
    ctfDataset = create_channel_dataset("ctf", struct("H", HCanonical), ...
        axes, metadata);

    emit("cir", 0.70, "Deriving CIR by deterministic IFFT");
    cirDataset = ifft_ctf_to_cir(ctfDataset);

    emit("characteristics", 0.85, "Running the characteristic engine");
    analysis = analyze_channel_characteristics(cirDataset, ...
        Region="all", ModuleRole="prediction");

    emit("result", 0.95, "Assembling prediction result");
    request = buildRequest(channelDataset, prediction, ...
        knownIndices, targetIndices, frequencyHz, HRecovered, recoveryMethod);
    predictionResult = create_prediction_result( ...
        request, cirDataset, ctfDataset, analysis, ...
        repmat(struct(), 0, 1), struct("method", "frequency_recovery"), ...
        "v32-4a-frequency-recovery");

    result.success = true;
    result.outcome = "SUCCEEDED";
    result.status = "PASS";
    result.formal_eligible = true;
    result.prediction_result = predictionResult;
    emit("complete", 1.0, "Frequency recovery completed");
catch exception
    result.errors = string(exception.identifier) + " | " + ...
        string(exception.message);
end
result.events = events;
result.runtime.finished_utc = utcNow();
result.runtime.elapsed_s = toc(clock);
if ~result.success
    result.status = "FAIL";
    result.outcome = "FAILED";
    result.formal_eligible = false;
end
result.errors = uniqueNonempty(result.errors);

    function emit(phase, progress, message)
        event = struct( ...
            "phase", string(phase), ...
            "target_number", 1, ...
            "target_count", double(numel(prediction.target_parameter_sample_index)), ...
            "progress", max(0, min(1, double(progress))), ...
            "message", string(message), ...
            "timestamp_utc", utcNow());
        events(end + 1, 1) = event; %#ok<AGROW>
        if isfield(options, "progress_callback") && ...
                ~isempty(options.progress_callback)
            options.progress_callback(event);
        end
    end
end

function request = buildRequest(channelDataset, prediction, ...
        knownIndices, targetIndices, frequencyHz, HRecovered, recoveryMethod)
% Assemble the canonical v3 request consumed by create_prediction_result.
% The predicted parameters are the recovered magnitude/phase at target
% subcarriers (median over Tx/Rx through the complex mean).
nf = size(HRecovered, 3);
targetMean = mean(HRecovered(:, :, targetIndices), [1, 2]);
predicted = [abs(targetMean(:)), angle(targetMean(:))];  % [T, 2]
if recoveryMethod == "delay_domain_sparse"
    executionContract = "in_band_missing_subcarrier_recovery_delay_omp";
else
    executionContract = "in_band_missing_subcarrier_recovery_linear";
end
request = struct( ...
    "task_type", "interpolation", ...
    "task_axis", "frequency", ...
    "target_parameter_sample_index", targetIndices(:), ...
    "target_axis_values", frequencyHz(targetIndices(:)), ...
    "parameter_names", ["magnitude", "phase"], ...
    "parameter_units", ["linear", "rad"], ...
    "predicted_parameters", predicted, ...
    "dimensions", struct("Tx", size(HRecovered, 1), ...
        "Rx", size(HRecovered, 2), "Nf", nf, "Nt", 1, "N_sample", 1), ...
    "prediction_manifest", struct( ...
        "schema_version", "v3.2-4a-frequency.1", ...
        "selection", struct( ...
            "selected_model", recoveryMethod, ...
            "target_ground_truth_read_for_selection", false), ...
        "model", struct( ...
            "model_type", recoveryMethod, ...
            "execution_contract", executionContract), ...
        "adaptation", struct("requested_mode", "off", ...
            "status", "not_performed", "accepted", false), ...
        "request_contains_target_ground_truth", false, ...
        "known_subcarrier_index", knownIndices(:), ...
        "target_subcarrier_index", targetIndices(:), ...
        "recovery_dispatch", "structure_hybrid_1a_contiguous_block_ge_4", ...
        "cir_derivation", "deterministic_ifft_of_predicted_ctf", ...
        "target_region_channel_samples_read", false), ...
    "backend", "none_full_6gpcm_not_involved", ...
    "mode", "formal", ...
    "engine", struct("id", recoveryMethod, "version", "v3.2-4a-1a"), ...
    "scenario", struct(), ...
    "master_seed", 0, ...
    "parameter_sources", struct(), ...
    "ctf", struct("enabled", true, "frequency_hz", frequencyHz(:)));
end

function result = emptyResult(started)
result = struct( ...
    "schema_version", "v3.0-prediction-generation-service-result.1", ...
    "status", "FAIL", ...
    "outcome", "FAILED", ...
    "success", false, ...
    "cancelled", false, ...
    "formal_eligible", false, ...
    "prediction_result", struct(), ...
    "target_diagnostics", repmat(emptyEvent(), 0, 1), ...
    "validation", struct(), ...
    "cache_key", "v32-4a-frequency-recovery", ...
    "warnings", strings(0, 1), ...
    "errors", strings(0, 1), ...
    "events", repmat(emptyEvent(), 0, 1), ...
    "runtime", struct( ...
        "started_utc", started, ...
        "finished_utc", "", ...
        "elapsed_s", NaN));
end

function event = emptyEvent()
event = struct("phase", "", "target_number", 0, ...
    "target_count", 0, "progress", 0, "message", "", ...
    "timestamp_utc", "");
end

function values = uniqueNonempty(values)
values = string(values(:));
values = values(strlength(strtrim(values)) > 0);
values = unique(values, "stable");
end

function value = utcNow()
value = string(datetime("now", "TimeZone", "UTC", ...
    "Format", "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"));
end
