function result = run_v32_3c_frequency_end_to_end()
%RUN_V32_3C_FREQUENCY_END_TO_END v3.2-3c Frequency-axis end-to-end chain.
%   Loads one in-band CTF spectrum, recovers missing subcarriers with linear
%   interpolation (the v3.2-2b recommended Frequency method), assembles the
%   complete CTF dataset, derives the CIR by IFFT (labelled), runs the shared
%   characteristic engine (6 plots for wideband static MIMO), and assembles a
%   canonical prediction result. Full 6GPCM is not involved.

%% 1. Load the exported Frequency corpus and take one spectrum.
corpusFile = fullfile( ...
    "D:\Codex_Feiyi\ChanAI-Pulse-v3.1-assets\corpora\chanaipulse-v3.2-corpus.1", ...
    "frequency_inband_ctf.h5");
[ctfReal, ctfImag, knownIdx, targetIdx, freqHz] = readSpectrum(corpusFile, 0);
nf = size(ctfReal, 3);      % [Tx, Rx, Nf]
rxCount = size(ctfReal, 2);
txCount = size(ctfReal, 1);
H = ctfReal + 1j * ctfImag; % [Tx, Rx, Nf]

%% 2. Linear interpolation recovery per (tx, rx) over the frequency axis.
HRecovered = zeros(size(H));
for tx = 1:txCount
    for rx = 1:rxCount
        values = squeeze(H(tx, rx, :));       % [Nf]
        known = sort(knownIdx(:));
        knownValues = values(known);
        HRecovered(tx, rx, :) = interp1(known, knownValues, ...
            (1:nf).', "linear", "extrap");
    end
end

%% 3. Assemble the complete CTF dataset (v3 contract).
HCanonical = reshape(HRecovered, [txCount, rxCount, nf, 1, 1]);
axes = struct( ...
    "frequency_hz", freqHz(:), ...
    "sample_index", 1);
metadata = struct( ...
    "source", "full_6gpcm_public_api_frequency_recovered", ...
    "sample_semantics", "ordered_frequency", ...
    "center_frequency_hz", mean(freqHz), ...
    "subcarrier_spacing_hz", median(diff(freqHz)));
ctfDataset = create_channel_dataset("ctf", struct("H", HCanonical), ...
    axes, metadata);

%% 4. Derive CIR by IFFT (labelled; not a prediction).
cirDataset = ifftCtfToCir(ctfDataset);

%% 5. Run the shared characteristic engine (6 plots for wideband static MIMO).
analysis = analyze_channel_characteristics(cirDataset, ...
    Region="all", ModuleRole="prediction");

%% 6. Assemble a canonical prediction result.
request = struct( ...
    "task_type", "interpolation", ...
    "task_axis", "frequency", ...
    "target_parameter_sample_index", targetIdx(:), ...
    "target_axis_values", freqHz(targetIdx), ...
    "parameter_names", ["magnitude", "phase"], ...
    "parameter_units", ["linear", "rad"], ...
    "predicted_parameters", [], ...
    "dimensions", struct("Tx", txCount, "Rx", rxCount, ...
        "Nf", nf, "Nt", 1, "N_sample", 1), ...
    "prediction_manifest", struct( ...
        "schema_version", "v3.2-3c-frequency.1", ...
        "selection", struct( ...
            "selected_model", "linear_interpolation", ...
            "target_ground_truth_read_for_selection", false), ...
        "model", struct( ...
            "model_type", "linear_interpolation", ...
            "execution_contract", "in_band_missing_subcarrier_recovery"), ...
        "adaptation", struct("requested_mode", "off", ...
            "status", "not_performed", "accepted", false), ...
        "request_contains_target_ground_truth", false, ...
        "known_subcarrier_index", knownIdx, ...
        "target_subcarrier_index", targetIdx, ...
        "cir_derivation", "deterministic_ifft_of_predicted_ctf", ...
        "target_region_channel_samples_read", false), ...
    "backend", "none_full_6gpcm_not_involved", ...
    "mode", "formal", ...
    "engine", struct("id", "linear_interpolation", "version", "v3.2-2b"), ...
    "scenario", struct(), ...
    "master_seed", 0, ...
    "parameter_sources", struct(), ...
    "ctf", struct("enabled", true, "frequency_hz", freqHz(:)));
result = create_prediction_result(request, cirDataset, ctfDataset, ...
    analysis, repmat(struct(), 0, 1), struct("method", "frequency_recovery"), ...
    "v32-3c-frequency-cache");

%% 7. Verify.
assert(~isempty(fieldnames(result.cir_dataset)), "CIR must exist.");
assert(~isempty(fieldnames(result.ctf_dataset)), "CTF must exist.");
assert(~isempty(fieldnames(result.analysis)), ...
    "Characteristic analysis must exist.");
analysisNames = string(fieldnames(result.analysis)).';
fprintf("PASS: v3.2-3c Frequency end-to-end chain.\n");
fprintf("  Nf=%d  Rx=%d  Tx=%d  recovered targets=%d\n", ...
    nf, rxCount, txCount, numel(targetIdx));
fprintf("  CIR domain=%s  CTF present=%d\n", ...
    result.cir_dataset.domain, ~isempty(fieldnames(result.ctf_dataset)));
fprintf("  analysis fields: %s\n", strjoin(analysisNames, ", "));
fprintf("  recovered magnitude mean abs error on targets: %.4f\n", ...
    mean(abs(abs(HRecovered(targetIdx)) - abs(H(targetIdx)))));
end

function [realPart, imagPart, knownIdx, targetIdx, freqHz] = ...
        readSpectrum(filePath, spectrumIndex)
% Exported HDF5 stores [Tx, Rx, Nf, N_spectrum] for CTF and [Nf, N] for
% frequency_hz (MATLAB column-major write; see export script).
realAll = h5read(filePath, "/ctf_real");    % [Tx, Rx, Nf, N]
imagAll = h5read(filePath, "/ctf_imag");
realPart = squeeze(realAll(:, :, :, spectrumIndex + 1));  % [Tx, Rx, Nf]
imagPart = squeeze(imagAll(:, :, :, spectrumIndex + 1));
knownAll = h5read(filePath, "/known_index");   % [K, N]
knownIdx = knownAll(:, spectrumIndex + 1);
knownIdx = knownIdx(~isnan(knownIdx));
targetAll = h5read(filePath, "/target_index"); % [T, N]
targetIdx = targetAll(:, spectrumIndex + 1);
targetIdx = targetIdx(~isnan(targetIdx));
freqAll = h5read(filePath, "/frequency_hz");   % [Nf, N]
freqHz = freqAll(:, spectrumIndex + 1);
end

function cir = ifftCtfToCir(ctfDataset)
% Deterministic IFFT of the predicted CTF to the time-delay domain.
H = ctfDataset.ctf.H;                       % [Tx, Rx, Nf, Nt, N_sample]
coefficient = ifft(H, [], 3);
nf = size(H, 3);
spacing = double(ctfDataset.axes.frequency_hz(2) - ...
    ctfDataset.axes.frequency_hz(1));
delayAxis = reshape((0:nf - 1) / (nf * spacing), [1, 1, nf, 1, 1]);
delayS = repmat(delayAxis, [size(coefficient, 1), size(coefficient, 2), ...
    1, size(coefficient, 4), size(coefficient, 5)]);
pathValid = true(size(coefficient));
payload = struct( ...
    "coefficient", coefficient, ...
    "delay_s", delayS, ...
    "path_valid", pathValid);
% CIR uses its own axes (no frequency_hz); metadata marks the derivation.
cirAxes = struct("sample_index", 1);
cirMetadata = ctfDataset.metadata;
cirMetadata.source = string(cirMetadata.source) + "_deterministic_ifft";
cir = create_channel_dataset("cir", payload, cirAxes, cirMetadata);
end
