function result = run_v32_3b_space_end_to_end(engineRoot)
%RUN_V32_3B_SPACE_END_TO_END v3.2-3b Space-axis end-to-end chain.
%   Loads one Space route's DS/KF known sequence, predicts the target
%   positions with Persistence (the v3.2-2a recommended Space model),
%   assembles the full P8 generator parameters (predicted DS/KF + frozen
%   fields), and runs the prediction-generation service to produce target
%   CIR/CTF with real sample_position_m coordinates.

arguments
    engineRoot (1, 1) string = ""
end

if engineRoot == ""
    engineRoot = resolve_full_6gpcm_root().root;
end

%% 1. Load the Space corpus sequence for one route.
corpusFile = fullfile( ...
    "D:\Codex_Feiyi\ChanAI-Pulse-v3.1-assets\corpora\chanaipulse-v3.2-corpus.1", ...
    "space_extrapolation_ds_kf.h5");
sequence = readSpaceSequence(corpusFile, "space-001");

%% 2. Known region: first 16 positions; target: next 4.
knownValues = sequence.values(1:16, :);
knownIndex = sequence.parameter_sample_index(1:16);
targetIndex = sequence.parameter_sample_index(17:20);
targetPositionM = sequence.sample_position_m(17:20, :);

%% 3. Persistence prediction (v3.2-2a recommended Space model).
predicted = repmat(knownValues(end, :), numel(targetIndex), 1);

%% 4. Assemble full P8 generator parameters.
frozen = struct( ...
    "DS_sigma", 0.35, "KF_sigma", 2.0, "r_DS", 2.66, ...
    "LNS_ksi", 3.33, "num_clusters", 12, "num_rays", 20);
parameterNames = ["DS_mu", "KF_mu", "DS_sigma", "KF_sigma", ...
    "r_DS", "LNS_ksi", "num_clusters", "num_rays"];
parameterUnits = ["log10_s", "dB", "log10_s_std", "dB", ...
    "dimensionless", "dB", "count", "count"];

%% 5. Build prediction and generation request.
prediction = struct( ...
    "schema_version", "v3.2-3b-space-prediction.1", ...
    "task_type", "extrapolation", ...
    "parameter_names", parameterNames, ...
    "parameter_units", parameterUnits, ...
    "prediction_parameters", zeros(1, numel(targetIndex), 8), ...
    "target_parameter_sample_index", targetIndex(:).', ...
    "selection", struct( ...
        "selected_model", "persistence", ...
        "selected_model_by_parameter", struct( ...
            "DS_mu", "persistence", "KF_mu", "persistence", ...
            "num_clusters", "frozen_known_anchor"), ...
        "target_ground_truth_read_for_selection", false), ...
    "adaptation", struct( ...
        "requested_mode", "off", "status", "not_performed", ...
        "accepted", false, "official_checkpoint_overwritten", false), ...
    "model", struct( ...
        "model_type", "persistence", ...
        "execution_contract", "known_region_persistence_extrapolation", ...
        "known_history_policy", "all_available"), ...
    "request_contains_target_ground_truth", false, ...
    "target_region_channel_samples_read", false, ...
    "known_context_parameters", knownValues, ...
    "known_context_parameter_sample_index", knownIndex(:).', ...
    "provenance", struct( ...
        "source", "v32_3b_space_end_to_end_probe", ...
        "target_channel_samples_read", false));

for targetNumber = 1:numel(targetIndex)
    for name = ["DS_mu", "KF_mu"]
        prediction.prediction_parameters(1, targetNumber, ...
            find(name == parameterNames)) = ...
            predicted(targetNumber, find(name == ["DS_mu", "KF_mu"]));
    end
    for name = ["DS_sigma", "KF_sigma", "r_DS", "LNS_ksi", ...
            "num_clusters", "num_rays"]
        prediction.prediction_parameters(1, targetNumber, ...
            find(name == parameterNames)) = frozen.(name);
    end
end

generationConfig = default_prediction_generation_config("full_6gpcm");
% Space axis maps to the position task axis (v3.2-0 contract: Space is the
% unified upgrade of sample/position).
generationConfig.task_axis = "position";
generationConfig.task_axis_unit = "m";
generationConfig.target_axis_values = targetPositionM(:, 1); % along-track x
generationConfig.dimensions.Tx = 2;
generationConfig.dimensions.Rx = 4;
generationConfig.dimensions.Nt = 1;
generationConfig.dimensions.Npath = 6;
generationConfig.master_seed = 43;
generationConfig.mode = "formal";
generationConfig.generator_overrides.backend_options.full_interface = ...
    "public_api";
generationConfig.generator_overrides.backend_options.full_track_speed_mps = 8.0;
request = create_prediction_generation_request(prediction, generationConfig);

%% 6. Run generation service.
result = run_prediction_generation(request, struct());

%% 7. Verify.
assert(result.success, "Space end-to-end generation failed: %s", ...
    strjoin(result.errors, " | "));
predictionResult = result.prediction_result;
cir = predictionResult.cir_dataset;
assert(cir.dimensions.N_sample == numel(targetIndex), ...
    "Target CIR must have one sample per target position.");
assert(isfield(cir.axes, "sample_position_m"), ...
    "Target CIR must carry sample_position_m.");
assert(isfield(predictionResult, "ctf_dataset") && ...
    ~isempty(fieldnames(predictionResult.ctf_dataset)), ...
    "CTF must be produced when enabled.");

fprintf("PASS: v3.2-3b Space end-to-end chain.\n");
fprintf("  targets=%d  CIR samples=%d  CTF present=%d\n", ...
    numel(targetIndex), cir.dimensions.N_sample, ...
    ~isempty(fieldnames(predictionResult.ctf_dataset)));
fprintf("  target positions (x) [%.3f, %.3f] m\n", ...
    targetPositionM(1, 1), targetPositionM(end, 1));
fprintf("  predicted DS %.4f  KF %.3f\n", ...
    predicted(1, 1), predicted(1, 2));
end

function sequence = readSpaceSequence(filePath, groupId)
bundle = read_predictor_data_hdf5(filePath);
seq = bundle.parameter_sequence;
rows = find(seq.group_id == groupId);
n = numel(rows);
% The v3.2-1 Space corpus routes move at 8 m/s sampled at 100 ms => 0.8 m/step.
positions = zeros(n, 3);
positions(:, 1) = (0:n - 1).' * 0.8;
sequence = struct( ...
    "values", seq.values(rows, :), ...
    "parameter_sample_index", seq.parameter_sample_index(rows), ...
    "sample_position_m", positions);
end
