% ChanAI Pulse characterization rendering regression test.
% Uses invisible UI axes and synthetic in-memory metrics only.
clearvars;
clc;

repoRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(fullfile(repoRoot, "app")));
addpath(genpath(fullfile(repoRoot, "core")));

fig = uifigure("Visible", "off", "Position", [100, 100, 900, 600]);
cleanup = onCleanup(@() delete(fig)); %#ok<NASGU>
layout = uigridlayout(fig, [2, 2]);
axesHandles = struct( ...
    "angular", uiaxes(layout), ...
    "delay", uiaxes(layout), ...
    "spread", uiaxes(layout), ...
    "doppler", uiaxes(layout));

dpsdDbm = -80 + reshape(1:48, 12, 4) / 10;
metrics = analyze_channel_data(dpsdDbm, 100e6);
metrics.space.angle = linspace(-90, 90, 128);
metrics.space.psd = -abs(linspace(-20, 20, 128));

style = struct( ...
    "language", "EN", ...
    "primary_color", [0.000, 0.447, 0.741], ...
    "text_color", [0.10, 0.10, 0.10], ...
    "text_dim_color", [0.35, 0.35, 0.35]);
render_characterization_plots(axesHandles, metrics, style);

assert(string(axesHandles.angular.Title.String) == "Angle Power Spectrum", ...
    "English angular title changed.");
assert(string(axesHandles.delay.Title.String) == "Delay PSD", ...
    "English delay title changed.");
assert(string(axesHandles.spread.Title.String) == "Spread CDF", ...
    "English spread title changed.");
assert(string(axesHandles.doppler.Title.String) == "Doppler", ...
    "English Doppler title changed.");
assert(isequal(axesHandles.spread.YLim, [0, 1]), ...
    "Spread CDF y-axis must remain [0, 1].");
assert(~isempty(axesHandles.angular.Children) && ...
    ~isempty(axesHandles.delay.Children) && ...
    ~isempty(axesHandles.spread.Children) && ...
    ~isempty(axesHandles.doppler.Children), ...
    "Characterization plots must render visible children.");

style.language = "CN";
render_characterization_plots(axesHandles, metrics, style);
assert(contains(string(axesHandles.angular.Title.String), "角度功率谱"), ...
    "Chinese angular title changed.");
assert(contains(string(axesHandles.delay.Title.String), "时延功率谱密度"), ...
    "Chinese delay title changed.");

metrics.space.psd(:) = -1000;
metrics.time.y(:) = -1000;
style.language = "EN";
render_characterization_plots(axesHandles, metrics, style);
angularText = findobj(axesHandles.angular, "Type", "Text");
dopplerText = findobj(axesHandles.doppler, "Type", "Text");
assert(any(string({angularText.String}) == "No Data"), ...
    "Angular no-data placeholder changed.");
assert(any(string({dopplerText.String}) == "No Data"), ...
    "Doppler no-data placeholder changed.");

fprintf("PASS: characterization rendering preserves bilingual plots and axes.\n");
