% ChanAI Pulse generation rendering regression test.
% Uses invisible UI axes and deterministic synthetic generation only.
clearvars;
clc;

repoRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(fullfile(repoRoot, "app")));
addpath(genpath(fullfile(repoRoot, "core")));

config = default_6gpcm_lite_config();
config.snapshots = 8;
config.clusters = 5;
config.rays = 7;
config.delay_max_ns = 63;
config.random_seed = 20260716;
generationResult = generate_6gpcm_lite(config);

fig = uifigure("Visible", "off", "Position", [100, 100, 900, 420]);
cleanup = onCleanup(@() delete(fig)); %#ok<NASGU>
layout = uigridlayout(fig, [1, 2]);
axesHandles = struct( ...
    "pdp", uiaxes(layout), ...
    "cdf", uiaxes(layout));
style = struct( ...
    "language", "EN", ...
    "model_label", "Scenario 1", ...
    "primary_color", [0.000, 0.447, 0.741], ...
    "secondary_color", [0.850, 0.325, 0.098], ...
    "text_color", [0.10, 0.10, 0.10]);

rng(8128, "twister");
englishPlot = render_generation_plots(axesHandles, generationResult, style);
assert(string(axesHandles.pdp.Title.String) == ...
    "Delay Power Spectrum (Scenario 1)", "English PDP title changed.");
assert(string(axesHandles.cdf.Title.String) == "CDF of DS", ...
    "English CDF title changed.");
assert(isequal(axesHandles.pdp.XLim, [0, config.delay_max_ns]), ...
    "PDP delay range changed.");
assert(isequal(axesHandles.cdf.YLim, [0, 1]), ...
    "Generation CDF y-axis must remain [0, 1].");
assert(numel(axesHandles.pdp.Children) == 2, ...
    "PDP axes must contain the PDP and multipath components.");
assert(numel(axesHandles.cdf.Children) == 1, ...
    "CDF axes must contain exactly one curve.");
assert(all(isfinite(englishPlot.pdp_db)), ...
    "Rendered PDP contains invalid values.");
assert(all(diff(englishPlot.cdf_x) >= 0) && ...
    all(diff(englishPlot.cdf_y) >= -1e-12), ...
    "Rendered delay-spread CDF must be monotonic.");
assert(all(englishPlot.cdf_y >= 0 & englishPlot.cdf_y <= 1), ...
    "Rendered delay-spread CDF must remain within [0, 1].");

style.language = "CN";
style.model_label = "场景 1";
rng(8128, "twister");
chinesePlot = render_generation_plots(axesHandles, generationResult, style);
assert(contains(string(axesHandles.pdp.Title.String), "时延功率谱"), ...
    "Chinese PDP title changed.");
assert(string(axesHandles.cdf.Title.String) == "时延扩展的累积分布函数", ...
    "Chinese CDF title changed.");
assert(numel(axesHandles.pdp.Children) == 2 && ...
    numel(axesHandles.cdf.Children) == 1, ...
    "Repeated rendering must replace rather than stack curves.");
assert(isequal(englishPlot.pdp_db, chinesePlot.pdp_db), ...
    "Language selection must not change plotted PDP values.");

singleResult = generationResult;
singleResult.delay_spread_ns = generationResult.delay_spread_ns(1);
rng(8128, "twister");
singlePlot = render_generation_plots(axesHandles, singleResult, style);
assert(isequal(singlePlot.cdf_y, [0, 1, 1]), ...
    "Single-snapshot CDF fallback changed.");

fprintf("PASS: generation rendering preserves bilingual PDP and DS CDF plots.\n");
