% Step 11ABC training-corpus regression test (no external engine required).

clearvars;
clc;

repoRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(fullfile(repoRoot, "core")));

config = default_step11abc_config();
config.route.group_count = 8;
config.data.split_group_counts = [6, 1, 1];
corpus = create_step11abc_training_corpus("unused-for-embedded-profile", ...
    "Config", config, "UseExternalProfiles", false);

assert(isequal(corpus.config.parameter_bundles.P2, ...
    ["DS_mu", "KF_mu"]), "P2 parameter order changed.");
assert(isequal(corpus.config.parameter_bundles.P8, ...
    corpus.config.parameter_names), "P8 must retain canonical order.");
assert(corpus.summary.route_group_count == 8, "Unexpected group count.");
assert(corpus.bundles.extrapolation.P8.dataset.summary.N_example == 808, ...
    "Expected 8 routes x 101 extrapolation windows.");
assert(corpus.bundles.interpolation.P4.split.leakage_check.passed, ...
    "Route groups must never overlap across partitions.");
assert(all(corpus.sequence.label_source == "generator_truth"), ...
    "Training labels must be explicitly marked as generator truth.");
assert(all(mod(corpus.sequence.values(:, 7:8), 1) == 0, "all"), ...
    "Cluster/ray count labels must stay integral.");
assert(all(corpus.profiles{1}.parameter_sources == "versioned_default"), ...
    "Embedded profiles must expose per-parameter source provenance.");

%% samples_per_group is configuration, not a hidden 120-row constant
shortConfig = config;
shortConfig.route.samples_per_group = 80;
shortCorpus = create_step11abc_training_corpus( ...
    "unused-for-embedded-profile", "Config", shortConfig, ...
    "UseExternalProfiles", false);
assert(size(shortCorpus.sequence.values, 1) == 8 * 80, ...
    "Configured route length was not honored.");
assert(shortCorpus.summary.expected_examples_per_route == 61, ...
    "Expected windows must derive from 80 - 16 - 4 + 1.");
assert(shortCorpus.bundles.extrapolation.P8.dataset.summary.N_example == ...
    8 * 61, "Expected 8 routes x 61 configurable windows.");

%% PDP comparisons reuse one frozen grid and expose overflow power
featureDataset = struct("cir", struct( ...
    "coefficient", reshape(complex([1, 2, 1]), [1, 1, 3, 1, 1]), ...
    "delay_s", reshape([0, 0.5e-6, 2e-6], [1, 1, 3, 1, 1])));
features = compute_step11abc_cir_features( ...
    featureDataset, [0, 0.5e-6, 1e-6, Inf]);
assert(numel(features.pdp) == 3, "Common PDP grid shape changed.");
assert(features.delay_overflow_power_fraction > 0, ...
    "Out-of-range delay power must be visible in the overflow bin.");

%% Frozen selection loader rejects test leakage and verifies model hashes
registryRoot = string(tempname);
mkdir(registryRoot);
registryCleanup = onCleanup(@() rmdir(registryRoot, "s")); %#ok<NASGU>
modelRegistryPaths = [fullfile(registryRoot, "interpolation.json"), ...
    fullfile(registryRoot, "extrapolation.json")];
for path = modelRegistryPaths
    writelines("{}", path);
end
records = repmat(struct("task_type", "", "selected_bundle", "P8", ...
    "path", "", "sha256", ""), 2, 1);
tasks = ["interpolation", "extrapolation"];
for index = 1:2
    records(index).task_type = tasks(index);
    records(index).path = modelRegistryPaths(index);
    records(index).sha256 = sha256ForTest(modelRegistryPaths(index));
end
selection = struct( ...
    "schema_version", "v3.0-step11abc-bundle-selection.2", ...
    "evaluation_partition", "validation", ...
    "test_truth_used_for_selection", false, ...
    "decisions", struct( ...
        "interpolation", struct("selected_bundle", "P8"), ...
        "extrapolation", struct("selected_bundle", "P8")), ...
    "delay_grid", struct( ...
        "frozen_from_partition", "validation_truth_only", ...
        "overflow_bin_enabled", true, ...
        "finite_edges_s", [0, 1e-6]), ...
    "selected_model_registries", records);
selectionPath = fullfile(registryRoot, "selection.json");
writelines(string(jsonencode(selection)), selectionPath);
loaded = read_step11abc_system_registry(selectionPath, ...
    "RequireFinalTest", false);
assert(~loaded.test_truth_used_for_selection);
selection.test_truth_used_for_selection = true;
writelines(string(jsonencode(selection)), selectionPath);
leakageRejected = false;
try
    read_step11abc_system_registry(selectionPath, ...
        "RequireFinalTest", false);
catch exception
    leakageRejected = exception.identifier == ...
        "read_step11abc_system_registry:TestLeakage";
end
assert(leakageRejected, "System-registry loader must reject test leakage.");

fprintf("PASS: Step 11ABC corpus contract, P-bundle order, and group split are valid.\n");

function value = sha256ForTest(path)
fid = fopen(path, "rb");
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
bytes = fread(fid, Inf, "*uint8");
digest = javaMethod("getInstance", ...
    "java.security.MessageDigest", "SHA-256");
digest.update(typecast(uint8(bytes(:)), "int8"));
raw = typecast(int8(digest.digest()), "uint8");
value = lower(string(reshape(dec2hex(raw, 2).', 1, [])));
end
