% Optional real external full 6GPCM Step 11 end-to-end test.

scriptPath = string(mfilename("fullpath"));
repositoryRoot = fileparts(fileparts(scriptPath));
addpath(genpath(fullfile(repositoryRoot, "core")));

engineRoot = string(getenv("CHANAI_FULL_6GPCM_ROOT"));
if strlength(strtrim(engineRoot)) == 0
    fprintf("SKIP: CHANAI_FULL_6GPCM_ROOT is not configured.\n");
    return;
end

values = zeros(1, 4, 2);
values(1, :, 1) = [-7.925, -7.90, -7.875, -7.85];
values(1, :, 2) = [-0.39, -0.20, 0.00, 0.20];
prediction = struct( ...
    "schema_version", "v3.0-predicted-channel-parameters.1", ...
    "request_contains_target_ground_truth", false, ...
    "task_type", "extrapolation", ...
    "parameter_names", ["DS_mu", "KF_mu"], ...
    "parameter_units", ["log10_s", "dB"], ...
    "prediction_parameters", values, ...
    "target_parameter_sample_index", [17, 18, 19, 20], ...
    "selection", struct("mode", "auto", ...
        "selected_model", "tcn"), ...
    "adaptation", struct("status", "skipped", ...
        "accepted", false), ...
    "model", struct("checkpoint", "external-smoke", ...
        "manifest_schema_version", ...
        "v3.0-predictor-model-manifest.1"));

config = default_prediction_generation_config("full_6gpcm");
config.mode = "formal";
config.engine_root = engineRoot;
config.dimensions.Nf = 16;
config.ctf.frequency_hz = linspace(15.95e9, 16.05e9, 16).';
request = create_prediction_generation_request(prediction, config);
result = run_prediction_generation(request);
assert(result.success, strjoin(result.errors, " | "));
assert(result.formal_eligible);
assert(isequal(size5( ...
    result.prediction_result.cir_dataset.cir.coefficient), ...
    [2, 2, 240, 2, 4]));
assert(isequal(size5(result.prediction_result.ctf_dataset.ctf.H), ...
    [2, 2, 16, 2, 4]));
assert(all(arrayfun(@(item) ...
    item.backend_manifest.core_unchanged, ...
    result.target_diagnostics)));
assert(all(~[result.target_diagnostics.target_position_injected]));
assert(result.prediction_result.analysis.metrics. ...
    angular_power_spectrum.available);
assert(result.prediction_result.analysis.metrics. ...
    angular_spread_cdf.available);
assert(result.prediction_result.analysis.registry. ...
    available_standard_plot_count == 6);
fprintf("PASS: real full 6GPCM Step 11 formal four-target CIR/CTF chain.\n");

function shape = size5(value)
shape = [size(value, 1), size(value, 2), size(value, 3), ...
    size(value, 4), size(value, 5)];
end
