% Validate a tiny local measured-data sample against extracted core helpers.
% Read-only: no training, no prediction, no measured data modification.

clearvars;
clc;

repoRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(fullfile(repoRoot, "core")));

previewRoot = fullfile(repoRoot, "datasets", "measured", "extracted_preview");
reportPath = fullfile(repoRoot, "datasets", "measured", "REAL_DATA_VALIDATION.md");

files = dir(fullfile(previewRoot, "**", "*.mat"));
if isempty(files)
    error("No extracted measured .mat preview files found. Run tests/test_measured_dataset_probe.m first.");
end

sampleCount = min(3, numel(files));
samples = files(1:sampleCount);

fid = fopen(reportPath, "w", "n", "UTF-8");
cleanupObj = onCleanup(@() fclose(fid));

fprintf(fid, "# Real Measured Data Validation\n\n");
fprintf(fid, "Generated by `tests/test_real_data_validation.m`.\n\n");
fprintf(fid, "Scope: read-only loading and characterization of a tiny local sample. No training and no prediction were performed.\n\n");

fprintf(fid, "## 1. Selected Samples\n\n");
fprintf(fid, "- Sample count: %d\n", sampleCount);
fprintf(fid, "- Source root: `%s`\n\n", previewRoot);

allOk = true;

for i = 1:sampleCount
    matPath = fullfile(samples(i).folder, samples(i).name);
    relPath = erase(string(matPath), string(previewRoot) + filesep);
    fprintf("Validating sample %d: %s\n", i, matPath);

    fprintf(fid, "### Sample %d\n\n", i);
    fprintf(fid, "- Path: `%s`\n", relPath);

    try
        rawStruct = load(matPath);
        wh = whos("-file", matPath);
        fprintf(fid, "- Variables: %s\n", strjoin(string({wh.name}), ", "));

        data = extract_raw_data(rawStruct);
        fprintf(fid, "- `extract_raw_data`: success\n");
        fprintf(fid, "- Extracted type: `%s`\n", class(data));
        fprintf(fid, "- Extracted size: `%s`\n", strjoin(string(size(data)), "x"));
        fprintf(fid, "- Complex: %s\n", yesNo(~isreal(data)));

        [angles, aps_dB] = calculate_angular_spectrum(data);
        fprintf(fid, "- `calculate_angular_spectrum`: success\n");
        fprintf(fid, "- Angular axis size: `%s`\n", strjoin(string(size(angles)), "x"));
        fprintf(fid, "- APS size: `%s`\n", strjoin(string(size(aps_dB)), "x"));

        if isreal(data)
            dpsd_dbm = squeeze(data);
        else
            if ndims(data) >= 3
                pdp_lin = squeeze(sum(sum(abs(data).^2, 1), 2));
            else
                pdp_lin = abs(data).^2;
            end
            if size(pdp_lin, 1) == 1 && size(pdp_lin, 2) > 1
                pdp_lin = pdp_lin.';
            end
            dpsd_dbm = 10 * log10(pdp_lin / 1e-3 + 1e-20);
        end

        dpsd_dbm = real(squeeze(dpsd_dbm));
        if isvector(dpsd_dbm)
            dpsd_dbm = dpsd_dbm(:);
        end
        if size(dpsd_dbm, 2) < 2
            dpsd_dbm = [dpsd_dbm, dpsd_dbm + randn(size(dpsd_dbm))*0.001];
        end

        metrics = analyze_channel_data(dpsd_dbm, 100e6);
        fprintf(fid, "- `analyze_channel_data`: success\n");
        fprintf(fid, "- Analysis matrix size: `%s`\n", strjoin(string(size(dpsd_dbm)), "x"));
        fprintf(fid, "- Delay profile points: %d\n", numel(metrics.delay.x));
        fprintf(fid, "- DS CDF points: %d\n", numel(metrics.delay.cdf_x));
        fprintf(fid, "- Plot generation: not run in this automated read-only validation; metrics required for plots were generated.\n");
        fprintf(fid, "- Dimension issue: %s\n\n", detectDimensionIssue(data, dpsd_dbm));
    catch ME
        allOk = false;
        fprintf(fid, "- Validation status: FAILED\n");
        fprintf(fid, "- Error: `%s`\n\n", ME.message);
    end
end

fprintf(fid, "## 2. Read Flow\n\n");
fprintf(fid, "The validation used this flow:\n\n");
fprintf(fid, "```text\n.mat file -> load -> extract_raw_data -> sage{1}.cir -> angular spectrum -> DPSD-like matrix -> analyze_channel_data\n```\n\n");

fprintf(fid, "## 3. Result\n\n");
if allOk
    fprintf(fid, "- Overall result: success for the selected tiny sample.\n");
    fprintf(fid, "- Current helpers can unwrap `sage{1}.cir` and generate characterization metrics.\n");
else
    fprintf(fid, "- Overall result: at least one selected sample failed.\n");
end

fprintf(fid, "\n## 4. Converter Recommendation\n\n");
fprintf(fid, "A converter is still recommended before broad training or benchmarking. The current App can likely read these files, but a converter can standardize frequency band, scenario labels, bandwidth assumptions, dimensions, metadata, and batch loading behavior.\n\n");
fprintf(fid, "No measured data should be copied to `demo_data/` or committed to Git.\n");

fprintf("Validation report written to: %s\n", reportPath);

function text = yesNo(value)
if value
    text = "yes";
else
    text = "no";
end
end

function text = detectDimensionIssue(data, dpsd_dbm)
if ndims(data) > 3
    text = "source has more than 3 dimensions; scenario-specific conversion should be reviewed";
elseif size(dpsd_dbm, 1) < 2
    text = "analysis matrix has very few delay/frequency bins";
else
    text = "no blocking issue detected in selected sample";
end
end

