% v3.1-7 real-P8 extraction, local backtest, and product safety checks.
clearvars;
clc;

repoRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(repoRoot);
addpath(genpath(fullfile(repoRoot, "core")));

pythonExecutable = string(getenv("CHANAI_STEP10_PYTHON"));
if strlength(pythonExecutable) == 0
    pythonExecutable = "python";
end
fixture = fullfile(repoRoot, "demo_data", "v3_standard_fixtures", ...
    "wideband_static_siso_cir.h5");
imported = import_channel_dataset(fixture, struct( ...
    "task_mode", "extrapolation", ...
    "task_axis", "sample", ...
    "task_preset", "manual", ...
    "known_indices", 1:26, ...
    "target_indices", 27:32));
assert(imported.status == "PASS");

optimizer = default_optimization_config("lite_6gpcm");
calibration = struct( ...
    "success", true, ...
    "selected_strategy", "grid", ...
    "best", struct("parameters", optimizer.generator_config.model), ...
    "manifest", struct("schema_version", "v3.1-7-test"));

%% P8 rows are ordered local fits and never read target channel samples.
extraction = extract_known_region_p8_sequence( ...
    imported.dataset, imported.task, calibration, "lite_6gpcm");
assert(extraction.valid_row_count == 26);
assert(~extraction.target_channel_samples_read);
assert(isequal(double(extraction.sequence.parameter_sample_index(:)).', 1:26));
assert(all(std(double(extraction.sequence.values(:, [1, 2])), 0, 1) > 0));
assert(isequal(string( ...
    extraction.sequence.provenance.locally_observed_parameter_names(:)).', ...
    ["DS_mu", "KF_mu", "num_clusters"]));
assert(isequal(string( ...
    extraction.sequence.provenance.imputed_parameter_names(:)).', ...
    ["DS_sigma", "KF_sigma", "r_DS", "LNS_ksi", "num_rays"]));

ctfFile = fullfile(repoRoot, "demo_data", "v3_standard_fixtures", ...
    "wideband_static_siso_ctf.h5");
ctfImported = import_channel_dataset(ctfFile, struct( ...
    "task_mode", "extrapolation", "task_axis", "sample", ...
    "task_preset", "manual", "known_indices", 1:26, ...
    "target_indices", 27:32));
ctfExtraction = extract_known_region_p8_sequence( ...
    ctfImported.dataset, ctfImported.task, calibration, "lite_6gpcm");
assert(ctfExtraction.valid_row_count == 26);
assert(all(isfinite(ctfExtraction.sequence.values), "all"));
assert(~ctfExtraction.target_channel_samples_read);

% Narrowband/single-path inputs cannot identify local delay spread. They
% freeze DS_mu instead of failing the complete prediction workflow.
narrowFile = fullfile(repoRoot, "demo_data", "v3_standard_fixtures", ...
    "narrowband_static_siso_cir.h5");
narrowImported = import_channel_dataset(narrowFile, struct( ...
    "task_mode", "extrapolation", "task_axis", "sample", ...
    "task_preset", "manual", "known_indices", 1:16, ...
    "target_indices", 17:20));
narrowExtraction = extract_known_region_p8_sequence( ...
    narrowImported.dataset, narrowImported.task, calibration, "lite_6gpcm");
assert(ismember("DS_mu", string(narrowExtraction.sequence.provenance. ...
    imputed_parameter_names)));
assert(~ismember("DS_mu", string(narrowExtraction.sequence.provenance. ...
    locally_observed_parameter_names)));

changedTarget = imported.dataset;
target = imported.task.target_indices;
changedTarget.cir.coefficient(:, :, :, :, target) = ...
    changedTarget.cir.coefficient(:, :, :, :, target) * 1e6 + (10 + 20i);
changed = extract_known_region_p8_sequence( ...
    changedTarget, imported.task, calibration, "lite_6gpcm");
assert(isequaln(extraction.sequence.values, changed.sequence.values), ...
    "Changing target ground truth must not alter known-region P8 extraction.");

%% Auto mode uses local evidence and freezes unidentifiable fields.
config = struct( ...
    "python_executable", pythonExecutable, ...
    "device", "cpu", ...
    "adaptation_mode", "off");
automatic = run_v31_product_safety_gate(extraction, imported.task, config);
assert(string(automatic.selection.recommended_model) == "kalman");
assert(any(string(automatic.selection.selected_model) == ...
    ["hybrid", "persistence", "linear", "quadratic", "holt", ...
    "harmonic", "ar", "kalman", "gru", "lstm", "tcn", ...
    "dlinear", "nlinear"]));
assert(string(automatic.selection.selected_model) == "hybrid");
assert(string(automatic.selection.selected_model_by_parameter.DS_mu) == ...
    "harmonic");
assert(string(automatic.selection.selected_model_by_parameter.KF_mu) == "ar");
assert(string(automatic.selection.selected_model_by_parameter.num_clusters) == ...
    "persistence");
assert(automatic.backtest.example_count == 5);
assert(logical(automatic.backtest.passed));
assert(string(automatic.continuity.effect) == "warning_only");
assert(~logical(automatic.request_contains_target_ground_truth));
assert(~logical(automatic.target_region_channel_samples_read));
assert(isequal(size(automatic.prediction_parameters), [1, 6, 8]));
frozenColumns = [3, 4, 5, 6, 8];
predicted = reshape(automatic.prediction_parameters, [6, 8]);
anchor = automatic.known_context_parameters(end, frozenColumns);
assert(all(predicted(:, frozenColumns) == anchor, "all"));

%% External holdout reads target observables only after prediction completes.
% This block is acceptance evidence, never an input to model selection.
holdoutTask = struct("mode", "extrapolation", ...
    "known_indices", (27:32).', "target_indices", 1);
holdoutTruth = extract_known_region_p8_sequence( ...
    imported.dataset, holdoutTask, calibration, "lite_6gpcm");
truthValues = holdoutTruth.sequence.values;
registry = jsondecode(fileread(fullfile(repoRoot, "models", "official", ...
    "v3.1.0", "extrapolation", ...
    "extrapolation_model_registry_v2.json")));
normalizationStd = double(registry.preprocessing.normalization_std(:)).';
observedColumns = [1, 2, 7];
holdoutNrmse = sqrt(mean(((predicted(:, observedColumns) - ...
    truthValues(:, observedColumns)) ./ ...
    normalizationStd(observedColumns)).^2, "all"));
assert(holdoutNrmse <= 0.10, ...
    "The public auto fixture must remain well below a visibly poor trajectory.");

%% Arbitrary interpolation gaps use every known point on both sides.
interpolated = import_channel_dataset(fixture, struct( ...
    "task_mode", "interpolation", "task_axis", "sample", ...
    "task_preset", "manual", ...
    "known_indices", [1:12, 21:32], "target_indices", 13:20));
interpolationExtraction = extract_known_region_p8_sequence( ...
    interpolated.dataset, interpolated.task, calibration, "lite_6gpcm");
interpolationConfig = config;
interpolationConfig.selection_mode = "manual";
interpolationConfig.requested_model = "harmonic";
interpolationPrediction = run_v31_product_safety_gate( ...
    interpolationExtraction, interpolated.task, interpolationConfig);
assert(isequal(size(interpolationPrediction.prediction_parameters), [1, 8, 8]));
assert(numel(interpolationPrediction.known_context_parameter_sample_index) == 24);
assert(string(interpolationPrediction.selection.selected_model) == "harmonic");
assert(~logical(interpolationPrediction.target_region_channel_samples_read));

%% Manual performance guards warn rather than reject.
task4 = imported.task;
task4.target_indices = (27:30).';
config.selection_mode = "manual";
config.requested_model = string(automatic.backtest.best_safe_baseline);
manual = run_v31_product_safety_gate(extraction, task4, config);
assert(string(manual.selection.selected_model) == config.requested_model);
manualValues = reshape(manual.prediction_parameters, [4, 8]);
manualAnchor = manual.known_context_parameters(end, frozenColumns);
assert(all(manualValues(:, frozenColumns) == manualAnchor, "all"));

config.requested_model = "gru";
manualGru = run_v31_product_safety_gate(extraction, imported.task, config);
assert(string(manualGru.selection.selected_model) == "gru");
assert(isequal(size(manualGru.prediction_parameters), [1, 6, 8]));
assert(contains(string(manualGru.model.component_models.gru.execution_contract), ...
    "rolling"));
assert(logical(manualGru.stabilization.applied), ...
    "An extreme manual-model regret must use the transparent local guard.");
gruValues = reshape(manualGru.prediction_parameters, [6, 8]);
gruHoldoutNrmse = sqrt(mean(((gruValues(:, observedColumns) - ...
    truthValues(:, observedColumns)) ./ ...
    normalizationStd(observedColumns)).^2, "all"));
assert(gruHoldoutNrmse <= 0.20, ...
    "The guarded public-fixture GRU trajectory is still visibly implausible.");
assert(logical(manualGru.target_region_channel_samples_read) == false);
generationConfig = default_prediction_generation_config("lite_6gpcm");
generationConfig.target_axis_values = double(imported.task.axis_values( ...
    imported.task.target_indices));
generationRequest = create_prediction_generation_request( ...
    manualGru, generationConfig);
assert(logical(generationRequest.prediction_manifest.stabilization.applied));
assert(numel(generationRequest.prediction_manifest. ...
    known_context_parameter_sample_index) == 26);
assert(~isempty(generationRequest.prediction_manifest.warnings));

%% Advanced UI exposes all registered choices without silently changing them.
app = ChannelSimulator(Visible="off");
cleanup = onCleanup(@() delete(app));
for model = ["persistence", "linear", "quadratic", "holt", ...
        "harmonic", "ar", "kalman", "gru", ...
        "lstm", "tcn", "dlinear", "nlinear"]
    app.configurePrediction(SelectionMode="manual", Model=model, ...
        Adaptation="off", Device="cpu");
end
state = app.getReviewState();
assert(state.model_selection_mode == "manual");
assert(state.requested_model == "nlinear");
assert(state.adaptation_mode == "off");
assert(state.device == "cpu");

fprintf("%s\n", "PASS: v3.1-7 uses target-free local P8 observations, " + ...
    "full-history arbitrary-horizon prediction, per-parameter selection, " + ...
    "warning-only performance guards, and frozen imputed fields.");
