function config = default_v31_3_evidence_config()
%DEFAULT_V31_3_EVIDENCE_CONFIG Reproducible v3.1-3 evidence defaults.

step = default_step11abc_config();
config = struct( ...
    "schema_version", "v3.1-3-parameter-evidence-config.1", ...
    "study_id", "v31_3_parameter_evidence.1", ...
    "parameter_names", step.parameter_names, ...
    "parameter_bounds", step.parameter_bounds, ...
    "parameter_bundles", step.parameter_bundles, ...
    "tasks", ["interpolation", "extrapolation"], ...
    "selection_partition", "validation", ...
    "report_partition", "test", ...
    "asset_policy", "git_external_local_asset_root_only", ...
    "sensitivity", sensitivityDefaults(), ...
    "freezing", freezingDefaults());
end

function config = sensitivityDefaults()
config = struct( ...
    "seed_values", [31301, 31302, 31303], ...
    "relative_bound_perturbation", 0.10, ...
    "delay_bin_count", 64, ...
    "ctf_frequency_count", 16, ...
    "snapshot_count", 8, ...
    "profile_scenarios", [ ...
        "sub-6 GHz_UMa_LoS", "cmWave_UMa_NLoS", "mmWave_UMi_LoS"], ...
    "profile_frequencies_hz", [3.5e9, 16e9, 28e9], ...
    "profile_speeds_mps", [0.5, 3.0, 8.0], ...
    "profile_tx_counts", [1, 2, 2], ...
    "profile_rx_counts", [1, 2, 4]);
end

function config = freezingDefaults()
config = struct( ...
    "minimum_extrapolation_coverage", 0.85, ...
    "minimum_interpolation_coverage", 0.95, ...
    "minimum_p8_increment", 0.05, ...
    "sensitivity_score_floor", 1e-4, ...
    "require_full_generator_mapping", true);
end
