function report = audit_platform_compatibility(options)
%AUDIT_PLATFORM_COMPATIBILITY Inspect production compatibility decisions.
%   REPORT = AUDIT_PLATFORM_COMPATIBILITY(FullEngineRoot=ROOT) distinguishes
%   a genuine backend limit from an avoidable platform-side rejection.  It
%   does not generate a channel and never changes an external engine.

arguments
    options.FullEngineRoot (1, 1) string = ""
end

profiles = [ ...
    struct("name", "Narrowband static SISO", "requested", "auto", ...
        "dimensions", dims(1, 1, 1), "expected", "lite_6gpcm", ...
        "expected_variant", "lite_native", "kind", "production"), ...
    struct("name", "Wideband static SISO", "requested", "auto", ...
        "dimensions", dims(1, 1, 1), "expected", "lite_6gpcm", ...
        "expected_variant", "lite_native", "kind", "production"), ...
    struct("name", "Wideband static MIMO", "requested", "auto", ...
        "dimensions", dims(2, 4, 1), "expected", "full_6gpcm", ...
        "expected_variant", "public_api", "kind", "production"), ...
    struct("name", "Wideband dynamic MIMO", "requested", "auto", ...
        "dimensions", dims(2, 4, 16), "expected", "full_6gpcm", ...
        "expected_variant", "public_api", "kind", "production"), ...
    struct("name", "Manual Lite for MIMO", "requested", "lite_6gpcm", ...
        "dimensions", dims(2, 4, 1), "expected", "", ...
        "expected_variant", "", "kind", "intentional_rejection"), ...
    struct("name", "Full resource guard", "requested", "full_6gpcm", ...
        "dimensions", dims(16, 16, 64), "expected", "", ...
        "expected_variant", "", "kind", "intentional_rejection") ...
    ];

records = repmat(struct("name", "", "requested_backend", "", ...
    "dimensions", struct(), "classification", "", "status", "", ...
    "selected_backend", "", "selected_adapter_variant", "", ...
    "evidence", "", "selection", struct()), numel(profiles), 1);

for index = 1:numel(profiles)
    profile = profiles(index);
    selection = select_generator_backend(profile.requested, ...
        profile.dimensions, FullEngineRoot=options.FullEngineRoot);
    record = records(index);
    record.name = profile.name;
    record.requested_backend = profile.requested;
    record.dimensions = profile.dimensions;
    record.selected_backend = selection.selected_backend;
    record.selected_adapter_variant = selection.selected_adapter_variant;
    record.selection = selection;

    if profile.kind == "intentional_rejection"
        if ~selection.success
            record.classification = "genuine_limit";
            record.status = "PASS";
            record.evidence = strjoin(candidateReasons(selection), " | ");
        else
            record.classification = "false_acceptance";
            record.status = "FAIL";
            record.evidence = "A deliberately unsupported request selected " + ...
                selection.selected_backend + ".";
        end
    elseif selection.success && selection.selected_backend == profile.expected && ...
            selection.selected_adapter_variant == profile.expected_variant
        record.classification = "verified_compatible";
        record.status = "PASS";
        record.evidence = "Selected " + selection.selected_backend + ...
            " / " + selection.selected_adapter_variant + ".";
    elseif profile.expected == "full_6gpcm" && ...
            ~hasPublicApi(options.FullEngineRoot)
        record.classification = "environment_unavailable";
        record.status = "WARNING";
        record.evidence = "The Full public API root is unavailable; this is not a dimension rejection.";
    else
        record.classification = "possible_false_rejection";
        record.status = "FAIL";
        record.evidence = strjoin(candidateReasons(selection), " | ");
    end
    records(index) = record;
end

source = sourceAssumptions();
findings = [ ...
    finding("Auto backend selection", "PASS", "verified_compatible", ...
        "Full public API is tried before the historical fixed entry point.", ...
        "Keep the public API first and retain fixed entry only as a fallback."), ...
    finding("Manual backend choice", "PASS", "genuine_limit", ...
        "A manual Lite request for MIMO is rejected rather than silently changed.", ...
        "Keep explicit user choice and expose the candidate audit in the UI."), ...
    finding("Full resource guard", "PASS", "genuine_limit", ...
        "Configured antenna/time resource limits reject oversized jobs before generation.", ...
        "Treat a future limit increase as an engineering decision, not a format fix."), ...
    finding("Time/frequency target-axis generation", "PASS", "verified_compatible", ...
        "Time, space and frequency target generation are supported since v3.2-4a: " + ...
        "time/space via the v3.2 studied models (AR/Persistence) through the Full public " + ...
        "API, and frequency via deterministic in-band linear-interpolation recovery " + ...
        "(no engine involved).", ...
        "Keep the three-axis unified prediction entry and its leakage-free guards."), ...
    finding("Legacy fixed Full interface", "PASS", "controlled_legacy", ...
        "Fixed-interface references found: " + string(source.fixed_entrypoint_references) + ".", ...
        "Use only as an exact 2x2xNt=2 fallback; never use it as a general compatibility test.") ...
    ];

statuses = string({records.status});
summaryTable = table( ...
    string({records.name}).', string({records.status}).', ...
    string({records.classification}).', string({records.selected_backend}).', ...
    string({records.selected_adapter_variant}).', string({records.evidence}).', ...
    'VariableNames', ["Profile", "Status", "Classification", ...
    "SelectedBackend", "AdapterVariant", "Evidence"]);
report = struct( ...
    "schema_version", "v3.0-step12extra-compatibility-audit.1", ...
    "generated_at", string(datetime("now", "Format", "yyyy-MM-dd HH:mm:ss")), ...
    "full_engine_root", options.FullEngineRoot, ...
    "records", records, ...
    "summary_table", summaryTable, ...
    "findings", findings, ...
    "source_assumptions", source, ...
    "summary", struct( ...
        "pass_count", sum(statuses == "PASS"), ...
        "warning_count", sum(statuses == "WARNING"), ...
        "fail_count", sum(statuses == "FAIL"), ...
        "safe_to_run_formal_sample_position_flow", ...
            ~any(statuses == "FAIL"), ...
        "time_frequency_target_generation_supported", true));
end

function value = dims(tx, rx, nt)
value = struct("Tx", tx, "Rx", rx, "Nt", nt, "N_sample", 20);
end

function values = candidateReasons(selection)
values = strings(0, 1);
for index = 1:numel(selection.candidates)
    candidate = selection.candidates(index);
    values(end + 1, 1) = candidate.backend + " / " + ...
        candidate.adapter_variant + ": " + candidate.reason; %#ok<AGROW>
end
end

function tf = hasPublicApi(root)
required = [ ...
    "@simulation_parameters/simulation_parameters.m", ...
    "@antenna_array/antenna_array.m", ...
    "@track/track.m", ...
    "@channel_model/channel_model.m", ...
    "+mf/result2H.m"];
tf = strlength(strtrim(root)) > 0 && isfolder(root);
for relativePath = required
    tf = tf && isfile(fullfile(root, replace(relativePath, "/", filesep)));
end
end

function value = sourceAssumptions()
root = fileparts(fileparts(mfilename("fullpath")));
files = [ ...
    fullfile(root, "generation", "select_generator_backend.m"), ...
    fullfile(root, "generation", "probe_generator_backend.m"), ...
    fullfile(root, "generation", "validate_generator_config.m"), ...
    fullfile(root, "generation", "run_full_6gpcm_adapter.m"), ...
    fullfile(root, "generation", "run_full_6gpcm_public_api_adapter.m") ...
    ];
combined = "";
for file = files
    if isfile(file)
        combined = combined + string(fileread(file));
    end
end
value = struct( ...
    "scanned_files", files, ...
    "fixed_entrypoint_references", count(combined, "fixed_entrypoint"), ...
    "public_api_references", count(combined, "public_api"), ...
    "hardcoded_lite_siso_references", count(combined, "Tx=1") + ...
        count(combined, "Rx=1"));
end

function value = finding(area, status, classification, evidence, recommendation)
value = struct("area", string(area), "status", string(status), ...
    "classification", string(classification), "evidence", string(evidence), ...
    "recommendation", string(recommendation));
end
