function config = default_generator_config(backend)
%DEFAULT_GENERATOR_CONFIG Return a versioned Step 6 generator request.
%   CONFIG = DEFAULT_GENERATOR_CONFIG(BACKEND) creates a complete request
%   for "mock", "lite_6gpcm", or "full_6gpcm".  The dimensions follow the
%   v3 contract and keep Nt separate from N_sample.

arguments
    backend (1, 1) string = "mock"
end

backend = canonicalBackend(backend);
config = struct( ...
    "schema_version", "v3.0-generator-config.1", ...
    "backend", backend, ...
    "mode", "preview", ...
    "random_seed", 3103, ...
    "dimensions", struct( ...
        "Tx", 2, "Rx", 2, "Npath", 12, "Nt", 4, "N_sample", 6), ...
    "scenario", struct( ...
        "id", "deterministic_mock", ...
        "center_frequency_hz", 16e9, ...
        "bandwidth_hz", 100e6, ...
        "track_type", "linear", ...
        "snapshot_interval_s", 1e-3), ...
    "model", struct( ...
        "DS_mu", -7.925, ...
        "DS_sigma", 0.060, ...
        "r_DS", 2.8, ...
        "num_clusters", 12, ...
        "num_rays", 20, ...
        "LNS_ksi", 3.0, ...
        "KF_mu", -0.39, ...
        "KF_sigma", 2.4, ...
        "doppler_hz", 50), ...
    "ctf", struct( ...
        "enabled", false, ...
        "frequency_hz", zeros(0, 1)), ...
    "backend_options", struct( ...
        "lite_delay_max_ns", 300, ...
        "output_profile", "native", ...
        "full_interface", "fixed_entrypoint", ...
        "full_track_speed_mps", 1.0, ...
        "full_max_antenna_pairs", 64, ...
        "full_max_nt", 256, ...
        "full_max_tensor_slices", 4096), ...
    "engine_root", "", ...
    "engine", struct( ...
        "id", "chanai_mock_generator", ...
        "version", "v3.0-step6.1", ...
        "source_package_name", "project_owned_test_double", ...
        "source_package_sha256", "", ...
        "expected_tree_sha256", "", ...
        "test_only", true));

switch backend
    case "mock"
        % Common defaults already describe the deterministic test adapter.
    case "lite_6gpcm"
        config.dimensions = struct( ...
            "Tx", 1, "Rx", 1, "Npath", 0, "Nt", 8, "N_sample", 4);
        config.scenario.id = "lite_clustered_siso";
        config.scenario.track_type = "time_sequence";
        config.engine = struct( ...
            "id", "6GPCM-lite", ...
            "version", "repository", ...
            "source_package_name", "ChanAI Pulse internal generator", ...
            "source_package_sha256", "", ...
            "expected_tree_sha256", "", ...
            "test_only", false);
    case "full_6gpcm"
        config.dimensions = struct( ...
            "Tx", 2, "Rx", 2, "Npath", 0, "Nt", 2, "N_sample", 3);
        config.scenario.id = "cmWave_Indoor_LoS";
        config.scenario.track_type = "static";
        config.scenario.snapshot_interval_s = 1.0;
        config.engine_root = string(getenv("CHANAI_FULL_6GPCM_ROOT"));
        config.engine = struct( ...
            "id", "full_6gpcm_external", ...
            "version", "260317-candidate", ...
            "source_package_name", ...
                "信道生成模块代码_260317.zip", ...
            "source_package_sha256", ...
                "fcf151adf94038a6cf10d86c6dd687938b085a8f78a64d6829b5439c1d6c5875", ...
            "expected_tree_sha256", ...
                "e5e4ec49ef25090e2d472283914187967e801b38722e10a28694efa77bfccac0", ...
            "test_only", false);
end
end

function backend = canonicalBackend(value)
backend = lower(strtrim(string(value)));
switch backend
    case {"mock", "test", "test_double"}
        backend = "mock";
    case {"lite", "6gpcm-lite", "lite_6gpcm"}
        backend = "lite_6gpcm";
    case {"full", "6gpcm", "full_6gpcm", "full_6gpcm_external"}
        backend = "full_6gpcm";
    otherwise
        error("default_generator_config:UnsupportedBackend", ...
            "Unsupported generator backend: %s", value);
end
end
