function payload = run_mock_generator_adapter(config, hooks)
%RUN_MOCK_GENERATOR_ADAPTER Deterministic project-owned test adapter.
%   This adapter exists for tests and interface demonstrations only.

arguments
    config (1, 1) struct
    hooks (1, 1) struct
end

dims = config.dimensions;
shape = [dims.Tx, dims.Rx, dims.Npath, dims.Nt, dims.N_sample];
coefficient = complex(zeros(shape));
delayS = zeros(shape);
aoaRad = zeros(shape);
aodRad = zeros(shape);
dopplerHz = zeros(shape);

originalState = rng;
cleanup = onCleanup(@() rng(originalState));
rng(double(config.random_seed), "twister");
defaultModel = default_generator_config("mock").model;
delayScale = 10 ^ (config.model.DS_mu - defaultModel.DS_mu);
baseDelay = reshape(sort(rand(1, dims.Npath)) * 280e-9 * ...
    delayScale, ...
    [1, 1, dims.Npath, 1]);
decayConstant = 70e-9 * ...
    max(0.1, config.model.r_DS / defaultModel.r_DS);
basePower = exp(-baseDelay / decayConstant);
pathCoordinate = reshape(linspace(0, 1, dims.Npath), ...
    [1, 1, dims.Npath, 1]);
clusterResponse = exp(0.025 * ...
    (config.model.num_clusters - defaultModel.num_clusters) .* ...
    cos(2 * pi * pathCoordinate));
rayResponse = exp(0.010 * ...
    (config.model.num_rays - defaultModel.num_rays) .* ...
    sin(2 * pi * pathCoordinate));
shadowResponse = exp(0.04 * ...
    (config.model.LNS_ksi - defaultModel.LNS_ksi) .* ...
    (pathCoordinate - 0.5));
basePower = basePower .* clusterResponse .* ...
    rayResponse .* shadowResponse;
kFactorLinear = 10 ^ (config.model.KF_mu / 10);
basePower(:, :, 1, :) = basePower(:, :, 1, :) * ...
    (1 + kFactorLinear);
baseAoa = reshape(linspace(-0.8, 0.8, dims.Npath), ...
    [1, 1, dims.Npath, 1]);
baseAod = reshape(linspace(0.7, -0.7, dims.Npath), ...
    [1, 1, dims.Npath, 1]);
baseDoppler = reshape(linspace(-config.model.doppler_hz, ...
    config.model.doppler_hz, dims.Npath), [1, 1, dims.Npath, 1]);
basePhase = reshape(2 * pi * rand(dims.Tx, dims.Rx, dims.Npath), ...
    [dims.Tx, dims.Rx, dims.Npath, 1]);
pathDelay = repmat(baseDelay, [dims.Tx, dims.Rx, 1, 1]);
pathAoa = repmat(baseAoa, [dims.Tx, dims.Rx, 1, 1]);
pathAod = repmat(baseAod, [dims.Tx, dims.Rx, 1, 1]);
pathDoppler = repmat(baseDoppler, [dims.Tx, dims.Rx, 1, 1]);

for sample = 1:dims.N_sample
    if hooks.is_cancelled()
        error("run_mock_generator_adapter:Cancelled", ...
            "Mock generation was cancelled before sample %d.", sample);
    end
    sigmaRatio = config.model.DS_sigma / ...
        max(defaultModel.DS_sigma, eps);
    sampleOffset = (sample - 1) * 0.35e-9 * sigmaRatio;
    for time = 1:dims.Nt
        timeS = (time - 1) * config.scenario.snapshot_interval_s;
        phase = basePhase + 2 * pi .* baseDoppler .* timeS + ...
            0.04 * (sample - 1);
        sampleModulation = reshape( ...
            1 + 0.02 * cos(sample + (1:dims.Npath)), ...
            [1, 1, dims.Npath, 1]);
        kSigmaDb = config.model.KF_sigma * ...
            sin(0.7 * sample + 0.3 * time);
        sampleModulation(:, :, 1, :) = ...
            sampleModulation(:, :, 1, :) * 10 ^ (kSigmaDb / 20);
        amplitude = sqrt(basePower) .* sampleModulation;
        coefficient(:, :, :, time, sample) = amplitude .* exp(1i * phase);
        delayS(:, :, :, time, sample) = pathDelay + sampleOffset;
        aoaRad(:, :, :, time, sample) = pathAoa;
        aodRad(:, :, :, time, sample) = pathAod;
        dopplerHz(:, :, :, time, sample) = pathDoppler;
    end
    hooks.emit("generate", 0.10 + 0.75 * sample / dims.N_sample, ...
        "Mock sample " + sample + " of " + dims.N_sample);
end

axes = struct( ...
    "sample_index", (1:dims.N_sample).', ...
    "time_s", (0:dims.Nt - 1).' * ...
        config.scenario.snapshot_interval_s);
if dims.N_sample > 1
    axes.sample_position_m = [(0:dims.N_sample - 1).', ...
        zeros(dims.N_sample, 2)];
    sampleSemantics = "ordered_route";
else
    sampleSemantics = "independent";
end

metadata = struct( ...
    "source", "step6_mock_generator", ...
    "sample_semantics", sampleSemantics, ...
    "generator", string(config.engine.id), ...
    "generator_version", string(config.engine.version), ...
    "random_seed", double(config.random_seed), ...
    "center_frequency_hz", ...
        double(config.scenario.center_frequency_hz), ...
    "snapshot_interval_s", ...
        double(config.scenario.snapshot_interval_s), ...
    "scenario_id", string(config.scenario.id), ...
    "tx_array_positions_m", ulaPositions(dims.Tx, ...
        config.scenario.center_frequency_hz), ...
    "rx_array_positions_m", ulaPositions(dims.Rx, ...
        config.scenario.center_frequency_hz), ...
    "config", sanitize_generator_config(config));
cirPayload = struct( ...
    "coefficient", coefficient, ...
    "delay_s", delayS, ...
    "path_valid", true(shape), ...
    "aoa_rad", aoaRad, ...
    "aod_rad", aodRad, ...
    "doppler_hz", dopplerHz);
dataset = create_channel_dataset("cir", cirPayload, axes, metadata);

payload = struct( ...
    "dataset", dataset, ...
    "warnings", ...
        "Mock output is deterministic test data and must not be presented as physical 6GPCM.", ...
    "backend_manifest", struct( ...
        "adapter", "MockGeneratorAdapter", ...
        "adapter_version", "v3.0-step6.1", ...
        "test_only", true));
clear cleanup
end

function positions = ulaPositions(count, centerFrequencyHz)
wavelength = 299792458 / centerFrequencyHz;
positions = zeros(count, 3);
positions(:, 1) = (0:count - 1).' * wavelength / 2;
end
