function payload = run_lite_6gpcm_adapter(config, hooks)
%RUN_LITE_6GPCM_ADAPTER Wrap the internal engineering generator as v3 CIR.

arguments
    config (1, 1) struct
    hooks (1, 1) struct
end

dims = config.dimensions;
legacyConfig = default_6gpcm_lite_config();
legacyConfig.bandwidth_hz = config.scenario.bandwidth_hz;
legacyConfig.delay_grid_step_ns = ...
    1e9 / config.scenario.bandwidth_hz;
legacyConfig.delay_max_ns = config.backend_options.lite_delay_max_ns;
legacyConfig.ds_mu = config.model.DS_mu;
legacyConfig.ds_sigma = config.model.DS_sigma;
legacyConfig.r_ds = config.model.r_DS;
legacyConfig.clusters = config.model.num_clusters;
legacyConfig.rays = config.model.num_rays;
legacyConfig.lns_ksi_db = config.model.LNS_ksi;
legacyConfig.kf_mu_db = config.model.KF_mu;
legacyConfig.kf_sigma_db = config.model.KF_sigma;
legacyConfig.snapshots = dims.Nt;
legacyConfig.doppler_hz = config.model.doppler_hz;
legacyConfig.sample_interval_s = config.scenario.snapshot_interval_s;

originalState = rng;
cleanup = onCleanup(@() rng(originalState));
pathCount = round(legacyConfig.delay_max_ns / ...
    legacyConfig.delay_grid_step_ns) + 1;
coefficient = complex(zeros(1, 1, pathCount, ...
    dims.Nt, dims.N_sample));
delayS = zeros(1, 1, pathCount, dims.Nt, dims.N_sample);
delaySpreadNs = zeros(dims.Nt, dims.N_sample);
for sample = 1:dims.N_sample
    if hooks.is_cancelled()
        error("run_lite_6gpcm_adapter:Cancelled", ...
            "6GPCM-lite generation was cancelled before sample %d.", sample);
    end
    legacyConfig.random_seed = double(config.random_seed) + sample - 1;
    legacy = generate_6gpcm_lite(legacyConfig);
    sampleCoefficient = permute(legacy.cir, [1, 2, 4, 3]);
    sampleDelay = permute(legacy.delay, [1, 2, 4, 3]);
    if size(sampleCoefficient, 3) ~= pathCount
        error("run_lite_6gpcm_adapter:UnexpectedPathCount", ...
            "6GPCM-lite returned %d paths; expected %d from the delay grid.", ...
            size(sampleCoefficient, 3), pathCount);
    end
    coefficient(:, :, :, :, sample) = sampleCoefficient;
    delayS(:, :, :, :, sample) = sampleDelay;
    delaySpreadNs(:, sample) = legacy.delay_spread_ns(:);
    hooks.emit("generate", 0.10 + 0.75 * sample / dims.N_sample, ...
        "6GPCM-lite sample " + sample + " of " + dims.N_sample);
end

axes = struct( ...
    "sample_index", (1:dims.N_sample).', ...
    "time_s", (0:dims.Nt - 1).' * ...
        config.scenario.snapshot_interval_s);
metadata = struct( ...
    "source", "lite_6gpcm_adapter", ...
    "sample_semantics", "independent", ...
    "generator", "6GPCM-lite", ...
    "generator_version", string(config.engine.version), ...
    "random_seed", double(config.random_seed), ...
    "center_frequency_hz", ...
        double(config.scenario.center_frequency_hz), ...
    "snapshot_interval_s", ...
        double(config.scenario.snapshot_interval_s), ...
    "scenario_id", string(config.scenario.id), ...
    "seed_rule", "base_seed_plus_sample_index_minus_one", ...
    "config", sanitize_generator_config(config));
cirPayload = struct( ...
    "coefficient", coefficient, ...
    "delay_s", delayS, ...
    "path_valid", true(size(coefficient)));
dataset = create_channel_dataset("cir", cirPayload, axes, metadata);

payload = struct( ...
    "dataset", dataset, ...
    "warnings", [ ...
        "6GPCM-lite is an internal engineering generator, not the external full 6GPCM."; ...
        "Lite time snapshots redraw cluster statistics and should not be treated as a scientifically validated continuous trajectory."], ...
    "backend_manifest", struct( ...
        "adapter", "Lite6GPCMAdapter", ...
        "adapter_version", "v3.0-step6.1", ...
        "test_only", false, ...
        "legacy_delay_grid_step_ns", legacyConfig.delay_grid_step_ns, ...
        "delay_spread_ns", delaySpreadNs));
clear cleanup
end
