function output = translate_channel_simulator_text(input, language)
%TRANSLATE_CHANNEL_SIMULATOR_TEXT Translate presentation text only.
%   Scientific identifiers (Tx/Rx/Nt, DS_mu, KF_mu, CIR, CTF and manifest
%   field names) intentionally remain stable across languages.

arguments
    input
    language (1, 1) string
end

language = lower(strtrim(language));
output = string(input);
if language == "zh"
    [from, to] = phrasePairs("en_to_zh");
elseif language == "en"
    [from, to] = phrasePairs("zh_to_en");
else
    error("translate_channel_simulator_text:UnsupportedLanguage", ...
        "Supported languages are zh and en.");
end
[extraFrom, extraTo] = additionalPhrasePairs(language);
from = [from; extraFrom];
to = [to; extraTo];

% Long phrases first prevents a short token from spoiling an exact label.
[~, order] = sort(strlength(from), "descend");
for index = order(:).'
    output = replace(output, from(index), to(index));
end
% The automatic-start label is the only dynamic sentence that joins a
% Chinese full-width closing parenthesis to a translated English prefix.
% Keep this targeted so generic ')' replacement cannot corrupt model IDs,
% warning details, or scientific notation elsewhere in the UI.
if language == "en"
    mask = startsWith(output, "Start prediction (automatic: ");
    output(mask) = replace(output(mask), "）", ")");
elseif language == "zh"
    mask = startsWith(output, "开始预测（自动：");
    output(mask) = replace(output(mask), ")", "）");
end

function [from, to] = additionalPhrasePairs(language)
% Complete sentences are deliberately listed here.  They are the dynamic
% run summaries written after construction and cannot be translated merely
% by changing the static labels created with the UI components.
zh = [ ...
    "普通用户无需在本页逐项操作。"; ...
    "从模块一启动后自动运行"; ...
    "模块二使用已知区域的信道特性作为参考。"; ...
    "普通模式自动选择 Grid Search 或 SA，并把实际选择与理由写入 Manifest。"; ...
    "这里的标定对照只解释生成器配置，不是模块三预测准确度。"; ...
    "阶段：准备数据"; "阶段：提取参考特性"; "阶段：参数标定与生成"; "阶段：交给模块三预测"; ...
    "参数标定运行中"; "实际策略: "; "选择来源: "; "理由: "; "状态: "; ...
    "当前候选数 "; " 超过当前后端自动上限 "; "，因此自动选择 SA。"; "当前自动选择 SA。"; ...
    "数据状态: "; "域: "; "分类: "; "可用图: "; "标准图"; "附加图"; ...
    "标准特性图 "; " 张，附加可视化 "; " 张"; ...
    "阅读提示"; "• 顶部图表数字采用“标准图+附加图”。"; ...
    "• 全部概览说明每张图是否可用。"; "• 热力图单独放在附加可视化。"; ...
    "• 不支持的图不会生成伪造曲线。"; ...
    "任务区间：加载后显示已知区与目标区"; ...
    "原始轴已知区："; "原始轴目标区："; "内部 MATLAB 已知索引："; ...
    "原始轴已知区: "; "原始轴目标区: "; "内部 MATLAB 已知索引: "; ...
    "：已知 "; "，目标 "; " 个值"; ...
    "sample（绿色：已知，橙色：目标，灰色：未使用）"; ...
    "数据、任务和可视化能力均通过。"; "生成器预检："; ...
    "PASS：数据、任务和可视化能力均通过。"; "生成器预检：PASS，已选择 "; ...
    " 标准 + "; " 附加"; ...
    "当前全部正式候选均不适用。"; "不兼容："; ...
    "预测或生成失败。不会发布部分 CIR。"; ...
    "模型选择不读取本次目标区域 Ground Truth。"; ...
    "ModelRegistry v2 的冻结推荐将如实显示。"; ...
    "普通模式按上传已知区逐参数回测自动选择。"; ...
    "支持全历史任意长度外推和双向内插。"; ...
    "Registry 冻结推荐作为历史参考如实显示。"; ...
    "模型选择不读取目标区真值。"; ...
    "神经模型属于 legacy 16→4 实验候选，长目标采用滚动兼容。"; ...
    "性能异常会警告；只有硬性技术错误才拒绝。"; ...
    "ModelRegistry v2 自动推荐。"; ...
    "外推：P8 + Kalman"; "内插：P8 + Persistence"; ...
    "神经模型仅供高级用户研究；模型选择不读取目标区真值。"; ...
    "不兼容或运行环境不可用时会明确记录安全回退。"; ...
    "高级用户手动选择："; "该模型可能不是系统推荐，结果会写入 Manifest。"; ...
    "GRU/LSTM/TCN/DLinear/NLinear 属于实验候选。"; ...
    "目标区域 Ground Truth 不参与选择或适配。"; ...
    "Registry 冻结推荐："; "选择依据："; "适配结果："; ...
    "模型："; "模型来源："; "适配："; "设备："; ...
    "GPU 不可用，已明确回退"; ...
    "手动模型性能较差时警告但仍运行；硬性不兼容才拒绝。Full 失败不会静默改用 Lite。"; ...
    "等待本次模型回测与技术检查"; ...
    "逐参数模型："; "本地最佳基线："; "警告："; ...
    "预测 CIR 已生成，但请查看模型警告"; ...
    "说明：本页展示已知区回测，不把目标真值当作已知精度。"; ...
    "已知历史不足以执行本地留出回测；任务仍使用最安全的可用灵活模型运行。"; ...
    "手动模型 "; " 在上传数据已知区回测中弱于本地基线 "; "；系统仍按要求运行。"; ...
    "手选模型至少一个参数超过极端本地退化比。系统仍运行该模型，并透明地与该参数的最佳已知区基线融合，避免明显不合理的轨迹；权重已写入 Manifest。"; ...
    "预测变化超过已知区连续性参考；这是警告，不是拒绝。"; ...
    "至少一个旧神经模型的四点输出头使用了滚动兼容；长预测的不确定性可能累积。"; ...
    " 个预测参数值已投影到生成器合法范围/整数计数合同。"; ...
    "正式预测已完成：Persistence（冻结注册表自动选择）"; ...
    "参数包："; "参数来源："; "目标区域 Ground Truth：未读取"; ...
    "输出：预测 CIR，可选 CTF、特性图和可审计 Manifest"; ...
    "本页不显示准确度；准确度应由软件外部 Benchmark 验证。"; ...
    "本页不显示准确度；准确度由软件外部 Benchmark 验证。"; ...
    "可导出："; "注："; "多普勒扩展经验 CDF"; ...
    "时延—样本功率热力图"; "当前数据不支持这一组图表；请查看右侧能力说明。"; ...
    "当前数据没有可登记的特性图。"; "已通过数据维度与元数据检查"; ...
    "系统自动选择"; "高级用户手动指定"; "已知区 Grid/SA 标定"; "known 区 Grid/SA 标定"; ...
    "Full 6GPCM："; "当前 Full 固定入口为"; "优化 Manifest"; ...
    "模块二："; "模块三："; ...
    "当前没有可导出的 PredictionResult。"; "尚无预测结果"; ...
    "选择预测结果导出目录"; "导出完成：" ...
    ];
en = [ ...
    "Standard users do not need to operate this page item by item."; ...
    "Starts automatically after Module 1"; ...
    "Module 2 uses known-region channel characteristics as its reference."; ...
    "Standard mode automatically chooses Grid Search or SA and records the selected method and rationale in the Manifest."; ...
    "The calibration comparison here explains generator configuration, not Module 3 prediction accuracy."; ...
    "Stage: preparing data"; "Stage: extracting reference characteristics"; "Stage: parameter calibration and generation"; "Stage: handing off to Module 3 prediction"; ...
    "Parameter calibration in progress"; "Actual strategy: "; "Selection source: "; "Reason: "; "Status: "; ...
    "Candidate count "; " exceeds the current backend auto limit "; ", so SA was selected automatically."; "SA was selected automatically."; ...
    "Data status: "; "Domain: "; "Classification: "; "Available plots: "; "standard"; "additional"; ...
    "Standard characteristic plots: "; ", additional visualizations: "; " plots"; ...
    "Reading tips"; "• The plot count is shown as ‘standard + additional’."; ...
    "• Overview states whether each plot is available."; "• Heatmaps appear under Additional visualization."; ...
    "• Unsupported plots never produce fabricated curves."; ...
    "Task range: known and target regions appear after loading"; ...
    "Known region in original axis: "; "Target region in original axis: "; "Internal MATLAB known indices: "; ...
    "Known region in original axis: "; "Target region in original axis: "; "Internal MATLAB known indices: "; ...
    ": known "; ", target "; " values"; ...
    "sample (green: known, orange: target, gray: unused)"; ...
    "Data, task, and visualization capabilities have passed."; "Generator preflight: "; ...
    "PASS: Data, task, and visualization capabilities have passed."; "Generator preflight: PASS, selected "; ...
    " standard + "; " additional"; ...
    "All formal generator candidates are currently inapplicable."; "Incompatible: "; ...
    "Prediction or generation failed. No partial CIR will be published."; ...
    "Model selection does not read Ground Truth from this target region."; ...
    "The frozen ModelRegistry v2 recommendation is displayed exactly."; ...
    "Standard mode automatically selects per parameter using uploaded known-region backtests."; ...
    "Full-history arbitrary-horizon extrapolation and bidirectional interpolation are supported."; ...
    "Frozen Registry recommendations remain visible as historical references."; ...
    "Model selection does not read target-region truth."; ...
    "Neural models are legacy 16-to-4 experimental candidates; long targets use rolling compatibility."; ...
    "Performance anomalies produce warnings; only hard technical errors are rejected."; ...
    "ModelRegistry v2 automatic recommendation."; ...
    "Extrapolation: P8 + Kalman"; "Interpolation: P8 + Persistence"; ...
    "Neural models are advanced research candidates; model selection does not read target truth."; ...
    "An incompatible task or unavailable runtime produces an explicit safe-fallback record."; ...
    "Advanced manual selection: "; "This model may not be system-recommended; the decision is recorded in the Manifest."; ...
    "GRU/LSTM/TCN/DLinear/NLinear are experimental candidates."; ...
    "Target-region Ground Truth is not used for selection or adaptation."; ...
    "Frozen Registry recommendation: "; "Selection basis: "; "Adaptation result: "; ...
    "Model: "; "Model source: "; "Adaptation: "; "Device: "; ...
    "GPU unavailable; explicit fallback applied"; ...
    "A poorly performing manual model still runs with a warning; only hard incompatibility is rejected. Full failure never silently switches to Lite."; ...
    "Waiting for known-region backtest and technical checks"; ...
    "Per-parameter models: "; "Best local baseline: "; "Warning: "; ...
    "Predicted CIR generated; review model warnings"; ...
    "Note: this page shows known-region backtests and does not claim target truth as known accuracy."; ...
    "Known history is too short for a local holdout backtest; the task still runs with the safest available flexible model."; ...
    "Manual "; " is worse than local baseline "; " on the uploaded known-region backtest; it was run as requested."; ...
    "The requested model exceeded the extreme local-regret ratio on at least one parameter. It still ran, and its output was transparently blended with that parameter's best known-region baseline to prevent an obviously implausible trajectory; weights are recorded in the Manifest."; ...
    "Prediction changes exceed the known-region continuity reference; this is a warning, not a rejection."; ...
    "At least one legacy neural four-point output head used rolling compatibility; long-horizon uncertainty may accumulate."; ...
    " predicted parameter values were projected into the generator's valid bounds/integer-count contract."; ...
    "Formal prediction complete: Persistence (frozen registry automatic selection)"; ...
    "Parameter bundle: "; "Parameter source: "; "Target-region Ground Truth: not read"; ...
    "Output: predicted CIR, optional CTF, characteristic plots, and auditable Manifest"; ...
    "This page does not show accuracy; verify accuracy with an external Benchmark."; ...
    "This page does not show accuracy; verify accuracy with an external Benchmark."; ...
    "Exportable: "; "Note: "; "Doppler-spread empirical CDF"; ...
    "Delay–sample power heatmap"; "This data does not support this plot group; see the capability panel on the right."; ...
    "No registered characteristic plots are available for this data."; "Passed data-dimension and metadata checks"; ...
    "Automatically selected by the system"; "Manually selected by an advanced user"; "Known-region Grid/SA calibration"; "Known-region Grid/SA calibration"; ...
    "Full 6GPCM: "; "The current Full fixed entry point is"; "Optimization Manifest"; ...
    "Module 2: "; "Module 3: "; ...
    "No PredictionResult is available for export."; "No prediction result yet"; ...
    "Choose a prediction-result export directory"; "Export complete: " ...
    ];
if language == "en"
    from = zh;
    to = en;
else
    from = en;
    to = zh;
end
end
end

function [from, to] = phrasePairs(direction)
zh = [ ...
    "数据与任务"; "运行详情"; "预测结果"; "使用模式"; "普通模式"; "高级模式"; ...
    "数据导入与任务设置"; "输入信道特性（能力驱动）"; "数据质量与能力"; ...
    "浏览信道文件…"; "MAT 数据转换向导…"; "尚未选择文件"; "任务类型"; "样本"; "位置"; "时间"; "频率"; ...
    "外推：已知 → 未来"; "内插：两侧 → 中间"; "自动 80/20"; "精确手动区间"; ...
    "手动区间的输入依据"; "原始样本编号（推荐）"; "原始位置坐标（推荐）"; ...
    "原始时间坐标（推荐）"; "原始频率坐标（推荐）"; "MATLAB 数组位置（高级）"; ...
    "已知区（例：0:30,40:60）"; "目标区（例：31:39）"; ...
    "加载、验证并分析"; "开始预测"; "执行预测并生成 CIR"; ...
    "全部概览"; "时延 / 频率"; "空间 / 角度"; "时间 / 多普勒"; "附加可视化"; ...
    "后台标定状态"; "运行进度与标定说明"; "高级设置"; "生成后端"; "优化方法"; ...
    "自动选择（推荐）"; "Lite 预览"; "Full 6GPCM 正式"; "Grid Search"; "模拟退火 SA"; ...
    "取消当前运行"; "收起进度面板"; "运行进度"; "等待运行"; "运行完成"; "运行未完成"; ...
    "预测任务与模型"; "模型选择"; "自动推荐"; "高级用户手动选择"; "手动模型"; ...
    "上传数据适配"; "自动（推荐）"; "直接推理"; "尝试专家适配"; ...
    "自动安全适配（推荐）"; "关闭适配 / 直接推理"; "预测设备"; "CPU"; "GPU（CUDA）"; ...
    "二次趋势"; "Holt 阻尼趋势"; "谐波 / 傅里叶"; "自适应 AR"; ...
    "GRU（实验）"; "LSTM（实验）"; "TCN（实验）"; "DLinear（实验）"; "NLinear（实验）"; ...
    "导出 CIR / CTF / Manifest"; "预测 CIR 特性（不显示准确度）"; ...
    "预测参数轨迹（蓝色：已知区局部 P8 观测；橙色：目标区预测）"; "状态与导出"; ...
    "数据类型"; "图表"; "参数"; "标定值"; "来源"; ...
    "基础"; "空间与角度"; "时间与多普勒"; "附加"; ...
    "窄带静态 SISO"; "宽带静态 SISO"; "宽带静态 MIMO"; "宽带动态 MIMO"; ...
    "内插"; "外推"; "可用"; "不可用"; "标准特性图"; ...
    "当前阶段："; "目标进度："; "生成后端："; "已用时间："; ...
    "最终状态：成功"; "最终状态：未完成"; ...
    "正在分析输入信道"; "正在读取文件、验证数据合同并判断可视化能力。"; ...
    "输入验证"; "正在加载 HDF5 信道数据。"; "输入分析完成"; ...
    "数据、任务和图表能力已经验证。"; "输入数据已就绪。点击“开始预测”可继续完整流程。"; ...
    "正在准备预测任务"; "模块二将只使用已知区域进行标定。目标区域真值不会被读取。"; ...
    "模块二：准备数据"; "正在提取已知区域的参考特性。"; "模块二：选择生成器"; ...
    "已选择 "; "模块二：标定完成"; "正在交给模块三预测并生成目标 CIR。"; ...
    "正在生成预测 CIR"; "模块三会将预测参数交给兼容的正式生成器。"; ...
    "模块三：构造预测请求"; "使用 "; "模块三：生成目标 CIR"; ...
    "预测 CIR、可选 CTF 和特性图均已生成。"; ...
    "请保持软件窗口打开；Full 6GPCM 的单个目标可能需要数十秒。"; ...
    "可点击“收起进度面板”继续查看结果。"; ...
    "请根据上方信息修正任务后重新运行。"; ...
    "任务轴"; "已知区局部 P8 观测"; "目标区预测"; "不在当前参数包中"; ...
    "类别："; "说明："; "状态："; "后端："; "生成目标数："; ...
    "模块一"; "模块二"; "模块三"; "标定完成"; "标定失败"; "正在运行"; ...
    "输入验证失败"; "预测未完成"; "预测 CIR 已生成，可查看特性图或导出"; ...
    "MAT 转换完成，正在自动加载"; "转换结果文件不存在，无法自动加载。"; "MAT 转换失败"; ...
    "当前无兼容生成器"; "开始预测（自动："; ...
    "功率"; "频率自相关"; "时延扩展 CDF"; "角度功率谱"; "空间相关"; ...
    "角度扩展 CDF"; "多普勒功率谱"; "时间自相关"; "多普勒扩展 CDF"; "时延—样本热力图"; ...
    "空间"; "缺失子载波模式（仅频率轴）"; "均匀隔1挖1（缺50%）"; "随机50%"; "成块8"; ...
    "space（绿色：已知，橙色：目标，灰色：未使用）" ...
    ];
en = [ ...
    "Data & Task"; "Run Details"; "Prediction Result"; "Mode"; "Standard mode"; "Advanced mode"; ...
    "Data Import & Task Setup"; "Input Channel Characteristics (capability-driven)"; "Data Quality & Capabilities"; ...
    "Browse channel file…"; "MAT conversion wizard…"; "No file selected"; "Task type"; "Sample"; "Position"; "Time"; "Frequency"; ...
    "Extrapolation: known → future"; "Interpolation: sides → middle"; "Automatic 80/20"; "Exact manual ranges"; ...
    "Manual-range coordinate basis"; "Original sample ID (recommended)"; "Original position coordinate (recommended)"; ...
    "Original time coordinate (recommended)"; "Original frequency coordinate (recommended)"; "MATLAB array index (advanced)"; ...
    "Known region (e.g., 0:30,40:60)"; "Target region (e.g., 31:39)"; ...
    "Load, validate & analyze"; "Start prediction"; "Run prediction & generate CIR"; ...
    "Overview"; "Delay / Frequency"; "Space / Angle"; "Time / Doppler"; "Additional visualization"; ...
    "Calibration status"; "Run progress & calibration notes"; "Advanced settings"; "Generator backend"; "Optimization method"; ...
    "Automatic (recommended)"; "Lite preview"; "Full 6GPCM formal"; "Grid Search"; "Simulated annealing (SA)"; ...
    "Cancel current run"; "Hide progress panel"; "Run progress"; "Waiting to run"; "Run complete"; "Run incomplete"; ...
    "Prediction task & model"; "Model selection"; "Automatic recommendation"; "Advanced manual selection"; "Manual model"; ...
    "Uploaded-data adaptation"; "Automatic (recommended)"; "Direct inference"; "Try expert adaptation"; ...
    "Automatic safe adaptation (recommended)"; "Disable adaptation / direct inference"; "Prediction device"; "CPU"; "GPU (CUDA)"; ...
    "Quadratic Trend"; "Holt Damped Trend"; "Harmonic / Fourier"; "Adaptive AR"; ...
    "GRU (experimental)"; "LSTM (experimental)"; "TCN (experimental)"; "DLinear (experimental)"; "NLinear (experimental)"; ...
    "Export CIR / CTF / Manifest"; "Predicted CIR characteristics (accuracy hidden)"; ...
    "Predicted parameter trajectories (blue: local known-region P8 observations; orange: target prediction)"; "Status & export"; ...
    "Data type"; "Plots"; "Parameter"; "Calibrated value"; "Source"; ...
    "Core"; "Space & angle"; "Time & Doppler"; "Additional"; ...
    "Narrowband static SISO"; "Wideband static SISO"; "Wideband static MIMO"; "Wideband dynamic MIMO"; ...
    "Interpolation"; "Extrapolation"; "Available"; "Unavailable"; "Standard characteristic plot"; ...
    "Current phase: "; "Target progress: "; "Generator backend: "; "Elapsed: "; ...
    "Final status: success"; "Final status: incomplete"; ...
    "Analyzing input channel"; "Reading the file, validating the data contract, and determining visualization capabilities."; ...
    "Input validation"; "Loading HDF5 channel data."; "Input analysis complete"; ...
    "Data, task, and plotting capabilities have been verified."; "Input data is ready. Select “Start prediction” to continue the full workflow."; ...
    "Preparing prediction task"; "Module 2 calibrates using the known region only. Target ground truth is not read."; ...
    "Module 2: preparing data"; "Extracting reference characteristics from the known region."; "Module 2: selecting generator"; ...
    "Selected "; "Module 2: calibration complete"; "Handing off to Module 3 for prediction and target-CIR generation."; ...
    "Generating predicted CIR"; "Module 3 will pass predicted parameters to a compatible formal generator."; ...
    "Module 3: building prediction request"; "Using "; "Module 3: generating target CIR"; ...
    "Predicted CIR, optional CTF, and characteristic plots have been generated."; ...
    "Keep the application window open; one Full 6GPCM target can take tens of seconds."; ...
    "Select “Hide progress panel” to continue reviewing results."; ...
    "Correct the task using the information above and run again."; ...
    "Task axis"; "Local known-region P8 observations"; "Target prediction"; "is not in the current parameter bundle"; ...
    "Category: "; "Note: "; "Status: "; "Backend: "; "Generated targets: "; ...
    "Module 1"; "Module 2"; "Module 3"; "calibration complete"; "calibration failed"; "Running"; ...
    "Input validation failed"; "Prediction incomplete"; "Predicted CIR generated; view characteristics or export"; ...
    "MAT conversion complete; loading automatically"; "The converted output does not exist and cannot be loaded."; "MAT conversion failed"; ...
    "No compatible generator"; "Start prediction (automatic: "; ...
    "Power"; "Frequency autocorrelation"; "Delay-spread CDF"; "Angular power spectrum"; "Spatial correlation"; ...
    "Angular-spread CDF"; "Doppler power spectrum"; "Time autocorrelation"; "Doppler-spread CDF"; "Delay–sample power heatmap"; ...
    "Space"; "Missing-subcarrier pattern (Frequency axis only)"; "Uniform half (every other)"; "Random half"; "Block of 8"; ...
    "Space (green: known, orange: target, gray: unused)" ...
    ];

if direction == "zh_to_en"
    from = zh;
    to = en;
else
    from = en;
    to = zh;
end
end
