function config = default_full_6gpcm_probe_config(engineRoot)
%DEFAULT_FULL_6GPCM_PROBE_CONFIG Fixed-input Step 3 probe configuration.
%   CONFIG = DEFAULT_FULL_6GPCM_PROBE_CONFIG(ENGINEROOT) describes the
%   historical generate_channel_v1 entry point without changing its core.

arguments
    engineRoot (1, 1) string = ""
end

installation = resolve_full_6gpcm_root(EngineRoot=engineRoot);
engineRoot = installation.root;
if installation.is_bundled
    engineId = "full_6gpcm_bundled";
    sourceVersion = "260317";
    expectedTreeHash = ...
        "369d778674004bbda6231b89b967b12c1fecacdddf9306b842db8982309a8ae9";
else
    engineId = "full_6gpcm_external_override";
    sourceVersion = "user-supplied";
    expectedTreeHash = "";
end

config = struct( ...
    "engine_root", engineRoot, ...
    "DS_mu", -7.925, ...
    "DS_sigma", 0.060, ...
    "r_DS", 2.8, ...
    "num_clusters", 12, ...
    "num_rays", 20, ...
    "LNS_ksi", 3.0, ...
    "KF_mu", -0.39, ...
    "KF_sigma", 2.4, ...
    "sample_count", 3, ...
    "random_seed", 3103, ...
    "snapshot_interval_s", 1.0, ...
    "engine_id", engineId, ...
    "source_package_name", "信道生成模块代码_260317.zip", ...
    "source_version", sourceVersion, ...
    "source_package_sha256", ...
        "fcf151adf94038a6cf10d86c6dd687938b085a8f78a64d6829b5439c1d6c5875", ...
    "expected_tree_sha256", expectedTreeHash, ...
    "known_core_settings", struct( ...
        "center_frequency_hz", 16e9, ...
        "scenario", "cmWave_Indoor_LoS", ...
        "tx_elements", 2, ...
        "rx_elements", 2, ...
        "track_type", "static", ...
        "move_time_s", 1, ...
        "sample_rate_hz", 1));
end
