function output = run_full_6gpcm_probe(config)
%RUN_FULL_6GPCM_PROBE Execute the Step 3 external headless call.
%   This is a technical probe, not the production Generator Adapter planned
%   for Step 6. It never edits files under config.engine_root.

arguments
    config (1, 1) struct
end

config = mergeWithDefaults(config);
validateConfig(config);
engineRoot = string(config.engine_root);
entryPoint = fullfile(engineRoot, "generate_channel_v1.m");
if ~isfolder(engineRoot)
    error("run_full_6gpcm_probe:MissingEngineRoot", ...
        "The full 6GPCM engine root does not exist: %s", engineRoot);
end
if ~isfile(entryPoint)
    error("run_full_6gpcm_probe:MissingEntryPoint", ...
        "Expected generate_channel_v1.m under engine root: %s", entryPoint);
end

beforeManifest = hash_full_6gpcm_tree(engineRoot);
if strlength(string(config.expected_tree_sha256)) > 0 && ...
        ~strcmpi(beforeManifest.aggregate_sha256, ...
        string(config.expected_tree_sha256))
    error("run_full_6gpcm_probe:UnexpectedCoreHash", ...
        "Full 6GPCM tree hash %s does not match expected %s.", ...
        beforeManifest.aggregate_sha256, config.expected_tree_sha256);
end

originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
originalRandomState = rng;
rngCleanup = onCleanup(@() rng(originalRandomState));
addpath(genpath(engineRoot), "-begin");
resolvedEntryPoint = string(which("generate_channel_v1"));
if strlength(resolvedEntryPoint) == 0 || ...
        ~isPathInside(resolvedEntryPoint, engineRoot)
    error("run_full_6gpcm_probe:WrongEntryPoint", ...
        "generate_channel_v1 did not resolve inside the requested engine root.");
end

rng(double(config.random_seed), "twister");
startTime = tic;
[HAll, delayAll] = generate_channel_v1( ...
    config.DS_mu, config.DS_sigma, config.r_DS, ...
    config.num_clusters, config.num_rays, config.LNS_ksi, ...
    config.KF_mu, config.KF_sigma, config.sample_count);
elapsedSeconds = toc(startTime);

metadata = buildMetadata(config);
dataset = convert_full_6gpcm_raw_to_cir(HAll, delayAll, metadata);
validation = validate_channel_dataset(dataset);
if ~validation.is_valid
    error("run_full_6gpcm_probe:InvalidCanonicalOutput", ...
        "Converted CIR failed the v3 data contract: %s", ...
        strjoin(validation.errors, " | "));
end

afterManifest = hash_full_6gpcm_tree(engineRoot);
coreUnchanged = beforeManifest.file_count == afterManifest.file_count && ...
    beforeManifest.total_bytes == afterManifest.total_bytes && ...
    strcmpi(beforeManifest.aggregate_sha256, afterManifest.aggregate_sha256);
if ~coreUnchanged
    error("run_full_6gpcm_probe:CoreChanged", ...
        "Full 6GPCM files changed during the probe.");
end

rawShapes = zeros(numel(HAll), 4);
for sample = 1:numel(HAll)
    rawShapes(sample, :) = [size(HAll{sample}, 1), ...
        size(HAll{sample}, 2), size(HAll{sample}, 3), ...
        size(HAll{sample}, 4)];
end
allDelays = cell2mat(cellfun(@(value) value(:), ...
    delayAll(:), "UniformOutput", false));
allCoefficients = cell2mat(cellfun(@(value) value(:), ...
    HAll(:), "UniformOutput", false));

report = struct( ...
    "status", "PASS", ...
    "probe_version", "v3.0-step3.1", ...
    "engine_id", string(config.engine_id), ...
    "source_package_name", string(config.source_package_name), ...
    "source_version", string(config.source_version), ...
    "source_package_sha256", lower(string(config.source_package_sha256)), ...
    "random_seed", double(config.random_seed), ...
    "elapsed_s", elapsedSeconds, ...
    "entrypoint", "generate_channel_v1.m", ...
    "raw_dimension_order", ["Tx", "Rx", "Nt", "Npath"], ...
    "raw_shapes", rawShapes, ...
    "canonical_dimension_order", dataset.dimension_order, ...
    "canonical_shape", fiveDimensionalSize( ...
        dataset.cir.coefficient), ...
    "sample_semantics", string(dataset.metadata.sample_semantics), ...
    "coefficient_is_complex", ~isreal(allCoefficients), ...
    "coefficient_all_finite", all(isfinite(real(allCoefficients))) && ...
        all(isfinite(imag(allCoefficients))), ...
    "delay_all_finite", all(isfinite(allDelays)), ...
    "delay_min_s", min(allDelays), ...
    "delay_max_s", max(allDelays), ...
    "core_unchanged", coreUnchanged, ...
    "tree_file_count", beforeManifest.file_count, ...
    "tree_total_bytes", beforeManifest.total_bytes, ...
    "tree_sha256_before", beforeManifest.aggregate_sha256, ...
    "tree_sha256_after", afterManifest.aggregate_sha256, ...
    "validation", validation, ...
    "capabilities", infer_channel_capabilities(dataset));

output = struct( ...
    "raw", struct("H_all", {HAll}, "delay_all", {delayAll}), ...
    "dataset", dataset, ...
    "report", report, ...
    "manifest", beforeManifest);
clear rngCleanup pathCleanup
end

function config = mergeWithDefaults(config)
engineRoot = "";
if isfield(config, "engine_root")
    engineRoot = string(config.engine_root);
end
defaults = default_full_6gpcm_probe_config(engineRoot);
fieldNames = fieldnames(config);
for index = 1:numel(fieldNames)
    defaults.(fieldNames{index}) = config.(fieldNames{index});
end
config = defaults;
end

function validateConfig(config)
if strlength(strtrim(string(config.engine_root))) == 0
    error("run_full_6gpcm_probe:InvalidConfig", ...
        "config.engine_root must be provided.");
end
positiveFields = ["r_DS", "num_clusters", "num_rays", ...
    "LNS_ksi", "sample_count", "snapshot_interval_s"];
nonnegativeFields = ["DS_sigma", "KF_sigma", "random_seed"];
finiteFields = ["DS_mu", "KF_mu"];
for fieldName = [positiveFields, nonnegativeFields, finiteFields]
    value = config.(fieldName);
    if ~isnumeric(value) || ~isscalar(value) || ~isfinite(value)
        error("run_full_6gpcm_probe:InvalidConfig", ...
            "config.%s must be a finite numeric scalar.", fieldName);
    end
end
for fieldName = positiveFields
    if config.(fieldName) <= 0
        error("run_full_6gpcm_probe:InvalidConfig", ...
            "config.%s must be positive.", fieldName);
    end
end
for fieldName = nonnegativeFields
    if config.(fieldName) < 0
        error("run_full_6gpcm_probe:InvalidConfig", ...
            "config.%s must be nonnegative.", fieldName);
    end
end
integerFields = ["num_clusters", "num_rays", ...
    "sample_count", "random_seed"];
for fieldName = integerFields
    if floor(config.(fieldName)) ~= config.(fieldName)
        error("run_full_6gpcm_probe:InvalidConfig", ...
            "config.%s must be an integer.", fieldName);
    end
end
end

function metadata = buildMetadata(config)
publicConfig = config;
publicConfig = rmfield(publicConfig, "engine_root");
metadata = struct( ...
    "source", "full_6gpcm_external_probe", ...
    "sample_semantics", "independent", ...
    "generator", string(config.engine_id), ...
    "generator_version", string(config.source_version), ...
    "random_seed", double(config.random_seed), ...
    "center_frequency_hz", ...
        double(config.known_core_settings.center_frequency_hz), ...
    "snapshot_interval_s", double(config.snapshot_interval_s), ...
    "scenario_id", string(config.known_core_settings.scenario), ...
    "source_package_name", string(config.source_package_name), ...
    "source_package_sha256", lower(string(config.source_package_sha256)), ...
    "config", publicConfig);
end

function tf = isPathInside(filePath, rootPath)
normalizedFile = lower(replace(string(filePath), "\", "/"));
normalizedRoot = lower(replace(string(rootPath), "\", "/"));
if ~endsWith(normalizedRoot, "/")
    normalizedRoot = normalizedRoot + "/";
end
tf = startsWith(normalizedFile, normalizedRoot);
end

function shape = fiveDimensionalSize(value)
shape = [size(value, 1), size(value, 2), size(value, 3), ...
    size(value, 4), size(value, 5)];
end
