function guidance = user_error_guidance(exception, step)
%USER_ERROR_GUIDANCE Translate a technical exception into user-facing text.
%   Maps an MException identifier to a plain-language explanation with an
%   actionable next step. Unknown errors fall back to a generic template
%   that keeps the technical identifier/message for copying to support.
%
%   STEP is one of "import" | "calibration" | "prediction" | "export".
%   Returns GUIDANCE with:
%     title      - short plain-language title
%     lines      - string array: what happened / why / what to do
%     technical  - copyable technical detail (identifier + message)

arguments
    exception (1, 1)
    step (1, 1) string = "prediction"
end

identifier = string(exception.identifier);
message = string(exception.message);
title = "";
lines = strings(0, 1);

switch identifier
    case "create_channel_task_preset:AxisTooShort"
        title = "任务区间设置不正确";
        lines = [ ...
            "发生了什么：" + message; ...
            "建议：请检查“任务轴”是否与文件匹配，或把“任务预设”改为“精确手动区间”并填写合法范围。"];
    case {"ChannelSimulatorV3App:BadRange", "ChannelSimulatorV3App:UnmappedCoordinate", ...
            "ChannelSimulatorV3App:EmptyRange"}
        title = "手动区间输入有误";
        lines = [ ...
            "发生了什么：" + message; ...
            "建议：请按界面提示填写区间（如 0:30,40:60），或改用“自动 80/20”。"];
    case "ChannelSimulatorV3App:NoCompatibleGenerator"
        title = "没有可用的生成器";
        lines = [ ...
            "发生了什么：当前文件的天线/时间维度没有兼容的正式生成器。"; ...
            "建议：请检查 Full 6GPCM 引擎路径是否已配置，或换用平台支持的数据规模。"; ...
            "技术详情：" + message];
    case {"run_v32_axis_prediction:NeuralModelUnavailable", ...
            "run_v32_axis_prediction:UnsupportedModel"}
        title = "所选模型不可用";
        lines = [ ...
            "发生了什么：" + message; ...
            "建议：请从“手动模型”下拉中选择支持的模型，或使用“自动推荐”。"];
    case {"v32_axis_neural_forecast:PythonFailure", ...
            "run_predictor_adapter:PythonFailure", ...
            "run_predictor_request_adapter:PythonFailure"}
        title = "模型计算程序运行失败";
        lines = [ ...
            "发生了什么：神经模型需要调用 Python 计算环境，但运行失败。"; ...
            "建议：请重试一次；若仍失败，请把下面的技术详情发给负责人。"; ...
            "技术详情：" + message];
    case "build_channel_fit_target:MissingPdp"
        title = "标定无法进行（数据结构限制）";
        lines = [ ...
            "发生了什么：该数据无法构建标定所需的参考特征（频率已知区不是均匀网格，无法转换到时延域）。"; ...
            "建议：这是数据结构的限制，不是操作错误；请改用支持的任务配置，或联系负责人。"; ...
            "技术详情：" + message];
    case "ChannelSimulatorV3App:NoSelectedFile"
        title = "尚未选择文件";
        lines = ["发生了什么：" + message; "建议：请先点击“浏览信道文件…”选择文件。"];
    otherwise
        title = "操作未成功";
        lines = [ ...
            "发生了什么：" + message; ...
            "建议：请按提示检查任务设置后重试；若反复失败，请把下面的技术详情发给负责人。"];
end

if ~any(contains(lines, "技术详情")) && ...
        ~contains(identifier, "ChannelSimulatorV3App")
    % Keep the raw identifier/message available for support.
    technical = identifier + " | " + message;
    lines(end + 1, 1) = "技术详情：" + technical; %#ok<AGROW>
end

guidance = struct( ...
    "schema_version", "v3.2-4b-user-error-guidance.1", ...
    "step", step, ...
    "title", title, ...
    "lines", lines, ...
    "technical", identifier + " | " + message);
end
