function outputPath = render_step9_predictor_data_review( ...
        outputDirectory, options)
%RENDER_STEP9_PREDICTOR_DATA_REVIEW Render deterministic Step 9 review.

arguments
    outputDirectory (1, 1) string
    options.Visible (1, 1) string = "off"
end

root = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(fullfile(root, "core")));
if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end
fixture = create_step9_standard_fixture();
sequence = fixture.parameter_sequence;
dataset = fixture.extrapolation.dataset;
split = fixture.extrapolation.split;

figureHandle = figure("Visible", options.Visible, "Color", "white", ...
    "Position", [20, 25, 1500, 900]);
cleanup = onCleanup(@() closeIfValid(figureHandle));
layout = tiledlayout(figureHandle, 2, 3, ...
    "TileSpacing", "compact", "Padding", "compact");

overview = nexttile(layout);
axis(overview, "off");
text(overview, 0.03, 0.95, [ ...
    "数据契约（不是模型训练结果）"; ...
    ""; ...
    "参数序列：" + sizeText(size(sequence.values)); ...
    "顺序：[N_parameter_sample, P]"; ...
    "标准参数：DS_mu、KF_mu"; ...
    ""; ...
    "模型输入：" + sizeText(size(dataset.inputs)); ...
    "顺序：[N_example, N_context, P]"; ...
    "模型标签：" + sizeText(size(dataset.targets)); ...
    "顺序：[N_example, N_target, P]"; ...
    ""; ...
    "标签来源：generator_truth"; ...
    "用途：Step 10 泛用模型预训练"; ...
    "注意：本图使用确定性合成小样例"], ...
    "Units", "normalized", "VerticalAlignment", "top", ...
    "FontName", "Microsoft YaHei UI", "FontSize", 11.5);
title(overview, "① 统一的数据盒子", ...
    "FontName", "Microsoft YaHei UI");

route = nexttile(layout);
rows = sequence.group_id == "route-01";
local = sequence.parameter_sample_index(rows);
yyaxis(route, "left");
plot(route, local, sequence.values(rows, 1), "o-", ...
    "LineWidth", 1.6, "Color", [0.08, 0.38, 0.75]);
ylabel(route, "DS\_mu (log10 s)");
yyaxis(route, "right");
plot(route, local, sequence.values(rows, 2), "s-", ...
    "LineWidth", 1.6, "Color", [0.93, 0.49, 0.12]);
ylabel(route, "KF\_mu (dB)");
xlabel(route, "一条路线中的参数样本序号");
title(route, "② 每条路线形成参数序列", ...
    "FontName", "Microsoft YaHei UI");
grid(route, "on");

extrap = nexttile(layout);
renderTaskBlocks(extrap, [16, 4], ...
    ["已知历史 16", "未来 4"], ...
    [0.20, 0.55, 0.86; 0.95, 0.55, 0.16]);
title(extrap, "③ 外推：16 → 4", ...
    "FontName", "Microsoft YaHei UI");

interp = nexttile(layout);
renderTaskBlocks(interp, [8, 4, 8], ...
    ["已知左侧 8", "中间 4", "已知右侧 8"], ...
    [0.20, 0.55, 0.86; 0.95, 0.55, 0.16; 0.20, 0.55, 0.86]);
title(interp, "④ 内插：左 8 + 右 8 → 中间 4", ...
    "FontName", "Microsoft YaHei UI");

splitAxes = nexttile(layout);
counts = [numel(split.train_group_id), ...
    numel(split.validation_group_id), numel(split.test_group_id)];
splitLabels = categorical(["训练", "验证", "测试"]);
splitLabels = reordercats(splitLabels, ["训练", "验证", "测试"]);
bar(splitAxes, splitLabels, counts, ...
    "FaceColor", [0.18, 0.62, 0.42]);
ylim(splitAxes, [0, 8]);
ylabel(splitAxes, "完整路线/场景组数量");
title(splitAxes, "⑤ 按组切分 7 / 1 / 2", ...
    "FontName", "Microsoft YaHei UI");
text(splitAxes, 2, 7.3, ...
    "相邻样本不会被随机拆到不同集合", ...
    "HorizontalAlignment", "center", ...
    "FontName", "Microsoft YaHei UI");
grid(splitAxes, "on");

normalAxes = nexttile(layout);
trainRows = ismember(sequence.group_id, split.train_group_id);
rawDs = sequence.values(:, 1);
normalizedDs = (rawDs - dataset.normalization.mean(1)) / ...
    dataset.normalization.standard_deviation(1);
scatter(normalAxes, rawDs(trainRows), normalizedDs(trainRows), ...
    20, [0.18, 0.62, 0.42], "filled", ...
    "DisplayName", "训练组（用于计算均值/标准差）");
hold(normalAxes, "on");
scatter(normalAxes, rawDs(~trainRows), normalizedDs(~trainRows), ...
    20, [0.75, 0.35, 0.30], "filled", ...
    "DisplayName", "验证/测试组（只应用，不参与计算）");
hold(normalAxes, "off");
xlabel(normalAxes, "原始 DS\_mu");
ylabel(normalAxes, "训练集 Z-score");
title(normalAxes, "⑥ 归一化只看训练组", ...
    "FontName", "Microsoft YaHei UI");
legend(normalAxes, "Location", "best");
grid(normalAxes, "on");

title(layout, ...
    "ChanAI Pulse v3 Step 9 · 正式预测参数与训练数据契约", ...
    "FontName", "Microsoft YaHei UI", "FontWeight", "bold");
outputPath = fullfile(outputDirectory, ...
    "step9_predictor_data_review.png");
exportgraphics(figureHandle, outputPath, "Resolution", 150);
clear cleanup
end

function renderTaskBlocks(axesHandle, widths, labels, colors)
cla(axesHandle);
hold(axesHandle, "on");
start = 0;
for index = 1:numel(widths)
    rectangle(axesHandle, "Position", ...
        [start, 0.25, widths(index), 0.5], ...
        "FaceColor", colors(index, :), ...
        "EdgeColor", "white", "LineWidth", 1.5);
    text(axesHandle, start + widths(index) / 2, 0.5, ...
        labels(index), "HorizontalAlignment", "center", ...
        "Color", "white", "FontWeight", "bold", ...
        "FontName", "Microsoft YaHei UI");
    start = start + widths(index);
end
hold(axesHandle, "off");
xlim(axesHandle, [0, start]);
ylim(axesHandle, [0, 1]);
xlabel(axesHandle, "连续参数样本位置");
yticks(axesHandle, []);
box(axesHandle, "on");
end

function text = sizeText(shape)
text = strjoin(string(shape), " × ");
end

function closeIfValid(figureHandle)
if isvalid(figureHandle)
    close(figureHandle);
end
end
