function outputPath = render_step8_optimizer_review( ...
        outputDirectory, options)
%RENDER_STEP8_OPTIMIZER_REVIEW Render a reproducible Step 8 review sheet.

arguments
    outputDirectory (1, 1) string
    options.Visible (1, 1) string = "off"
    options.EngineRoot (1, 1) string = ""
end

root = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(fullfile(root, "core")));
if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end

[targetConfig, target] = buildTarget("mock", "");
config = comparisonConfig(targetConfig);
gridConfig = config;
gridConfig.requested_strategy = "grid";
gridResult = run_parameter_optimization(target.dataset, gridConfig);
saConfig = config;
saConfig.requested_strategy = "sa";
saResult = run_simulated_annealing(target.dataset, saConfig);
greedyResult = run_random_greedy_search(target.dataset, saConfig);
assert(gridResult.success && saResult.success && greedyResult.success);

fullLine = "真实Full：本次未配置外置引擎";
if options.EngineRoot ~= "" && isfolder(options.EngineRoot)
    [fullConfig, fullTarget] = buildTarget( ...
        "full_6gpcm", options.EngineRoot);
    fullOptimization = default_optimization_config("full_6gpcm");
    fullOptimization.requested_strategy = "sa";
    fullOptimization.generator_config = fullConfig;
    fullOptimization.variables = struct("DS_mu", discreteDescriptor( ...
        [fullConfig.model.DS_mu, fullConfig.model.DS_mu + 0.1], ...
        fullConfig.model.DS_mu + 0.1));
    fullOptimization.limits.max_evaluations = 2;
    fullOptimization.sa.no_improvement_limit = 8;
    fullOptimization.sa.proposals_per_temperature = 4;
    fullResult = run_parameter_optimization( ...
        fullTarget.dataset, fullOptimization);
    assert(fullResult.success);
    fullLine = sprintf( ...
        "真实Full：SA成功，最佳 %.6f，核心未修改=%s", ...
        fullResult.best.total_score, string( ...
            fullResult.best.generation_result. ...
            backend_manifest.core_unchanged));
end

figureHandle = figure("Visible", options.Visible, "Color", "white", ...
    "Position", [20, 25, 1550, 920]);
cleanup = onCleanup(@() closeIfValid(figureHandle));
layout = tiledlayout(figureHandle, 2, 3, ...
    "TileSpacing", "compact", "Padding", "compact");

overviewAxes = nexttile(layout);
axis(overviewAxes, "off");
decisionSmall = select_optimization_strategy( ...
    default_optimization_config("mock"));
continuousConfig = default_optimization_config("mock");
continuousConfig.variables = struct("DS_mu", struct( ...
    "type", "continuous", "lower", -8.1, "upper", -7.7, ...
    "initial", -7.9, "step_fraction", 0.1));
[~, continuousConfig] = validate_optimization_config(continuousConfig);
decisionContinuous = select_optimization_strategy(continuousConfig);
fullDefault = default_optimization_config("full_6gpcm");
[~, fullDefault] = validate_optimization_config(fullDefault);
decisionFull = select_optimization_strategy(fullDefault);
lines = [ ...
    "统一链路：known目标 → 同一生成器 → 同一评分 → Grid/Random/SA"; ...
    ""; ...
    "自动决策样例："; ...
    "● Mock小型全离散 27组 → " + ...
        upper(decisionSmall.selected_strategy); ...
    "● 含连续区间 → " + ...
        upper(decisionContinuous.selected_strategy); ...
    "● Full默认27组，自动上限16 → " + ...
        upper(decisionFull.selected_strategy); ...
    ""; ...
    "固定种子：生成器3103 / 优化器8103"; ...
    "SA默认：T0=0.10，α=0.90，Tmin=0.001"; ...
    fullLine; ...
    ""; ...
    "边界：拟合距离不是预测准确率；Random Greedy仅作对照"];
text(overviewAxes, 0.02, 0.97, lines, ...
    "Units", "normalized", "VerticalAlignment", "top", ...
    "FontName", "Microsoft YaHei UI", "FontSize", 11.2, ...
    "Interpreter", "none");
title(overviewAxes, "Step 8 决策规则与边界", ...
    "FontName", "Microsoft YaHei UI", "FontWeight", "bold");

scoreAxes = nexttile(layout);
labels = categorical(["Grid", "Random Greedy", "SA"]);
labels = reordercats(labels, ["Grid", "Random Greedy", "SA"]);
evaluationCounts = [gridResult.counts.objective_evaluations, ...
    greedyResult.objective_evaluations, saResult.objective_evaluations];
bar(scoreAxes, labels, evaluationCounts, ...
    "FaceColor", [0.30, 0.55, 0.78]);
ylabel(scoreAxes, "实际生成与评分次数");
title(scoreAxes, sprintf( ...
    "同一目标成本对照（最佳分数 %.1g / %.1g / %.1g）", ...
    gridResult.best.total_score, greedyResult.best.total_score, ...
    saResult.best.total_score), ...
    "FontName", "Microsoft YaHei UI");
grid(scoreAxes, "on");

convergenceAxes = nexttile(layout);
renderConvergence(convergenceAxes, greedyResult, saResult);

temperatureAxes = nexttile(layout);
renderTemperature(temperatureAxes, saResult);

pdpAxes = nexttile(layout);
renderPdp(pdpAxes, saResult.best.score);

dsAxes = nexttile(layout);
renderDs(dsAxes, saResult.best.score);

title(layout, ...
    "ChanAI Pulse v3 Step 8 · 自动策略、随机贪心与模拟退火审阅图", ...
    "FontName", "Microsoft YaHei UI", "FontWeight", "bold");
outputPath = fullfile(outputDirectory, "step8_optimizer_review.png");
exportgraphics(figureHandle, outputPath, "Resolution", 150);
clear cleanup
end

function [config, generation] = buildTarget(backend, engineRoot)
config = default_generator_config(backend);
config.random_seed = 3103;
switch backend
    case "mock"
        config.dimensions = struct( ...
            "Tx", 1, "Rx", 1, "Npath", 10, ...
            "Nt", 2, "N_sample", 6);
    case "full_6gpcm"
        config.engine_root = engineRoot;
        config.dimensions.N_sample = 1;
end
generation = run_generator_adapter(config);
assert(generation.success);
end

function config = comparisonConfig(targetConfig)
config = default_optimization_config("mock");
config.generator_config = targetConfig;
config.variables = struct( ...
    "DS_mu", discreteDescriptor( ...
        [targetConfig.model.DS_mu, targetConfig.model.DS_mu + 0.1], ...
        targetConfig.model.DS_mu + 0.1), ...
    "KF_mu", discreteDescriptor( ...
        [targetConfig.model.KF_mu, targetConfig.model.KF_mu + 0.5], ...
        targetConfig.model.KF_mu + 0.5), ...
    "num_clusters", discreteDescriptor( ...
        [targetConfig.model.num_clusters - 3, ...
            targetConfig.model.num_clusters], ...
        targetConfig.model.num_clusters - 3));
config.limits.max_evaluations = 18;
config.sa.no_improvement_limit = 18;
config.sa.proposals_per_temperature = 6;
end

function descriptor = discreteDescriptor(values, initial)
descriptor = struct( ...
    "type", "discrete", "values", values, ...
    "initial", initial, "step_fraction", 1);
end

function renderConvergence(axesHandle, greedy, sa)
greedyHistory = greedy.history([greedy.history.success]);
saHistory = sa.history([sa.history.success]);
plot(axesHandle, [greedyHistory.proposal_index], ...
    [greedyHistory.best_score], "o-", ...
    "LineWidth", 1.5, "DisplayName", "Random Greedy最佳");
hold(axesHandle, "on");
plot(axesHandle, [saHistory.proposal_index], ...
    [saHistory.best_score], "s-", ...
    "LineWidth", 1.5, "DisplayName", "SA最佳");
hold(axesHandle, "off");
xlabel(axesHandle, "提案序号");
ylabel(axesHandle, "截至当时的最佳距离");
title(axesHandle, "随机搜索过程对照", ...
    "FontName", "Microsoft YaHei UI");
legend(axesHandle, "Location", "best");
grid(axesHandle, "on");
end

function renderTemperature(axesHandle, result)
levels = result.temperature_history;
yyaxis(axesHandle, "left");
plot(axesHandle, [levels.level], [levels.temperature], ...
    "o-", "LineWidth", 1.8);
ylabel(axesHandle, "温度");
yyaxis(axesHandle, "right");
plot(axesHandle, [levels.level], [levels.acceptance_rate], ...
    "s-", "LineWidth", 1.5);
ylabel(axesHandle, "本层接受率");
xlabel(axesHandle, "温度层");
title(axesHandle, sprintf( ...
    "SA温度与接受率（接受较差 %d 次）", ...
    result.worse_accepted_proposals), ...
    "FontName", "Microsoft YaHei UI");
grid(axesHandle, "on");
end

function renderPdp(axesHandle, score)
features = score.features;
plot(axesHandle, features.pdp_centers_s * 1e9, ...
    features.target_pdp_probability, "LineWidth", 1.8, ...
    "DisplayName", "目标known");
hold(axesHandle, "on");
plot(axesHandle, features.pdp_centers_s * 1e9, ...
    features.candidate_pdp_probability, "--", "LineWidth", 1.8, ...
    "DisplayName", "SA最佳");
hold(axesHandle, "off");
xlabel(axesHandle, "时延 (ns)");
ylabel(axesHandle, "归一化概率");
title(axesHandle, "目标 vs SA最佳 PDP", ...
    "FontName", "Microsoft YaHei UI");
legend(axesHandle, "Location", "best");
grid(axesHandle, "on");
end

function renderDs(axesHandle, score)
features = score.features;
plot(axesHandle, features.quantile_probability, ...
    features.target_delay_spread_quantile_s * 1e9, ...
    "LineWidth", 1.8, "DisplayName", "目标known");
hold(axesHandle, "on");
plot(axesHandle, features.quantile_probability, ...
    features.candidate_delay_spread_quantile_s * 1e9, "--", ...
    "LineWidth", 1.8, "DisplayName", "SA最佳");
hold(axesHandle, "off");
xlabel(axesHandle, "分位概率");
ylabel(axesHandle, "RMS时延扩展 (ns)");
title(axesHandle, "目标 vs SA最佳时延扩展", ...
    "FontName", "Microsoft YaHei UI");
legend(axesHandle, "Location", "best");
grid(axesHandle, "on");
end

function closeIfValid(figureHandle)
if isvalid(figureHandle)
    close(figureHandle);
end
end
