function figureHandle = step9_predictor_data_demo(options)
%STEP9_PREDICTOR_DATA_DEMO Standalone beginner-friendly contract browser.

arguments
    options.Visible (1, 1) string = "on"
end

root = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(fullfile(root, "core")));
fixture = create_step9_standard_fixture();

figureHandle = uifigure( ...
    "Name", "ChanAI Pulse v3 - Step 9 Predictor Data Demo", ...
    "Position", [30, 40, 1480, 850], ...
    "Color", [0.96, 0.97, 0.985], ...
    "Visible", options.Visible);
layout = uigridlayout(figureHandle, [4, 1], ...
    "RowHeight", {58, 90, "1x", 34}, ...
    "Padding", [12, 10, 12, 10], "RowSpacing", 8);

header = uipanel(layout, "BackgroundColor", "white", ...
    "BorderColor", [0.50, 0.68, 0.88]);
headerGrid = uigridlayout(header, [1, 3], ...
    "ColumnWidth", {240, "1x", 350}, "Padding", [14, 5, 14, 5]);
uilabel(headerGrid, "Text", "● ChanAI Pulse", ...
    "FontSize", 18, "FontWeight", "bold", ...
    "FontColor", [0.04, 0.29, 0.56]);
uilabel(headerGrid, "Text", "Step 9 · 预测数据准备工作台", ...
    "HorizontalAlignment", "center", "FontSize", 19, ...
    "FontWeight", "bold", "FontColor", [0.04, 0.29, 0.56]);
uilabel(headerGrid, ...
    "Text", "独立体验 Demo · 尚未训练预测模型", ...
    "HorizontalAlignment", "right", ...
    "FontColor", [0.42, 0.46, 0.51]);

controls = uipanel(layout, "Title", "查看一条标准训练样本", ...
    "BackgroundColor", "white", "FontWeight", "bold");
controlGrid = uigridlayout(controls, [2, 8], ...
    "RowHeight", {28, 28}, ...
    "ColumnWidth", {72, 150, 72, 120, 72, 145, "1x", 260}, ...
    "Padding", [12, 5, 12, 5]);
uilabel(controlGrid, "Text", "任务类型", "HorizontalAlignment", "right");
taskDrop = uidropdown(controlGrid, ...
    "Items", ["外推（16→4）", "内插（8+8→中4）"], ...
    "ItemsData", ["extrapolation", "interpolation"], ...
    "Value", "extrapolation", "ValueChangedFcn", @refresh);
uilabel(controlGrid, "Text", "路线组", "HorizontalAlignment", "right");
groupDrop = uidropdown(controlGrid, ...
    "Items", unique(fixture.parameter_sequence.group_id), ...
    "Value", "route-01", "ValueChangedFcn", @refresh);
uilabel(controlGrid, "Text", "样本编号", "HorizontalAlignment", "right");
exampleSpinner = uispinner(controlGrid, ...
    "Limits", [1, 9], "Value", 1, "RoundFractionalValues", "on", ...
    "ValueChangedFcn", @refresh);
status = uilabel(controlGrid, ...
    "Text", "PASS · 契约可用", "HorizontalAlignment", "center", ...
    "FontWeight", "bold", ...
    "BackgroundColor", [0.84, 0.95, 0.88], ...
    "FontColor", [0.08, 0.50, 0.25]);
status.Layout.Column = 8;
uilabel(controlGrid, "Text", "固定参数", "HorizontalAlignment", "right");
parameterLabel = uilabel(controlGrid, ...
    "Text", "P=2：DS_mu、KF_mu");
parameterLabel.Layout.Column = [2, 3];
uilabel(controlGrid, "Text", "切分规则", "HorizontalAlignment", "right");
splitLabel = uilabel(controlGrid, ...
    "Text", "按路线组 70% / 15% / 15%，禁止相邻泄漏");
splitLabel.Layout.Column = [5, 8];

body = uigridlayout(layout, [2, 3], ...
    "RowHeight", {"1x", "1x"}, ...
    "ColumnWidth", {"1x", "1x", 420}, ...
    "Padding", [0, 0, 0, 0], "RowSpacing", 8, "ColumnSpacing", 8);
inputAxes = demoAxes(body, 1, 1, "模型输入：已知参数");
targetAxes = demoAxes(body, 1, 2, "模型标签：待预测参数");
sequenceAxes = demoAxes(body, 2, [1, 2], ...
    "原始路线参数序列与当前窗口");
side = uipanel(body, "Title", "这份数据代表什么？", ...
    "BackgroundColor", "white");
side.Layout.Row = [1, 2];
side.Layout.Column = 3;
sideGrid = uigridlayout(side, [2, 1], ...
    "RowHeight", {225, "1x"}, "Padding", [8, 8, 8, 8]);
shapeTable = uitable(sideGrid, "RowName", [], ...
    "ColumnName", {"对象", "形状", "含义"}, ...
    "ColumnWidth", {82, 105, 180});
explanation = uitextarea(sideGrid, "Editable", "off", ...
    "FontName", "Microsoft YaHei UI");

uilabel(layout, ...
    "Text", "Step 9 只负责把参数整理成可靠训练样本；泛用模型训练和每次上传后的微调属于 Step 10。", ...
    "BackgroundColor", "white", ...
    "FontColor", [0.42, 0.46, 0.51]);

refresh();

    function refresh(~, ~)
        task = string(taskDrop.Value);
        taskBundle = fixture.(task);
        data = taskBundle.dataset;
        groupExamples = find(data.example_group_id == ...
            string(groupDrop.Value));
        exampleSpinner.Limits = [1, max(1, numel(groupExamples))];
        exampleSpinner.Value = min(exampleSpinner.Value, ...
            exampleSpinner.Limits(2));
        exampleIndex = groupExamples(exampleSpinner.Value);
        renderExample(inputAxes, squeeze(data.inputs(exampleIndex, :, :)), ...
            data.parameter_names, [0.12, 0.46, 0.78]);
        renderExample(targetAxes, squeeze(data.targets(exampleIndex, :, :)), ...
            data.parameter_names, [0.93, 0.49, 0.12]);
        renderSequence(sequenceAxes, fixture.parameter_sequence, ...
            string(groupDrop.Value), ...
            data.input_parameter_sample_index(exampleIndex, :), ...
            data.target_parameter_sample_index(exampleIndex, :));
        shapeTable.Data = { ...
            '参数序列', sprintf('%d × %d', ...
                size(fixture.parameter_sequence.values)), ...
                '沿路线排列的参数标签'; ...
            '模型输入', sprintf('%d × %d × %d', ...
                size(data.inputs)), '每个样本的已知上下文'; ...
            '模型标签', sprintf('%d × %d × %d', ...
                size(data.targets)), '模型应该学会输出的答案'};
        if task == "extrapolation"
            taskText = "外推：把前面连续 16 个参数交给模型，让它学习预测后面 4 个。";
        else
            taskText = "内插：把左边 8 个和右边 8 个交给模型，让它学习补出中间缺失的 4 个。";
        end
        explanation.Value = cellstr([ ...
            taskText; ""; ...
            "蓝色是模型能够看见的信息，橙色是训练时提供的标准答案。"; ...
            ""; ...
            "每条 route 单独形成窗口，不允许一个样本跨越两条路线。"; ...
            ""; ...
            "归一化的均值与标准差只由训练路线计算；验证和测试路线不能提前泄露给模型。"; ...
            ""; ...
            "当前为 generator_truth 确定性合成样例，可用于预训练与接口测试，不代表真实测量精度。"]);
    end
end

function axesHandle = demoAxes(parent, row, column, titleText)
panel = uipanel(parent, "Title", titleText, ...
    "BackgroundColor", "white");
panel.Layout.Row = row;
panel.Layout.Column = column;
axesHandle = uiaxes(panel);
grid(axesHandle, "on");
end

function renderExample(axesHandle, values, names, color)
cla(axesHandle);
plot(axesHandle, values, "o-", "LineWidth", 1.6);
xlabel(axesHandle, "窗口内部位置");
ylabel(axesHandle, "归一化参数值");
legend(axesHandle, names, "Location", "best");
colororder(axesHandle, [color; 0.60, 0.25, 0.70]);
grid(axesHandle, "on");
end

function renderSequence(axesHandle, sequence, groupId, inputIndex, targetIndex)
rows = find(sequence.group_id == groupId);
local = sequence.parameter_sample_index(rows);
values = sequence.values(rows, 1);
cla(axesHandle);
plot(axesHandle, local, values, "o-", ...
    "Color", [0.60, 0.65, 0.70], "LineWidth", 1.2, ...
    "DisplayName", "整条路线 DS_mu");
hold(axesHandle, "on");
inputMask = ismember(local, inputIndex);
targetMask = ismember(local, targetIndex);
scatter(axesHandle, local(inputMask), values(inputMask), 55, ...
    [0.12, 0.46, 0.78], "filled", "DisplayName", "模型输入");
scatter(axesHandle, local(targetMask), values(targetMask), 65, ...
    [0.93, 0.49, 0.12], "filled", "DisplayName", "训练标签");
hold(axesHandle, "off");
xlabel(axesHandle, "路线内参数样本序号");
ylabel(axesHandle, "DS_mu");
legend(axesHandle, "Location", "best");
grid(axesHandle, "on");
end
