% Minimal ChanAI Pulse v3 CTF and interpolation example.

repoRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(genpath(fullfile(repoRoot, "core")));

Tx = 1;
Rx = 1;
Nf = 8;
Nt = 1;
N_sample = 10;

H = complex(randn(Tx, Rx, Nf, Nt, N_sample), ...
    randn(Tx, Rx, Nf, Nt, N_sample));
frequencyHz = (3.5e9 + (0:Nf-1) * 15e3).';

dataset = create_channel_dataset( ...
    "ctf", ...
    struct("H", H), ...
    struct( ...
        "frequency_hz", frequencyHz, ...
        "sample_index", (1:N_sample).'), ...
    struct( ...
        "source", "synthetic_example", ...
        "sample_semantics", "independent"));

task = create_channel_task( ...
    "interpolation", ...
    "sample", ...
    [1:4, 7:10], ...
    [5, 6], ...
    struct("axis_values", 1:N_sample));

dataReport = validate_channel_dataset(dataset);
taskReport = validate_channel_task(dataset, task);
capabilities = infer_channel_capabilities(dataset);

disp(dataReport);
disp(taskReport);
disp(capabilities);
