function target = build_channel_fit_target(dataset, task, scoring)
%BUILD_CHANNEL_FIT_TARGET Build Step 7 features from the known task region.

arguments
    dataset (1, 1) struct
    task (1, 1) struct
    scoring (1, 1) struct
end

analysis = analyze_channel_characteristics(dataset, ...
    Task=task, Region="known", ModuleRole="input");
if analysis.status == "FAIL"
    error("build_channel_fit_target:AnalysisFailed", ...
        "Target channel analysis failed: %s", ...
        strjoin(analysis.errors, " | "));
end
if ~analysis.metrics.pdp.available
    error("build_channel_fit_target:MissingPdp", ...
        "Step 7 requires a reliable wideband PDP: %s", ...
        analysis.metrics.pdp.reason);
end

delaySpread = double(analysis.raw.delay_spread_s(:));
delaySpread = delaySpread(isfinite(delaySpread) & delaySpread >= 0);
if isempty(delaySpread)
    error("build_channel_fit_target:MissingDelaySpread", ...
        "Step 7 requires at least one finite RMS delay-spread value.");
end

pdp = analysis.metrics.pdp.raw;
delayS = double(pdp.delay_s(:));
power = double(pdp.linear_power(:));
valid = isfinite(delayS) & delayS >= 0 & ...
    isfinite(power) & power >= 0;
delayS = delayS(valid);
power = power(valid);
if isempty(delayS) || sum(power) <= 0
    error("build_channel_fit_target:InvalidPdp", ...
        "Target PDP has no finite positive-power paths.");
end

maximumDelay = max(delayS);
if maximumDelay <= 0
    error("build_channel_fit_target:ZeroDelayWindow", ...
        "Target PDP must contain at least one positive delay.");
end
windowS = maximumDelay * scoring.delay_window_margin;
edgesS = linspace(0, windowS, scoring.common_delay_bins + 1).';
probability = weightedDelayHistogram(delayS, power, edgesS);

target = struct( ...
    "schema_version", "v3.0-channel-fit-target.1", ...
    "analysis", analysis, ...
    "classification", string(analysis.classification), ...
    "selection", analysis.selection, ...
    "pdp", struct( ...
        "delay_s", delayS, ...
        "linear_power", power, ...
        "edges_s", edgesS, ...
        "centers_s", (edgesS(1:end-1) + edgesS(2:end)) / 2, ...
        "probability", probability, ...
        "window_s", windowS), ...
    "delay_spread_s", delaySpread, ...
        "summary", struct( ...
        "selected_sample_count", ...
            analysis.dataset_summary.N_sample, ...
        "pdp_path_count", numel(delayS), ...
        "pdp_window_s", windowS, ...
        "delay_spread_count", numel(delaySpread), ...
        "delay_spread_median_s", median(delaySpread), ...
        "delay_spread_p90_s", empiricalQuantile(delaySpread, 0.9)), ...
    "warnings", string(analysis.warnings(:)), ...
    "provenance", struct( ...
        "source", string(analysis.provenance.source), ...
        "region", "known", ...
        "characteristics_engine", ...
            string(analysis.provenance.engine_version)));
end

function probability = weightedDelayHistogram(delayS, power, edgesS)
clipped = min(max(delayS(:), edgesS(1)), edgesS(end));
[~, ~, bins] = histcounts(clipped, edgesS);
valid = bins > 0;
histogram = accumarray(bins(valid), power(valid), ...
    [numel(edgesS) - 1, 1], @sum, 0);
total = sum(histogram);
if total <= 0
    error("build_channel_fit_target:EmptyHistogram", ...
        "Target PDP histogram has zero total power.");
end
probability = histogram / total;
end

function value = empiricalQuantile(values, probability)
values = sort(double(values(:)));
if isscalar(values)
    value = values(1);
    return;
end
position = 1 + (numel(values) - 1) * probability;
lowerIndex = floor(position);
upperIndex = ceil(position);
fraction = position - lowerIndex;
value = values(lowerIndex) * (1 - fraction) + ...
    values(upperIndex) * fraction;
end
