function result = create_capability_default_calibration(analysis, config)
%CREATE_CAPABILITY_DEFAULT_CALIBRATION Honest fallback for narrowband data.
%   A one-tap narrowband channel has no resolvable PDP, so DS/KF generator
%   parameters cannot be identified by Grid/SA. This result records that
%   capability boundary and supplies versioned generator defaults without
%   claiming they were estimated from unavailable delay information.

arguments
    analysis (1, 1) struct
    config (1, 1) struct
end

if ~isfield(analysis, "classification") || ...
        string(analysis.classification) ~= "narrowband_static_siso"
    error("create_capability_default_calibration:WrongCapability", ...
        "Capability-default calibration is reserved for narrowband static SISO.");
end
generator = config.generator_config;
knownPower = NaN;
if isfield(analysis, "metrics") && isfield(analysis.metrics, "power") && ...
        isfield(analysis.metrics.power, "summary") && ...
        isfield(analysis.metrics.power.summary, "mean_power_linear")
    knownPower = double(analysis.metrics.power.summary.mean_power_linear);
end
reason = "单抽头窄带输入没有可辨识宽带 PDP；Grid/SA 不适用。" + ...
    "平台保留已知区功率摘要，并对不可辨识的生成器参数使用版本化默认值。";
publicGenerator = sanitize_generator_config(generator);
result = struct( ...
    "schema_version", "v3.0-capability-default-calibration.1", ...
    "status", "WARNING", ...
    "outcome", "SUCCEEDED", ...
    "success", true, ...
    "complete", true, ...
    "cancelled", false, ...
    "formal_eligible", ~logical(generator.engine.test_only), ...
    "requested_strategy", string(config.requested_strategy), ...
    "selected_strategy", "capability_defaults", ...
    "selection_source", "capability_rule", ...
    "selection_reason_code", "NARROWBAND_PDP_NOT_IDENTIFIABLE", ...
    "selection_reason", reason, ...
    "selection", struct( ...
        "requested_strategy", string(config.requested_strategy), ...
        "selected_strategy", "capability_defaults", ...
        "source", "capability_rule", ...
        "reason_code", "NARROWBAND_PDP_NOT_IDENTIFIABLE", ...
        "reason", reason), ...
    "best", struct( ...
        "parameters", generator.model, ...
        "score", NaN, ...
        "parameter_source", "versioned_generator_defaults"), ...
    "config", struct( ...
        "schema_version", string(config.schema_version), ...
        "requested_strategy", string(config.requested_strategy), ...
        "generator_config", publicGenerator), ...
    "warnings", reason, ...
    "errors", strings(0, 1), ...
    "manifest", struct( ...
        "schema_version", "v3.0-capability-default-calibration-manifest.1", ...
        "requested_strategy", string(config.requested_strategy), ...
        "selected_strategy", "capability_defaults", ...
        "selection_source", "capability_rule", ...
        "selection_reason_code", "NARROWBAND_PDP_NOT_IDENTIFIABLE", ...
        "selection_reason", reason, ...
        "best_score", NaN, ...
        "known_region_mean_power_linear", knownPower, ...
        "parameter_source", "versioned_generator_defaults", ...
        "generator_config", publicGenerator, ...
        "target_ground_truth_read", false));
end
