function config = default_grid_search_config(backend)
%DEFAULT_GRID_SEARCH_CONFIG Return the frozen Step 7 search defaults.

arguments
    backend (1, 1) string = "mock"
end

generatorConfig = default_generator_config(backend);
config = struct( ...
    "schema_version", "v3.0-grid-search-config.1", ...
    "generator_config", generatorConfig, ...
    "parameter_space", struct( ...
        "DS_mu", [-8.05, -7.925, -7.80], ...
        "KF_mu", [-0.80, -0.39, 0.00], ...
        "num_clusters", [8, 12, 16]), ...
    "scoring", struct( ...
        "pdp_weight", 0.5, ...
        "delay_spread_weight", 0.5, ...
        "common_delay_bins", 128, ...
        "delay_window_margin", 1.05, ...
        "delay_spread_log_scale_decades", 1.0, ...
        "epsilon", 1e-12), ...
    "limits", struct( ...
        "max_candidates", 500, ...
        "retain_top_k", 5), ...
    "target", struct( ...
        "task", struct(), ...
        "region", "known"), ...
    "execution", struct( ...
        "order", "sequential", ...
        "continue_on_failure", true));
end
