function config = default_optimization_config(backend)
%DEFAULT_OPTIMIZATION_CONFIG Return the frozen Step 8 optimizer defaults.

arguments
    backend (1, 1) string = "mock"
end

generatorConfig = default_generator_config(backend);
config = struct( ...
    "schema_version", "v3.0-optimization-config.1", ...
    "requested_strategy", "auto", ...
    "generator_config", generatorConfig, ...
    "variables", struct( ...
        "DS_mu", discreteVariable( ...
            [-8.05, generatorConfig.model.DS_mu, -7.80], ...
            generatorConfig.model.DS_mu), ...
        "KF_mu", discreteVariable( ...
            [-0.80, generatorConfig.model.KF_mu, 0.00], ...
            generatorConfig.model.KF_mu), ...
        "num_clusters", discreteVariable( ...
            [8, generatorConfig.model.num_clusters, 16], ...
            generatorConfig.model.num_clusters)), ...
    "scoring", struct( ...
        "pdp_weight", 0.5, ...
        "delay_spread_weight", 0.5, ...
        "common_delay_bins", 128, ...
        "delay_window_margin", 1.05, ...
        "delay_spread_log_scale_decades", 1.0, ...
        "epsilon", 1e-12), ...
    "target", struct("task", struct(), "region", "known"), ...
    "limits", struct( ...
        "max_evaluations", 120, ...
        "max_consecutive_failures", 10, ...
        "retain_top_k", 5, ...
        "max_grid_candidates", 500), ...
    "sa", struct( ...
        "optimizer_seed", 8103, ...
        "initial_temperature", 0.10, ...
        "cooling_rate", 0.90, ...
        "minimum_temperature", 0.001, ...
        "no_improvement_limit", 30, ...
        "proposals_per_temperature", 0, ...
        "initial_step_fraction", 0.10, ...
        "minimum_step_fraction", 0.01), ...
    "auto", struct( ...
        "grid_candidate_caps", struct( ...
            "mock", 500, ...
            "lite_6gpcm", 125, ...
            "full_6gpcm", 16)), ...
    "execution", struct( ...
        "order", "sequential", ...
        "continue_on_failure", true));
end

function variable = discreteVariable(values, initial)
variable = struct( ...
    "type", "discrete", ...
    "values", double(values(:).'), ...
    "initial", double(initial), ...
    "step_fraction", 0.10);
end
