function result = run_grid_search(targetDataset, config, options)
%RUN_GRID_SEARCH Execute deterministic Cartesian-product parameter fitting.
%   Every candidate is generated through the Step 6 Generator Adapter and
%   scored against Step 5 characteristics from the known task region.

arguments
    targetDataset (1, 1) struct
    config (1, 1) struct
    options (1, 1) struct = struct()
end

startClock = tic;
startedUtc = utcNow();
events = repmat(emptyEvent(), 0, 1);
callbackWarnings = strings(0, 1);
normalized = config;
result = emptyResult(config, startedUtc);

try
    emitEvent("validate", 0.01, "Validating GridSearchConfig");
    [configReport, normalized] = validate_grid_search_config(config);
    result.validation.config = configReport;
    if isempty(fieldnames(normalized))
        result = failResult(result, configReport.errors, ...
            configReport.warnings);
        finalizeResult();
        return;
    end
    result.config = sanitize_grid_search_config(normalized);
    result.parameter_names = configReport.parameter_names;
    result.total_candidates = configReport.total_candidates;
    result.warnings = uniqueNonempty(configReport.warnings);
    if ~configReport.is_valid
        result = failResult(result, configReport.errors, ...
            configReport.warnings);
        finalizeResult();
        return;
    end
    if isCancelled()
        result = cancelledResult(result, ...
            "Grid Search was cancelled before target analysis.");
        finalizeResult();
        return;
    end

    emitEvent("target", 0.03, ...
        "Building target features from known task indices");
    target = build_channel_fit_target(targetDataset, ...
        normalized.target.task, normalized.scoring);
    result.target = publicTarget(target);
    result.validation.target_status = target.analysis.status;
    result.warnings = uniqueNonempty([ ...
        result.warnings; target.warnings(:)]);

    emitEvent("enumerate", 0.05, ...
        "Enumerating the complete Cartesian product");
    grid = enumerate_parameter_grid(normalized);
    candidateRecords = repmat(emptyCandidateRecord(), ...
        numel(grid), 1);
    retained = repmat(emptyRetainedCandidate(), 0, 1);
    completed = 0;
    succeeded = 0;
    failed = 0;

    for candidateIndex = 1:numel(grid)
        if isCancelled()
            result = cancelledResult(result, ...
                "Grid Search was cancelled before candidate " + ...
                grid(candidateIndex).id + ".");
            break;
        end

        candidateStart = tic;
        candidate = grid(candidateIndex);
        emitEvent("candidate", ...
            0.05 + 0.92 * (candidateIndex - 1) / numel(grid), ...
            sprintf("Evaluating %s (%d/%d)", candidate.id, ...
            candidateIndex, numel(grid)));
        generation = run_generator_adapter( ...
            candidate.generator_config, struct( ...
                "progress_callback", ...
                    @(event) forwardGenerationEvent( ...
                    candidateIndex, candidate.id, event), ...
                "cancel_check", @isCancelled));
        record = emptyCandidateRecord();
        record.index = candidate.index;
        record.id = candidate.id;
        record.parameters = candidate.parameters;
        record.runtime_s = toc(candidateStart);
        record.generation_status = generation.status;
        record.generation_outcome = generation.outcome;
        record.generation_manifest = generation.manifest;
        record.warnings = string(generation.warnings(:));

        if generation.cancelled || isCancelled()
            record.status = "WARNING";
            record.outcome = "CANCELLED";
            record.errors = string(generation.errors(:));
            completed = completed + 1;
            candidateRecords(completed) = record;
            result = cancelledResult(result, ...
                "Grid Search cancellation stopped at " + ...
                candidate.id + ".");
            break;
        elseif ~generation.success
            record.status = "FAIL";
            record.outcome = "FAILED";
            record.errors = string(generation.errors(:));
            failed = failed + 1;
            completed = completed + 1;
            candidateRecords(completed) = record;
            continue;
        end

        try
            fitScore = score_channel_fit( ...
                target, generation.dataset, normalized.scoring);
        catch scoreException
            fitScore = struct( ...
                "success", false, ...
                "status", "FAIL", ...
                "total", Inf, ...
                "components", struct( ...
                    "pdp", Inf, "delay_spread", Inf), ...
                "summary", struct(), ...
                "warnings", strings(0, 1), ...
                "errors", string(scoreException.identifier) + ...
                    " | " + string(scoreException.message));
        end
        record.warnings = uniqueNonempty([ ...
            record.warnings; string(fitScore.warnings(:))]);
        if ~fitScore.success
            record.status = "FAIL";
            record.outcome = "FAILED";
            record.errors = string(fitScore.errors(:));
            failed = failed + 1;
        else
            record.success = true;
            record.status = fitScore.status;
            record.outcome = "SUCCEEDED";
            record.total_score = fitScore.total;
            record.pdp_score = fitScore.components.pdp;
            record.delay_spread_score = ...
                fitScore.components.delay_spread;
            record.score_summary = fitScore.summary;
            succeeded = succeeded + 1;
            retained = retainCandidate(retained, candidate, ...
                generation, fitScore, normalized.limits.retain_top_k);
        end
        completed = completed + 1;
        candidateRecords(completed) = record;
        emitEvent("candidate_complete", ...
            0.05 + 0.92 * candidateIndex / numel(grid), ...
            sprintf("%s completed with score %.6f", ...
            candidate.id, record.total_score));
    end

    candidateRecords = candidateRecords(1:completed);
    [candidateRecords, successfulOrder] = rankCandidates( ...
        candidateRecords);
    retained = sortRetained(retained);
    result.ranking = candidateRecords;
    result.retained_candidates = retained;
    result.completed_candidates = completed;
    result.succeeded_candidates = succeeded;
    result.failed_candidates = failed;
    result.complete = completed == numel(grid) && ~result.cancelled;

    if ~isempty(retained)
        result.best = buildBest(retained(1), result.complete);
    end
    if result.cancelled
        result.success = false;
        result.formal_eligible = false;
    elseif succeeded == 0
        result = failResult(result, ...
            "All Grid Search candidates failed.", result.warnings);
    else
        result.success = true;
        result.outcome = "SUCCEEDED";
        result.errors = strings(0, 1);
        result.formal_eligible = result.complete && ...
            result.best.generation_result.formal_eligible;
        if failed > 0 || ~isempty(result.warnings) || ...
                any([candidateRecords(successfulOrder).status] == "WARNING")
            result.status = "WARNING";
        else
            result.status = "PASS";
        end
        emitEvent("complete", 1.0, ...
            "Grid Search completed with status " + result.status);
    end
catch exception
    result = failResult(result, ...
        string(exception.identifier) + " | " + ...
        string(exception.message), result.warnings);
end
finalizeResult();

    function forwardGenerationEvent(candidateIndex, candidateId, event)
        base = 0.05 + 0.92 * (candidateIndex - 1) / ...
            max(1, result.total_candidates);
        width = 0.92 / max(1, result.total_candidates);
        emitEvent("generate_" + string(event.phase), ...
            base + width * event.progress, ...
            candidateId + " · " + string(event.message));
    end

    function emitEvent(phase, progress, message)
        event = struct( ...
            "phase", string(phase), ...
            "progress", max(0, min(1, double(progress))), ...
            "message", string(message), ...
            "timestamp_utc", utcNow());
        events(end + 1, 1) = event;
        if isfield(options, "progress_callback") && ...
                ~isempty(options.progress_callback)
            try
                options.progress_callback(event);
            catch callbackException
                callbackWarnings(end + 1, 1) = ...
                    "Progress callback failed: " + ...
                    string(callbackException.message);
            end
        end
    end

    function cancelled = isCancelled()
        cancelled = false;
        if isfield(options, "cancel_check") && ...
                ~isempty(options.cancel_check)
            try
                cancelled = logical(options.cancel_check());
                if ~isscalar(cancelled)
                    cancelled = false;
                    callbackWarnings(end + 1, 1) = ...
                        "cancel_check returned a non-scalar value and was ignored.";
                end
            catch cancelException
                callbackWarnings(end + 1, 1) = ...
                    "cancel_check failed and was ignored: " + ...
                    string(cancelException.message);
                cancelled = false;
            end
        end
    end

    function finalizeResult()
        result.warnings = uniqueNonempty([ ...
            result.warnings; callbackWarnings]);
        if result.success && ~isempty(result.warnings)
            result.status = "WARNING";
        end
        result.events = events;
        result.runtime.started_utc = startedUtc;
        result.runtime.finished_utc = utcNow();
        result.runtime.elapsed_s = toc(startClock);
        result.manifest = buildManifest(result, normalized);
    end
end

function result = emptyResult(config, startedUtc)
result = struct( ...
    "schema_version", "v3.0-grid-search-result.1", ...
    "status", "FAIL", ...
    "outcome", "FAILED", ...
    "success", false, ...
    "complete", false, ...
    "cancelled", false, ...
    "formal_eligible", false, ...
    "config", safePublicConfig(config), ...
    "validation", struct(), ...
    "target", struct(), ...
    "parameter_names", strings(0, 1), ...
    "total_candidates", 0, ...
    "completed_candidates", 0, ...
    "succeeded_candidates", 0, ...
    "failed_candidates", 0, ...
    "ranking", repmat(emptyCandidateRecord(), 0, 1), ...
    "retained_candidates", ...
        repmat(emptyRetainedCandidate(), 0, 1), ...
    "best", struct(), ...
    "warnings", strings(0, 1), ...
    "errors", strings(0, 1), ...
    "events", repmat(emptyEvent(), 0, 1), ...
    "runtime", struct( ...
        "started_utc", startedUtc, ...
        "finished_utc", "", ...
        "elapsed_s", NaN), ...
    "manifest", struct());
end

function record = emptyCandidateRecord()
record = struct( ...
    "rank", NaN, ...
    "index", 0, ...
    "id", "", ...
    "success", false, ...
    "status", "FAIL", ...
    "outcome", "FAILED", ...
    "parameters", struct(), ...
    "total_score", Inf, ...
    "pdp_score", Inf, ...
    "delay_spread_score", Inf, ...
    "runtime_s", NaN, ...
    "generation_status", "", ...
    "generation_outcome", "", ...
    "generation_manifest", struct(), ...
    "score_summary", struct(), ...
    "warnings", strings(0, 1), ...
    "errors", strings(0, 1));
end

function retained = emptyRetainedCandidate()
retained = struct( ...
    "candidate_index", 0, ...
    "id", "", ...
    "parameters", struct(), ...
    "total_score", Inf, ...
    "generation_result", struct(), ...
    "score", struct());
end

function retained = retainCandidate(retained, candidate, generation, ...
        fitScore, topK)
entry = struct( ...
    "candidate_index", candidate.index, ...
    "id", candidate.id, ...
    "parameters", candidate.parameters, ...
    "total_score", fitScore.total, ...
    "generation_result", generation, ...
    "score", fitScore);
retained(end + 1, 1) = entry;
retained = sortRetained(retained);
if numel(retained) > topK
    retained = retained(1:topK);
end
end

function retained = sortRetained(retained)
if isempty(retained)
    return;
end
keys = [[retained.total_score].', [retained.candidate_index].'];
[~, order] = sortrows(keys, [1, 2]);
retained = retained(order);
end

function [records, successfulOrder] = rankCandidates(records)
if isempty(records)
    successfulOrder = zeros(0, 1);
    return;
end
success = [records.success].';
score = [records.total_score].';
index = [records.index].';
keys = [~success, score, index];
[~, order] = sortrows(keys, [1, 2, 3]);
records = records(order);
successfulOrder = find([records.success]);
for rank = 1:numel(successfulOrder)
    records(successfulOrder(rank)).rank = rank;
end
end

function best = buildBest(retained, complete)
best = struct( ...
    "candidate_index", retained.candidate_index, ...
    "id", retained.id, ...
    "parameters", retained.parameters, ...
    "total_score", retained.total_score, ...
    "component_scores", retained.score.components, ...
    "generation_result", retained.generation_result, ...
    "score", retained.score, ...
    "provisional", ~complete);
end

function result = failResult(result, errors, warnings)
result.status = "FAIL";
result.outcome = "FAILED";
result.success = false;
result.cancelled = false;
result.formal_eligible = false;
result.errors = uniqueNonempty(string(errors(:)));
result.warnings = uniqueNonempty(string(warnings(:)));
end

function result = cancelledResult(result, message)
result.status = "WARNING";
result.outcome = "CANCELLED";
result.success = false;
result.complete = false;
result.cancelled = true;
result.formal_eligible = false;
result.errors = strings(0, 1);
result.warnings = uniqueNonempty([result.warnings; string(message)]);
end

function public = publicTarget(target)
public = rmfield(target, "analysis");
end

function public = safePublicConfig(config)
if isstruct(config) && isscalar(config) && ...
        isfield(config, "generator_config")
    public = sanitize_grid_search_config(config);
else
    public = struct();
end
end

function manifest = buildManifest(result, normalized)
manifest = struct( ...
    "schema_version", "v3.0-grid-search-manifest.1", ...
    "search_api_version", "v3.0-step7.1", ...
    "status", result.status, ...
    "outcome", result.outcome, ...
    "complete", result.complete, ...
    "formal_eligible", result.formal_eligible, ...
    "backend", safeBackend(normalized), ...
    "config", safePublicConfig(normalized), ...
    "target_summary", safeTargetSummary(result.target), ...
    "parameter_names", result.parameter_names, ...
    "total_candidates", result.total_candidates, ...
    "completed_candidates", result.completed_candidates, ...
    "succeeded_candidates", result.succeeded_candidates, ...
    "failed_candidates", result.failed_candidates, ...
    "best_candidate_id", safeBestField(result.best, "id", ""), ...
    "best_score", safeBestField(result.best, "total_score", Inf), ...
    "runtime", result.runtime, ...
    "warnings", result.warnings, ...
    "errors", result.errors);
end

function value = safeBackend(config)
value = "";
if isstruct(config) && isscalar(config) && ...
        isfield(config, "generator_config") && ...
        isstruct(config.generator_config) && ...
        isfield(config.generator_config, "backend")
    value = string(config.generator_config.backend);
end
end

function value = safeTargetSummary(target)
value = struct();
if isstruct(target) && isscalar(target) && isfield(target, "summary")
    value = target.summary;
end
end

function value = safeBestField(best, fieldName, fallback)
value = fallback;
if isstruct(best) && isscalar(best) && isfield(best, fieldName)
    value = best.(fieldName);
end
end

function values = uniqueNonempty(values)
values = string(values(:));
values = values(strlength(strtrim(values)) > 0);
values = unique(values, "stable");
end

function event = emptyEvent()
event = struct( ...
    "phase", "", ...
    "progress", 0, ...
    "message", "", ...
    "timestamp_utc", "");
end

function value = utcNow()
value = string(datetime("now", "TimeZone", "UTC", ...
    "Format", "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"));
end
