function result = run_stochastic_optimizer( ...
        targetDataset, config, method, options)
%RUN_STOCHASTIC_OPTIMIZER Shared engine for SA and Random Greedy.

arguments
    targetDataset (1, 1) struct
    config (1, 1) struct
    method (1, 1) string {mustBeMember(method, ["sa", "random_greedy"])}
    options (1, 1) struct = struct()
end

startClock = tic;
startedUtc = utcNow();
events = repmat(emptyEvent(), 0, 1);
callbackWarnings = strings(0, 1);
result = emptyResult(config, method, startedUtc);
normalized = config;

previousRng = rng;
rngCleanup = onCleanup(@() rng(previousRng));

try
    emitEvent("validate", 0.01, "Validating OptimizationConfig");
    [validation, normalized] = validate_optimization_config(config);
    result.validation = validation;
    if isempty(fieldnames(normalized))
        result = failResult(result, validation.errors);
        finalizeResult();
        return;
    end
    result.config = sanitize_optimization_config(normalized);
    result.parameter_names = validation.parameter_names;
    result.warnings = uniqueNonempty(validation.warnings);
    if ~validation.is_valid
        result = failResult(result, validation.errors);
        finalizeResult();
        return;
    end
    rng(normalized.sa.optimizer_seed, "twister");
    if isCancelled()
        result = cancelledResult(result, ...
            "Optimization was cancelled before target analysis.");
        finalizeResult();
        return;
    end

    emitEvent("target", 0.03, ...
        "Building target features from known task indices");
    target = build_channel_fit_target(targetDataset, ...
        normalized.target.task, normalized.scoring);
    result.target = rmfield(target, "analysis");
    result.warnings = uniqueNonempty([ ...
        result.warnings; target.warnings(:)]);

    cache = containers.Map("KeyType", "char", "ValueType", "any");
    names = validation.parameter_names;
    currentParameters = initialParameters(normalized, names);
    initialKey = candidateKey(currentParameters, names);
    emitEvent("initial", 0.04, "Evaluating the initial parameter set");
    initialEvaluation = evaluate_optimization_candidate( ...
        target, currentParameters, normalized, ...
        candidateOptions("initial"));
    cache(initialKey) = initialEvaluation;
    result.objective_evaluations = 1;
    result.total_proposals = 1;
    initialRecord = historyRecord(1, 1, currentParameters, ...
        initialEvaluation, false, true, initialEvaluation.success, ...
        initialEvaluation.success, 0, normalized.sa.initial_temperature, ...
        1, "initial");
    result.history = initialRecord;
    if ~initialEvaluation.success
        if initialEvaluation.outcome == "CANCELLED" || isCancelled()
            result = cancelledResult(result, ...
                "Optimization was cancelled during initial evaluation.");
        else
            result = failResult(result, ...
                "The initial parameter set could not be evaluated: " + ...
                strjoin(initialEvaluation.errors, " | "));
        end
        finalizeResult();
        return;
    end

    currentEvaluation = initialEvaluation;
    bestEvaluation = initialEvaluation;
    bestParameters = currentParameters;
    retained = retainCandidate( ...
        repmat(emptyRetained(), 0, 1), 1, currentParameters, ...
        initialEvaluation, normalized.limits.retain_top_k);
    temperature = normalized.sa.initial_temperature;
    noImprovement = 0;
    consecutiveFailures = 0;
    acceptedCount = 0;
    worseAcceptedCount = 0;
    level = 0;
    stopReason = "";
    maxProposals = max(100, 20 * normalized.limits.max_evaluations);

    while result.objective_evaluations < ...
            normalized.limits.max_evaluations && ...
            temperature > normalized.sa.minimum_temperature && ...
            noImprovement < normalized.sa.no_improvement_limit && ...
            consecutiveFailures < ...
                normalized.limits.max_consecutive_failures && ...
            result.total_proposals < maxProposals
        level = level + 1;
        levelAccepted = 0;
        levelSuccessful = 0;
        for localProposal = 1:normalized.sa.proposals_per_temperature
            if result.objective_evaluations >= ...
                    normalized.limits.max_evaluations || ...
                    noImprovement >= ...
                    normalized.sa.no_improvement_limit || ...
                    consecutiveFailures >= ...
                    normalized.limits.max_consecutive_failures || ...
                    result.total_proposals >= maxProposals
                break;
            end
            if isCancelled()
                result = cancelledResult(result, ...
                    "Optimization was cancelled during candidate proposals.");
                stopReason = "cancelled";
                break;
            end

            proposalParameters = proposeNeighbor( ...
                currentParameters, normalized, names, temperature);
            key = candidateKey(proposalParameters, names);
            result.total_proposals = result.total_proposals + 1;
            proposalIndex = result.total_proposals;
            cached = isKey(cache, key);
            if cached
                evaluation = cache(key);
            else
                progress = 0.05 + 0.92 * ...
                    result.objective_evaluations / ...
                    normalized.limits.max_evaluations;
                emitEvent("candidate", progress, sprintf( ...
                    "Evaluating proposal %d (objective call %d/%d)", ...
                    proposalIndex, result.objective_evaluations + 1, ...
                    normalized.limits.max_evaluations));
                evaluation = evaluate_optimization_candidate( ...
                    target, proposalParameters, normalized, ...
                    candidateOptions("candidate"));
                cache(key) = evaluation;
                result.objective_evaluations = ...
                    result.objective_evaluations + 1;
            end

            accepted = false;
            improved = false;
            acceptanceProbability = 0;
            delta = Inf;
            if evaluation.success
                consecutiveFailures = 0;
                levelSuccessful = levelSuccessful + 1;
                delta = evaluation.total_score - ...
                    currentEvaluation.total_score;
                if delta <= 0
                    acceptanceProbability = 1;
                    accepted = true;
                elseif method == "sa"
                    acceptanceProbability = ...
                        metropolis_acceptance_probability( ...
                            delta, temperature);
                    accepted = rand < acceptanceProbability;
                end
                if accepted
                    if delta > 0
                        worseAcceptedCount = worseAcceptedCount + 1;
                    end
                    currentParameters = proposalParameters;
                    currentEvaluation = evaluation;
                    acceptedCount = acceptedCount + 1;
                    levelAccepted = levelAccepted + 1;
                end
                if evaluation.total_score < bestEvaluation.total_score
                    bestEvaluation = evaluation;
                    bestParameters = proposalParameters;
                    improved = true;
                    noImprovement = 0;
                else
                    noImprovement = noImprovement + 1;
                end
                if ~cached
                    retained = retainCandidate(retained, proposalIndex, ...
                        proposalParameters, evaluation, ...
                        normalized.limits.retain_top_k);
                end
            else
                consecutiveFailures = consecutiveFailures + 1;
                noImprovement = noImprovement + 1;
                result.failed_evaluations = ...
                    result.failed_evaluations + double(~cached);
                result.warnings = uniqueNonempty([ ...
                    result.warnings; evaluation.warnings(:); ...
                    "Proposal " + proposalIndex + " failed: " + ...
                    strjoin(evaluation.errors, " | ")]);
            end

            record = historyRecord(proposalIndex, ...
                result.objective_evaluations, proposalParameters, ...
                evaluation, cached, accepted, improved, ...
                currentEvaluation.success, delta, temperature, ...
                acceptanceProbability, "proposal");
            record.current_score = currentEvaluation.total_score;
            record.best_score = bestEvaluation.total_score;
            record.temperature_level = level;
            result.history(end + 1, 1) = record;
            if evaluation.outcome == "CANCELLED" || isCancelled()
                result = cancelledResult(result, ...
                    "Optimization was cancelled by the generator.");
                stopReason = "cancelled";
                break;
            end
        end
        if result.cancelled
            break;
        end
        result.temperature_history(end + 1, 1) = struct( ...
            "level", level, ...
            "temperature", temperature, ...
            "successful_proposals", levelSuccessful, ...
            "accepted_proposals", levelAccepted, ...
            "acceptance_rate", levelAccepted / max(1, levelSuccessful), ...
            "best_score", bestEvaluation.total_score);
        temperature = temperature * normalized.sa.cooling_rate;
    end

    if strlength(stopReason) == 0
        if result.objective_evaluations >= ...
                normalized.limits.max_evaluations
            stopReason = "max_evaluations";
        elseif noImprovement >= normalized.sa.no_improvement_limit
            stopReason = "no_improvement_limit";
        elseif consecutiveFailures >= ...
                normalized.limits.max_consecutive_failures
            stopReason = "max_consecutive_failures";
        elseif temperature <= normalized.sa.minimum_temperature
            stopReason = "minimum_temperature";
        else
            stopReason = "max_proposals_safeguard";
        end
    end

    result.stop_reason = stopReason;
    result.final_temperature = temperature;
    result.accepted_proposals = acceptedCount;
    result.worse_accepted_proposals = worseAcceptedCount;
    result.acceptance_rate = acceptedCount / ...
        max(1, sum([result.history(2:end).success]));
    result.retained_candidates = sortRetained(retained);
    result.best = buildBest(bestParameters, bestEvaluation, ...
        result.cancelled);
    if ~result.cancelled
        result.complete = true;
        result.success = true;
        result.outcome = "SUCCEEDED";
        result.formal_eligible = ...
            bestEvaluation.generation_result.formal_eligible;
        if result.failed_evaluations > 0 || ...
                ~isempty(result.warnings)
            result.status = "WARNING";
        else
            result.status = "PASS";
        end
        emitEvent("complete", 1.0, ...
            "Optimization completed with " + stopReason);
    end
catch exception
    result = failResult(result, ...
        string(exception.identifier) + " | " + string(exception.message));
end
finalizeResult();
clear rngCleanup

    function nestedOptions = candidateOptions(phase)
        nestedOptions = struct( ...
            "cancel_check", @isCancelled, ...
            "progress_callback", @(event) forwardGeneration(phase, event));
    end

    function forwardGeneration(phase, event)
        emitEvent("generate_" + string(event.phase), ...
            0.05 + 0.92 * result.objective_evaluations / ...
            max(1, normalized.limits.max_evaluations), ...
            string(phase) + " | " + string(event.message));
    end

    function emitEvent(phase, progress, message)
        event = struct( ...
            "phase", string(phase), ...
            "progress", max(0, min(1, double(progress))), ...
            "message", string(message), ...
            "timestamp_utc", utcNow());
        events(end + 1, 1) = event;
        if isfield(options, "progress_callback") && ...
                ~isempty(options.progress_callback)
            try
                options.progress_callback(event);
            catch callbackException
                callbackWarnings(end + 1, 1) = ...
                    "Progress callback failed: " + ...
                    string(callbackException.message);
            end
        end
    end

    function cancelled = isCancelled()
        cancelled = false;
        if isfield(options, "cancel_check") && ...
                ~isempty(options.cancel_check)
            try
                cancelled = logical(options.cancel_check());
                if ~isscalar(cancelled)
                    cancelled = false;
                    callbackWarnings(end + 1, 1) = ...
                        "cancel_check returned a non-scalar value and was ignored.";
                end
            catch cancelException
                callbackWarnings(end + 1, 1) = ...
                    "cancel_check failed and was ignored: " + ...
                    string(cancelException.message);
            end
        end
    end

    function finalizeResult()
        result.warnings = uniqueNonempty([ ...
            result.warnings; callbackWarnings]);
        if result.success && ~isempty(result.warnings)
            result.status = "WARNING";
        end
        result.events = events;
        result.runtime.started_utc = startedUtc;
        result.runtime.finished_utc = utcNow();
        result.runtime.elapsed_s = toc(startClock);
        result.manifest = buildManifest(result, normalized);
    end
end

function parameters = initialParameters(config, names)
parameters = struct();
for index = 1:numel(names)
    name = names(index);
    parameters.(name) = config.variables.(name).initial;
end
end

function proposal = proposeNeighbor(current, config, names, temperature)
proposal = current;
temperatureRatio = max(0, min(1, ...
    temperature / config.sa.initial_temperature));
for index = 1:numel(names)
    name = names(index);
    variable = config.variables.(name);
    stepFraction = max(config.sa.minimum_step_fraction, ...
        variable.step_fraction * temperatureRatio);
    switch string(variable.type)
        case "continuous"
            span = variable.upper - variable.lower;
            value = current.(name) + randn * span * stepFraction;
            proposal.(name) = ...
                min(variable.upper, max(variable.lower, value));
        case "integer"
            span = variable.upper - variable.lower;
            value = round(current.(name) + ...
                randn * max(1, span * stepFraction));
            proposal.(name) = ...
                min(variable.upper, max(variable.lower, value));
        case "discrete"
            values = variable.values;
            [~, currentIndex] = min(abs(values - current.(name)));
            moveProbability = min(1, max(0.10, 5 * stepFraction));
            indexStep = 0;
            if rand < moveProbability
                direction = sign(randn);
                if direction == 0
                    direction = 1;
                end
                distance = max(1, round(abs(randn) * ...
                    (numel(values) - 1) * stepFraction));
                indexStep = direction * distance;
            end
            proposedIndex = min(numel(values), ...
                max(1, currentIndex + indexStep));
            proposal.(name) = values(proposedIndex);
    end
end
end

function key = candidateKey(parameters, names)
parts = strings(numel(names), 1);
for index = 1:numel(names)
    name = names(index);
    parts(index) = name + "=" + ...
        string(sprintf("%.17g", parameters.(name)));
end
key = char(strjoin(parts, "|"));
end

function record = historyRecord(proposalIndex, evaluationCount, ...
        parameters, evaluation, cached, accepted, improved, ...
        hasCurrent, delta, temperature, acceptanceProbability, phase)
record = struct( ...
    "proposal_index", proposalIndex, ...
    "objective_evaluation_count", evaluationCount, ...
    "phase", string(phase), ...
    "parameters", parameters, ...
    "cached", logical(cached), ...
    "success", logical(evaluation.success), ...
    "status", string(evaluation.status), ...
    "outcome", string(evaluation.outcome), ...
    "total_score", double(evaluation.total_score), ...
    "pdp_score", double(evaluation.pdp_score), ...
    "delay_spread_score", double(evaluation.delay_spread_score), ...
    "delta_from_current", double(delta), ...
    "accepted", logical(accepted), ...
    "improved_best", logical(improved), ...
    "acceptance_probability", double(acceptanceProbability), ...
    "temperature", double(temperature), ...
    "temperature_level", 0, ...
    "current_score", conditionalScore(hasCurrent, evaluation.total_score), ...
    "best_score", conditionalScore(hasCurrent, evaluation.total_score), ...
    "runtime_s", double(evaluation.runtime_s), ...
    "generation_manifest", safeGenerationManifest(evaluation), ...
    "warnings", string(evaluation.warnings(:)), ...
    "errors", string(evaluation.errors(:)));
end

function score = conditionalScore(condition, value)
score = Inf;
if condition
    score = value;
end
end

function manifest = safeGenerationManifest(evaluation)
manifest = struct();
if isstruct(evaluation.generation_result) && ...
        isfield(evaluation.generation_result, "manifest")
    manifest = evaluation.generation_result.manifest;
end
end

function retained = retainCandidate(retained, proposalIndex, ...
        parameters, evaluation, topK)
entry = struct( ...
    "proposal_index", proposalIndex, ...
    "parameters", parameters, ...
    "total_score", evaluation.total_score, ...
    "generation_result", evaluation.generation_result, ...
    "score", evaluation.score);
retained(end + 1, 1) = entry;
retained = sortRetained(retained);
if numel(retained) > topK
    retained = retained(1:topK);
end
end

function retained = sortRetained(retained)
if isempty(retained)
    return;
end
keys = [[retained.total_score].', [retained.proposal_index].'];
[~, order] = sortrows(keys, [1, 2]);
retained = retained(order);
end

function entry = emptyRetained()
entry = struct( ...
    "proposal_index", 0, ...
    "parameters", struct(), ...
    "total_score", Inf, ...
    "generation_result", struct(), ...
    "score", struct());
end

function best = buildBest(parameters, evaluation, provisional)
best = struct( ...
    "parameters", parameters, ...
    "total_score", evaluation.total_score, ...
    "component_scores", struct( ...
        "pdp", evaluation.pdp_score, ...
        "delay_spread", evaluation.delay_spread_score), ...
    "generation_result", evaluation.generation_result, ...
    "score", evaluation.score, ...
    "provisional", logical(provisional));
end

function result = emptyResult(config, method, startedUtc)
result = struct( ...
    "schema_version", "v3.0-stochastic-optimization-result.1", ...
    "method", method, ...
    "status", "FAIL", ...
    "outcome", "FAILED", ...
    "success", false, ...
    "complete", false, ...
    "cancelled", false, ...
    "formal_eligible", false, ...
    "config", safeConfig(config), ...
    "validation", struct(), ...
    "target", struct(), ...
    "parameter_names", strings(0, 1), ...
    "objective_evaluations", 0, ...
    "failed_evaluations", 0, ...
    "total_proposals", 0, ...
    "accepted_proposals", 0, ...
    "worse_accepted_proposals", 0, ...
    "acceptance_rate", 0, ...
    "final_temperature", NaN, ...
    "stop_reason", "", ...
    "history", repmat(emptyHistory(), 0, 1), ...
    "temperature_history", repmat(emptyTemperature(), 0, 1), ...
    "retained_candidates", repmat(emptyRetained(), 0, 1), ...
    "best", struct(), ...
    "warnings", strings(0, 1), ...
    "errors", strings(0, 1), ...
    "events", repmat(emptyEvent(), 0, 1), ...
    "runtime", struct( ...
        "started_utc", startedUtc, ...
        "finished_utc", "", ...
        "elapsed_s", NaN), ...
    "manifest", struct());
end

function record = emptyHistory()
emptyEvaluation = struct( ...
    "success", false, "status", "", "outcome", "", ...
    "total_score", Inf, "pdp_score", Inf, ...
    "delay_spread_score", Inf, "runtime_s", NaN, ...
    "generation_result", struct(), ...
    "warnings", strings(0, 1), "errors", strings(0, 1));
record = historyRecord(0, 0, struct(), emptyEvaluation, ...
    false, false, false, false, Inf, NaN, 0, "");
end

function entry = emptyTemperature()
entry = struct( ...
    "level", 0, ...
    "temperature", NaN, ...
    "successful_proposals", 0, ...
    "accepted_proposals", 0, ...
    "acceptance_rate", 0, ...
    "best_score", Inf);
end

function result = failResult(result, errors)
result.status = "FAIL";
result.outcome = "FAILED";
result.success = false;
result.complete = false;
result.cancelled = false;
result.formal_eligible = false;
result.errors = uniqueNonempty(string(errors(:)));
end

function result = cancelledResult(result, message)
result.status = "WARNING";
result.outcome = "CANCELLED";
result.success = false;
result.complete = false;
result.cancelled = true;
result.formal_eligible = false;
result.errors = strings(0, 1);
result.warnings = uniqueNonempty([result.warnings; string(message)]);
end

function public = safeConfig(config)
if isstruct(config) && isscalar(config) && ...
        isfield(config, "generator_config")
    public = sanitize_optimization_config(config);
else
    public = struct();
end
end

function manifest = buildManifest(result, normalized)
manifest = struct( ...
    "schema_version", "v3.0-stochastic-optimization-manifest.1", ...
    "optimizer_api_version", "v3.0-step8.1", ...
    "method", result.method, ...
    "status", result.status, ...
    "outcome", result.outcome, ...
    "complete", result.complete, ...
    "formal_eligible", result.formal_eligible, ...
    "backend", safeBackend(normalized), ...
    "generator_seed", safeGeneratorSeed(normalized), ...
    "optimizer_seed", safeOptimizerSeed(normalized), ...
    "parameter_names", result.parameter_names, ...
    "objective_evaluations", result.objective_evaluations, ...
    "failed_evaluations", result.failed_evaluations, ...
    "total_proposals", result.total_proposals, ...
    "accepted_proposals", result.accepted_proposals, ...
    "worse_accepted_proposals", result.worse_accepted_proposals, ...
    "stop_reason", result.stop_reason, ...
    "best_score", safeBestScore(result.best), ...
    "config", safeConfig(normalized), ...
    "runtime", result.runtime, ...
    "warnings", result.warnings, ...
    "errors", result.errors);
end

function value = safeBackend(config)
value = "";
if isstruct(config) && isfield(config, "generator_config") && ...
        isfield(config.generator_config, "backend")
    value = string(config.generator_config.backend);
end
end

function value = safeGeneratorSeed(config)
value = NaN;
if isstruct(config) && isfield(config, "generator_config") && ...
        isfield(config.generator_config, "random_seed")
    value = config.generator_config.random_seed;
end
end

function value = safeOptimizerSeed(config)
value = NaN;
if isstruct(config) && isfield(config, "sa") && ...
        isfield(config.sa, "optimizer_seed")
    value = config.sa.optimizer_seed;
end
end

function value = safeBestScore(best)
value = Inf;
if isstruct(best) && isscalar(best) && isfield(best, "total_score")
    value = best.total_score;
end
end

function values = uniqueNonempty(values)
values = string(values(:));
values = values(strlength(strtrim(values)) > 0);
values = unique(values, "stable");
end

function event = emptyEvent()
event = struct( ...
    "phase", "", ...
    "progress", 0, ...
    "message", "", ...
    "timestamp_utc", "");
end

function value = utcNow()
value = string(datetime("now", "TimeZone", "UTC", ...
    "Format", "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"));
end
