function result = run_parameter_optimization(targetDataset, config, options)
%RUN_PARAMETER_OPTIMIZATION Unified Step 8 auto/grid/sa entry point.

arguments
    targetDataset (1, 1) struct
    config (1, 1) struct
    options (1, 1) struct = struct()
end

started = tic;
startedUtc = utcNow();
result = emptyResult(config, startedUtc);
[validation, normalized] = validate_optimization_config(config);
result.validation = validation;
if isempty(fieldnames(normalized))
    result.errors = validation.errors;
    result.runtime = finishRuntime(startedUtc, started);
    return;
end
result.config = sanitize_optimization_config(normalized);
result.warnings = validation.warnings;
if ~validation.is_valid
    result.errors = validation.errors;
    result.runtime = finishRuntime(startedUtc, started);
    return;
end

selection = select_optimization_strategy(normalized);
result.requested_strategy = selection.requested_strategy;
result.selected_strategy = selection.selected_strategy;
result.selection_source = selection.source;
result.selection_reason_code = selection.reason_code;
result.selection_reason = selection.reason;
result.selection = selection;

if selection.selected_strategy == "grid"
    gridConfig = toGridConfig(normalized);
    details = run_grid_search(targetDataset, gridConfig, options);
else
    details = run_simulated_annealing(targetDataset, normalized, options);
end

result.details = details;
result.status = details.status;
result.outcome = details.outcome;
result.success = details.success;
result.complete = details.complete;
result.cancelled = details.cancelled;
result.formal_eligible = details.formal_eligible;
result.best = details.best;
result.retained_candidates = details.retained_candidates;
result.warnings = uniqueNonempty([ ...
    result.warnings; details.warnings(:)]);
result.errors = string(details.errors(:));
result.counts = resultCounts(details, selection.selected_strategy);
result.runtime = finishRuntime(startedUtc, started);
result.manifest = struct( ...
    "schema_version", "v3.0-parameter-optimization-manifest.1", ...
    "optimizer_api_version", "v3.0-step8.1", ...
    "requested_strategy", result.requested_strategy, ...
    "selected_strategy", result.selected_strategy, ...
    "selection_source", result.selection_source, ...
    "selection_reason_code", result.selection_reason_code, ...
    "selection_reason", result.selection_reason, ...
    "status", result.status, ...
    "outcome", result.outcome, ...
    "complete", result.complete, ...
    "formal_eligible", result.formal_eligible, ...
    "counts", result.counts, ...
    "best_score", safeBestScore(result.best), ...
    "config", result.config, ...
    "runtime", result.runtime, ...
    "warnings", result.warnings, ...
    "errors", result.errors);
end

function gridConfig = toGridConfig(config)
gridConfig = default_grid_search_config(config.generator_config.backend);
gridConfig.generator_config = config.generator_config;
gridConfig.scoring = config.scoring;
gridConfig.target = config.target;
gridConfig.execution = config.execution;
gridConfig.limits.max_candidates = config.limits.max_grid_candidates;
gridConfig.limits.retain_top_k = config.limits.retain_top_k;
gridConfig.parameter_space = struct();
names = string(fieldnames(config.variables));
for index = 1:numel(names)
    name = names(index);
    descriptor = config.variables.(name);
    if string(descriptor.type) ~= "discrete"
        error("run_parameter_optimization:NonDiscreteGridVariable", ...
            "Grid Search variable %s is not discrete.", name);
    end
    gridConfig.parameter_space.(name) = descriptor.values;
end
end

function counts = resultCounts(details, strategy)
if strategy == "grid"
    counts = struct( ...
        "planned", details.total_candidates, ...
        "completed", details.completed_candidates, ...
        "succeeded", details.succeeded_candidates, ...
        "failed", details.failed_candidates, ...
        "proposals", details.completed_candidates, ...
        "objective_evaluations", details.completed_candidates);
else
    counts = struct( ...
        "planned", details.config.limits.max_evaluations, ...
        "completed", details.objective_evaluations, ...
        "succeeded", details.objective_evaluations - ...
            details.failed_evaluations, ...
        "failed", details.failed_evaluations, ...
        "proposals", details.total_proposals, ...
        "objective_evaluations", details.objective_evaluations);
end
end

function result = emptyResult(config, startedUtc)
result = struct( ...
    "schema_version", "v3.0-parameter-optimization-result.1", ...
    "status", "FAIL", ...
    "outcome", "FAILED", ...
    "success", false, ...
    "complete", false, ...
    "cancelled", false, ...
    "formal_eligible", false, ...
    "requested_strategy", "", ...
    "selected_strategy", "", ...
    "selection_source", "", ...
    "selection_reason_code", "", ...
    "selection_reason", "", ...
    "selection", struct(), ...
    "config", safeConfig(config), ...
    "validation", struct(), ...
    "counts", struct(), ...
    "best", struct(), ...
    "retained_candidates", struct([]), ...
    "details", struct(), ...
    "warnings", strings(0, 1), ...
    "errors", strings(0, 1), ...
    "runtime", struct( ...
        "started_utc", startedUtc, ...
        "finished_utc", "", ...
        "elapsed_s", NaN), ...
    "manifest", struct());
end

function public = safeConfig(config)
if isstruct(config) && isscalar(config) && ...
        isfield(config, "generator_config")
    public = sanitize_optimization_config(config);
else
    public = struct();
end
end

function runtime = finishRuntime(startedUtc, started)
runtime = struct( ...
    "started_utc", startedUtc, ...
    "finished_utc", utcNow(), ...
    "elapsed_s", toc(started));
end

function value = safeBestScore(best)
value = Inf;
if isstruct(best) && isscalar(best) && isfield(best, "total_score")
    value = best.total_score;
end
end

function values = uniqueNonempty(values)
values = string(values(:));
values = values(strlength(strtrim(values)) > 0);
values = unique(values, "stable");
end

function value = utcNow()
value = string(datetime("now", "TimeZone", "UTC", ...
    "Format", "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"));
end
