function mapping = default_mat_channel_mapping()
%DEFAULT_MAT_CHANNEL_MAPPING Explicit Step 14 MAT conversion contract.

mapping = struct( ...
    "schema_version", "v3.0-mat-conversion-mapping.1", ...
    "adapter", "generic_mat", ...
    "domain", "", ...
    "complex_variable", "", ...
    "real_variable", "", ...
    "imag_variable", "", ...
    "source_dimension_order", strings(1, 0), ...
    "delay_variable", "", ...
    "frequency_variable", "", ...
    "time_variable", "", ...
    "sample_index_variable", "", ...
    "position_variable", "", ...
    "delay_unit", "s", ...
    "frequency_unit", "Hz", ...
    "time_unit", "s", ...
    "position_unit", "m", ...
    "delay_bin_spacing_s", NaN, ...
    "center_frequency_hz", NaN, ...
    "subcarrier_spacing_hz", NaN, ...
    "snapshot_interval_s", NaN, ...
    "sample_semantics", "independent", ...
    "source_id", "", ...
    "advanced_mapping_confirmed", false);
end
