function manifest = create_v3_release_manifest(outputFile)
%CREATE_V3_RELEASE_MANIFEST Record a reproducible v3.0 RC environment.
%   A final clean manifest must be regenerated after the approved PR is
%   merged. This function never creates tags or changes Git state.

arguments
    outputFile (1, 1) string = ""
end
repoRoot = string(fileparts(fileparts(mfilename("fullpath"))));
if outputFile == ""
    outputRoot = fullfile(repoRoot, "review_data", "step14");
    if ~isfolder(outputRoot), mkdir(outputRoot); end
    outputFile = fullfile(outputRoot, "v3_0_rc_baseline_manifest.json");
end
if isfile(outputFile)
    error("create_v3_release_manifest:OutputExists", ...
        "Refusing to overwrite an existing manifest: %s", outputFile);
end

[revisionStatus, revision] = system("git rev-parse HEAD");
[branchStatus, branch] = system("git branch --show-current");
[dirtyStatus, dirtyText] = system("git status --porcelain");
[pythonStatus, pythonText] = system("python --version");
if revisionStatus ~= 0, revision = "unavailable"; end
if branchStatus ~= 0, branch = "unavailable"; end
if dirtyStatus ~= 0, dirtyText = "status unavailable"; end
if pythonStatus ~= 0, pythonText = "unavailable"; end

keyRelativeFiles = [ ...
    "VERSION"; ...
    "ChannelSimulator.m"; ...
    "ChannelBenchmark.m"; ...
    "core/contracts/write_channel_dataset_hdf5.m"; ...
    "core/ingestion/convert_channel_source_to_v3.m"; ...
    "core/ingestion/convert_mat_channel_to_v3_hdf5.m"; ...
    "core/prediction/create_calibrated_persistence_prediction.m"; ...
    "core/benchmark/run_channel_benchmark.m"];
hashes = repmat(struct("path", "", "sha256", ""), numel(keyRelativeFiles), 1);
for index = 1:numel(keyRelativeFiles)
    filePath = fullfile(repoRoot, keyRelativeFiles(index));
    hashes(index).path = keyRelativeFiles(index);
    if isfile(filePath)
        hashes(index).sha256 = compute_benchmark_file_sha256(filePath);
    else
        hashes(index).sha256 = "missing";
    end
end

externalRoot = fullfile(fileparts(repoRoot), ...
    "ChanAI-Pulse-v3-step11abc-assets", "full6gpcm", "source");
externalEntry = fullfile(externalRoot, "@channel_model", "channel_model.m");
external = struct( ...
    "configured_path", externalRoot, ...
    "available", isfile(externalEntry), ...
    "core_redistributed_in_repository", false, ...
    "entry_sha256", "not_available");
if external.available
    external.entry_sha256 = compute_benchmark_file_sha256(externalEntry);
end

manifest = struct( ...
    "schema_version", "v3.0-release-baseline.1", ...
    "product_version", strtrim(string(fileread(fullfile(repoRoot, "VERSION")))), ...
    "created_utc", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ss'Z'")), ...
    "git_revision", strtrim(string(revision)), ...
    "git_branch", strtrim(string(branch)), ...
    "git_dirty", strlength(strtrim(string(dirtyText))) > 0, ...
    "git_status_porcelain", splitlines(strtrim(string(dirtyText))), ...
    "matlab_release", string(version("-release")), ...
    "matlab_version", string(version), ...
    "python_version", strtrim(string(pythonText)), ...
    "operating_system", string(system_dependent("getos")), ...
    "contracts", struct( ...
        "channel_dataset", "v3.0-data-contract.1", ...
        "mat_inspection", "v3.0-mat-inspection.1", ...
        "mat_mapping", "v3.0-mat-conversion-mapping.1", ...
        "mat_manifest", "v3.0-mat-conversion-manifest.1", ...
        "prediction_result", "v3.0-prediction-result.1", ...
        "benchmark", "v3.0-benchmark-result.1"), ...
    "frozen_product_model", struct( ...
        "type", "persistence", ...
        "parameter_bundles", ["P6", "P8"], ...
        "target_ground_truth_read", false, ...
        "neural_model_auto_admission", "deferred_to_v3.1"), ...
    "external_full_6gpcm", external, ...
    "key_file_hashes", hashes, ...
    "finalization_note", ...
        "Regenerate after the approved Step 14 PR is merged; final release/tag requires git_dirty=false and owner approval.");

[folder, ~, ~] = fileparts(outputFile);
if folder ~= "" && ~isfolder(folder), mkdir(folder); end
identifier = fopen(outputFile, "wt", "n", "UTF-8");
if identifier < 0
    error("create_v3_release_manifest:WriteFailed", ...
        "Cannot create release manifest: %s", outputFile);
end
cleanup = onCleanup(@() fclose(identifier)); %#ok<NASGU>
fprintf(identifier, "%s\n", jsonencode(manifest, "PrettyPrint", true));
fprintf("v3.0 RC baseline manifest: %s\n", outputFile);
end
