function report = run_v31_4_local_model_study(assetRoot, options)
%RUN_V31_4_LOCAL_MODEL_STUDY Orchestrate the complete local v3.1-4 study.

arguments
    assetRoot (1, 1) string = ""
    options.ExperimentId (1, 1) string = ""
    options.PythonExecutable (1, 1) string = ""
    options.Device (1, 1) string {mustBeMember(options.Device, ...
        ["auto", "cpu", "cuda"])} = "auto"
    options.MaxGeneratorPairsPerTask (1, 1) double ...
        {mustBeInteger, mustBePositive} = 5
end
repositoryRoot = string(fileparts(fileparts(mfilename("fullpath"))));
addpath(genpath(fullfile(repositoryRoot, "core")));
if strlength(assetRoot) == 0
    assetRoot = fullfile(fileparts(repositoryRoot), ...
        "ChanAI-Pulse-v3.1-assets");
end
if strlength(options.PythonExecutable) == 0
    options.PythonExecutable = fullfile(assetRoot, "runtime", "v31_4", ...
        ".venv", "Scripts", "python.exe");
end
if ~isfile(options.PythonExecutable)
    error("run_v31_4_local_model_study:PythonMissing", ...
        "Python executable not found: %s", options.PythonExecutable);
end
corpusRoot = fullfile(assetRoot, "corpora", ...
    "chanaipulse-v3.1-corpus.1");
corpusManifest = fullfile(corpusRoot, "corpus_manifest.json");
dataDirectory = fullfile(corpusRoot, "predictor_bundles");
configuration = jsondecode(fileread(fullfile(repositoryRoot, ...
    "configs", "v31_4_model_study.json")));
record = create_experiment(assetRoot, ...
    ExperimentId=options.ExperimentId, ...
    DatasetManifestPath=corpusManifest, ...
    ExperimentConfig=configuration, ...
    CodeRoot=repositoryRoot);
record = update_experiment_status(record.root, "running", ...
    "Running validation-only model search and multi-seed comparison.");
studyRoot = fullfile(record.root, "artifacts", "model_study");
script = fullfile(repositoryRoot, "tools", "python", ...
    "run_v31_4_model_study.py");
studyManifest = fullfile(studyRoot, "v31_4_model_study_manifest.json");
gateManifest = fullfile(studyRoot, "full_6gpcm_gate", ...
    "v31_4_full_6gpcm_gate.json");
testResults = fullfile(studyRoot, "v31_4_test_once_results.json");
try
    command = join([quote(options.PythonExecutable), quote(script), ...
        "study", "--data-directory", quote(dataDirectory), ...
        "--output-directory", quote(studyRoot), ...
        "--device", options.Device], " ");
    [status, output] = system(command);
    writeText(fullfile(record.root, "logs", "python_study.log"), output);
    if status ~= 0
        error("run_v31_4_local_model_study:StudyFailed", ...
            "Python model study failed with status %d.", status);
    end
    gateReport = run_v31_4_full_6gpcm_gate(studyRoot, ...
        MaxPairsPerTask=options.MaxGeneratorPairsPerTask);
    command = join([quote(options.PythonExecutable), quote(script), ...
        "finalize-test", "--study-manifest", quote(studyManifest), ...
        "--gate-manifest", quote(gateManifest), ...
        "--data-directory", quote(dataDirectory), ...
        "--device", options.Device], " ");
    [status, output] = system(command);
    writeText(fullfile(record.root, "logs", "python_test_once.log"), output);
    if status ~= 0
        error("run_v31_4_local_model_study:TestFailed", ...
            "Frozen one-time test failed with status %d.", status);
    end
    record = update_experiment_status(record.root, "completed", ...
        "Model choices frozen, Full 6GPCM validation gate passed, and test opened once.");
catch exception
    current = read_experiment(record.root);
    if string(current.status.status) == "running"
        update_experiment_status(record.root, "failed", string(exception.message));
    end
    rethrow(exception);
end
report = struct( ...
    "schema_version", "v3.1-4-local-run.1", ...
    "experiment_root", record.root, ...
    "study_manifest", studyManifest, ...
    "full_6gpcm_gate_manifest", gateManifest, ...
    "test_once_results", testResults, ...
    "gate_report", gateReport, ...
    "status", record.status.status);
end

function value = quote(value)
if contains(string(value), '"')
    error("run_v31_4_local_model_study:InvalidPath", ...
        "Command paths cannot contain a double quote.");
end
value = '"' + string(value) + '"';
end

function writeText(path, value)
if isfile(path)
    error("run_v31_4_local_model_study:LogExists", ...
        "Refusing to overwrite %s", path);
end
fid = fopen(path, "w");
if fid < 0
    error("run_v31_4_local_model_study:CannotWrite", ...
        "Cannot create %s", path);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s", value);
end
