function report = run_v31_4_full_6gpcm_gate(experimentRoot, options)
%RUN_V31_4_FULL_6GPCM_GATE Validate frozen model pairs with bundled Full 6GPCM.

arguments
    experimentRoot (1, 1) string
    options.MaxPairsPerTask (1, 1) double {mustBeInteger, mustBePositive} = 5
end
repositoryRoot = string(fileparts(fileparts(mfilename("fullpath"))));
addpath(genpath(fullfile(repositoryRoot, "core")));
installation = resolve_full_6gpcm_root(UseEnvironment=false);
if ~installation.is_present || ~installation.has_public_api
    error("run_v31_4_full_6gpcm_gate:FullEngineUnavailable", ...
        "The bundled Full 6GPCM public API is unavailable.");
end
pairRoot = fullfile(experimentRoot, "generator_gate");
outputRoot = fullfile(experimentRoot, "full_6gpcm_gate");
if isfolder(outputRoot) || isfile(outputRoot)
    error("run_v31_4_full_6gpcm_gate:OutputExists", ...
        "Refusing to overwrite an existing gate result: %s", outputRoot);
end
before = hash_full_6gpcm_tree(installation.root);
report = run_step11abc_end_to_end_validation( ...
    installation.root, pairRoot, outputRoot, ...
    Mode="validation", MaxPairsPerBundle=options.MaxPairsPerTask);
after = hash_full_6gpcm_tree(installation.root);
if before.aggregate_sha256 ~= after.aggregate_sha256
    error("run_v31_4_full_6gpcm_gate:CoreChanged", ...
        "The Full 6GPCM tree changed during the validation gate.");
end
numericColumns = ["mean_parameter_nrmse", "mean_pdp_nrmse", ...
    "mean_rms_delay_abs_error_s", ...
    "mean_generated_delay_overflow_power_fraction"];
for column = numericColumns
    if ~ismember(column, string(report.summary.Properties.VariableNames)) || ...
            any(~isfinite(report.summary.(column)))
        error("run_v31_4_full_6gpcm_gate:InvalidMetric", ...
            "The validation gate produced a missing or non-finite %s metric.", column);
    end
end
gate = struct( ...
    "schema_version", "v3.1-4-full-6gpcm-validation-gate.1", ...
    "created_utc", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ss'Z'")), ...
    "evaluation_partition", "validation", ...
    "test_partition_used", false, ...
    "max_pairs_per_task", options.MaxPairsPerTask, ...
    "full_6gpcm_root_source", installation.source, ...
    "full_6gpcm_tree_sha256_before", before.aggregate_sha256, ...
    "full_6gpcm_tree_sha256_after", after.aggregate_sha256, ...
    "full_6gpcm_core_modified", false, ...
    "passed", true, ...
    "pass_definition", ...
        "All frozen validation pairs generated, scored finitely, and preserved the Full 6GPCM tree hash.", ...
    "selection_manifest", string(report.selection_manifest));
gatePath = fullfile(outputRoot, "v31_4_full_6gpcm_gate.json");
if isfile(gatePath)
    error("run_v31_4_full_6gpcm_gate:OutputExists", ...
        "Refusing to overwrite %s", gatePath);
end
fid = fopen(gatePath, "w");
if fid < 0
    error("run_v31_4_full_6gpcm_gate:CannotWrite", ...
        "Cannot create %s", gatePath);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "%s\n", jsonencode(gate, PrettyPrint=true));
end
