function registry = build_channel_plot_registry(classification, metrics)
%BUILD_CHANNEL_PLOT_REGISTRY Register Step 5 plots and capability reasons.

arguments
    classification (1, 1) string
    metrics (1, 1) struct
end

specifications = {
    "power", "功率", "基础", false;
    "pdp", "PDP", "基础", false;
    "frequency_autocorrelation", "频率自相关", "基础", false;
    "delay_spread_cdf", "时延扩展 CDF", "基础", false;
    "angular_power_spectrum", "角度功率谱", "空间与角度", false;
    "spatial_correlation", "空间相关", "空间与角度", false;
    "angular_spread_cdf", "角度扩展 CDF", "空间与角度", false;
    "doppler_power_spectrum", "多普勒功率谱", "时间与多普勒", false;
    "time_autocorrelation", "时间自相关", "时间与多普勒", false;
    "doppler_spread_cdf", "多普勒扩展 CDF", "时间与多普勒", false;
    "delay_sample_heatmap", "时延—样本热力图", "附加", true
    };

idealIds = idealStandardIds(classification);
entries = repmat(struct( ...
    "id", "", ...
    "title_zh", "", ...
    "category", "", ...
    "available", false, ...
    "reason", "", ...
    "is_standard", false, ...
    "is_additional", false, ...
    "kind", ""), size(specifications, 1), 1);

for index = 1:size(specifications, 1)
    id = string(specifications{index, 1});
    metric = metrics.(id);
    entries(index) = struct( ...
        "id", id, ...
        "title_zh", string(specifications{index, 2}), ...
        "category", string(specifications{index, 3}), ...
        "available", logical(metric.available), ...
        "reason", string(metric.reason), ...
        "is_standard", any(idealIds == id), ...
        "is_additional", logical(specifications{index, 4}), ...
        "kind", string(metric.kind));
end

standardMask = [entries.is_standard].';
availableMask = [entries.available].';
additionalMask = [entries.is_additional].';
registry = struct( ...
    "classification", classification, ...
    "is_standard_classification", ~isempty(idealIds), ...
    "ideal_standard_ids", idealIds, ...
    "ideal_standard_plot_count", numel(idealIds), ...
    "available_plot_count", sum(availableMask), ...
    "available_standard_plot_count", ...
        sum(standardMask & availableMask), ...
    "available_additional_plot_count", ...
        sum(additionalMask & availableMask), ...
    "entries", entries);
end

function ids = idealStandardIds(classification)
switch classification
    case "narrowband_static_siso"
        ids = "power";
    case "wideband_static_siso"
        ids = ["pdp", "frequency_autocorrelation", ...
            "delay_spread_cdf"];
    case "wideband_static_mimo"
        ids = ["pdp", "frequency_autocorrelation", ...
            "delay_spread_cdf", "angular_power_spectrum", ...
            "spatial_correlation", "angular_spread_cdf"];
    case "wideband_dynamic_mimo"
        ids = ["pdp", "frequency_autocorrelation", ...
            "delay_spread_cdf", "angular_power_spectrum", ...
            "spatial_correlation", "angular_spread_cdf", ...
            "doppler_power_spectrum", "time_autocorrelation", ...
            "doppler_spread_cdf"];
    otherwise
        ids = strings(0, 1);
end
end
