function fixture = create_step9_standard_fixture()
%CREATE_STEP9_STANDARD_FIXTURE Create small deterministic public review data.
%   This is a technical fixture, not scientific evidence or measured data.

config = default_predictor_data_config();
groupCount = 10;
rowsPerGroup = 28;
rowCount = groupCount * rowsPerGroup;
globalIndex = (1:rowCount).';
groupId = strings(rowCount, 1);
sampleIndex = zeros(rowCount, 1);
values = zeros(rowCount, 2);
for group = 1:groupCount
    rows = (group - 1) * rowsPerGroup + (1:rowsPerGroup);
    local = (1:rowsPerGroup).';
    groupId(rows) = "route-" + compose("%02d", group);
    sampleIndex(rows) = local;
    phase = 2 * pi * (local - 1) / rowsPerGroup;
    values(rows, 1) = -8.02 + 0.015 * group + ...
        0.055 * sin(phase);
    values(rows, 2) = -0.8 + 0.08 * group + ...
        0.55 * cos(phase + 0.2 * group);
end
sequence = build_generator_truth_parameter_sequence(values, ...
    config.standard_parameter_names, struct( ...
        "group_id", groupId, ...
        "parameter_sample_index", sampleIndex, ...
        "raw_window_start", globalIndex, ...
        "raw_window_end", globalIndex + ...
            config.local_fit_window.length - 1, ...
        "raw_window_center", globalIndex + ...
            (config.local_fit_window.length - 1) / 2, ...
        "bounds", [-9, -7; -10, 20], ...
        "provenance", struct( ...
            "source", "deterministic_synthetic_fixture", ...
            "scientific_evidence", false, ...
            "description", ...
                "Ten smooth synthetic routes for Step 9 contract review.")));

extrapolation = build_predictor_dataset( ...
    sequence, "extrapolation", config);
extrapolationSplit = split_predictor_dataset_by_group( ...
    extrapolation, config);
extrapolation = normalize_predictor_dataset( ...
    extrapolation, sequence, extrapolationSplit, config);
interpolation = build_predictor_dataset( ...
    sequence, "interpolation", config);
interpolationSplit = split_predictor_dataset_by_group( ...
    interpolation, config);
interpolation = normalize_predictor_dataset( ...
    interpolation, sequence, interpolationSplit, config);
fixture = struct( ...
    "schema_version", "v3.0-step9-standard-fixture.1", ...
    "config", config, ...
    "parameter_sequence", sequence, ...
    "extrapolation", struct( ...
        "dataset", extrapolation, ...
        "split", extrapolationSplit), ...
    "interpolation", struct( ...
        "dataset", interpolation, ...
        "split", interpolationSplit));
end
