function config = default_predictor_data_config()
%DEFAULT_PREDICTOR_DATA_CONFIG Frozen Step 9 predictor-data defaults.

config = struct( ...
    "schema_version", "v3.0-predictor-data-config.1", ...
    "supported_parameter_names", [ ...
        "DS_mu", "DS_sigma", "r_DS", "num_clusters", ...
        "num_rays", "LNS_ksi", "KF_mu", "KF_sigma"], ...
    "standard_parameter_names", ["DS_mu", "KF_mu"], ...
    "local_fit_window", struct( ...
        "length", 16, ...
        "stride", 4), ...
    "extrapolation", struct( ...
        "context_length", 16, ...
        "target_length", 4), ...
    "interpolation", struct( ...
        "left_context_length", 8, ...
        "right_context_length", 8, ...
        "target_length", 4), ...
    "split", struct( ...
        "strategy", "ordered_group", ...
        "fractions", [0.70, 0.15, 0.15], ...
        "names", ["train", "validation", "test"], ...
        "insufficient_group_policy", "warning"), ...
    "normalization", struct( ...
        "method", "zscore_train_only", ...
        "epsilon", 1e-12, ...
        "project_to_physical_bounds", true), ...
    "fine_tuning", struct( ...
        "supported_modes", ["pretrain", "auto", "off", "force"], ...
        "default_mode", "auto", ...
        "eligibility_rule", "metadata_only_until_step10"), ...
    "storage", struct( ...
        "flatten_order", "MATLAB_column_major", ...
        "tensor_order", ["N_example", "N_context", "P"]));
end
