function manifest = fit_parameter_normalization(sequence, trainGroupIds, config)
%FIT_PARAMETER_NORMALIZATION Fit per-parameter z-score on training groups.

arguments
    sequence (1, 1) struct
    trainGroupIds
    config (1, 1) struct = default_predictor_data_config()
end

report = validate_parameter_sequence(sequence);
if ~report.is_valid
    error("fit_parameter_normalization:InvalidSequence", ...
        "%s", strjoin(report.errors, " | "));
end
configReport = validate_predictor_data_config(config);
if ~configReport.is_valid
    error("fit_parameter_normalization:InvalidConfig", ...
        "%s", strjoin(configReport.errors, " | "));
end
trainGroupIds = string(trainGroupIds(:));
mask = ismember(string(sequence.group_id), trainGroupIds) & ...
    upper(string(sequence.quality_status)) ~= "FAIL" & ...
    all(isfinite(sequence.values), 2);
if ~any(mask)
    error("fit_parameter_normalization:NoTrainingRows", ...
        "No valid parameter rows belong to the training groups.");
end
trainingValues = double(sequence.values(mask, :));
mu = mean(trainingValues, 1);
sigmaRaw = std(trainingValues, 0, 1);
zeroVariance = ~isfinite(sigmaRaw) | ...
    sigmaRaw < config.normalization.epsilon;
sigma = sigmaRaw;
sigma(zeroVariance) = 1;

manifest = struct( ...
    "schema_version", "v3.0-parameter-normalization.1", ...
    "method", "zscore_train_only", ...
    "parameter_names", sequence.parameter_names, ...
    "mean", mu, ...
    "standard_deviation", sigma, ...
    "raw_standard_deviation", sigmaRaw, ...
    "zero_variance", logical(zeroVariance), ...
    "physical_bounds", sequence.parameter_bounds, ...
    "integer_parameter", ismember(sequence.parameter_names, ...
        ["num_clusters", "num_rays"]), ...
    "project_to_physical_bounds", ...
        logical(config.normalization.project_to_physical_bounds), ...
    "training_group_id", trainGroupIds, ...
    "training_row_count", sum(mask), ...
    "fit_scope", "training_partition_parameter_rows_only");
end
