function bundle = read_predictor_data_hdf5(filePath)
%READ_PREDICTOR_DATA_HDF5 Read the portable Step 9 predictor-data file.

arguments
    filePath (1, 1) string
end
if ~isfile(filePath)
    error("read_predictor_data_hdf5:MissingFile", ...
        "File does not exist: %s", filePath);
end
schema = string(h5readatt(filePath, "/", "schema_version"));
if schema ~= "v3.0-predictor-data-hdf5.1"
    error("read_predictor_data_hdf5:UnsupportedSchema", ...
        "Unsupported schema: %s", schema);
end
metadata = readJson(filePath, "/metadata/json_utf8");
sequenceOptions = struct( ...
    "units", string(metadata.parameter_units), ...
    "bounds", readFlat(filePath, ...
        "/parameter_sequence/parameter_bounds"), ...
    "parameter_sample_index", readFlat(filePath, ...
        "/parameter_sequence/parameter_sample_index"), ...
    "raw_window_start", readFlat(filePath, ...
        "/parameter_sequence/raw_window_start"), ...
    "raw_window_end", readFlat(filePath, ...
        "/parameter_sequence/raw_window_end"), ...
    "raw_window_center", readFlat(filePath, ...
        "/parameter_sequence/raw_window_center"), ...
    "group_id", string(metadata.group_id), ...
    "label_source", string(metadata.label_source), ...
    "fit_score", readFlat(filePath, ...
        "/parameter_sequence/fit_score"), ...
    "quality_status", string(metadata.quality_status), ...
    "provenance", metadata.sequence_provenance);
sequence = create_parameter_sequence( ...
    readFlat(filePath, "/parameter_sequence/values"), ...
    string(metadata.parameter_names), sequenceOptions);

dataset = struct( ...
    "schema_version", "v3.0-predictor-dataset.1", ...
    "task_type", string(metadata.task_type), ...
    "input_dimension_order", string(metadata.input_dimension_order), ...
    "target_dimension_order", string(metadata.target_dimension_order), ...
    "context_layout", string(metadata.context_layout), ...
    "inputs", readFlat(filePath, "/predictor/inputs"), ...
    "targets", readFlat(filePath, "/predictor/targets"), ...
    "input_parameter_sample_index", readFlat(filePath, ...
        "/predictor/input_parameter_sample_index"), ...
    "target_parameter_sample_index", readFlat(filePath, ...
        "/predictor/target_parameter_sample_index"), ...
    "parameter_names", sequence.parameter_names, ...
    "parameter_units", sequence.parameter_units, ...
    "parameter_bounds", sequence.parameter_bounds, ...
    "example_group_id", jsonStringColumn( ...
        metadata.example_group_id), ...
    "example_label_source", jsonStringColumn( ...
        metadata.example_label_source), ...
    "normalization", readNormalization(filePath, metadata), ...
    "fine_tuning", metadata.fine_tuning, ...
    "status", "PASS", ...
    "warnings", strings(0, 1), ...
    "summary", metadata.dataset_summary, ...
    "provenance", struct( ...
        "parameter_sequence_schema", sequence.schema_version, ...
        "parameter_sequence_provenance", sequence.provenance));

codes = uint8(readFlat(filePath, "/split/example_partition_code"));
split = struct( ...
    "schema_version", "v3.0-predictor-split.1", ...
    "strategy", string(metadata.split_strategy), ...
    "partition_names", string(metadata.partition_names), ...
    "requested_fractions", double(metadata.requested_fractions), ...
    "group_order", unique(dataset.example_group_id, "stable"), ...
    "train_group_id", jsonStringColumn(metadata.train_group_id), ...
    "validation_group_id", jsonStringColumn( ...
        metadata.validation_group_id), ...
    "test_group_id", jsonStringColumn(metadata.test_group_id), ...
    "example_partition_code", codes(:), ...
    "train_example_index", find(codes == 1), ...
    "validation_example_index", find(codes == 2), ...
    "test_example_index", find(codes == 3), ...
    "status", string(metadata.split_status), ...
    "warnings", string(metadata.split_warnings), ...
    "leakage_check", struct());
bundle = struct( ...
    "schema_version", schema, ...
    "parameter_sequence", sequence, ...
    "dataset", dataset, ...
    "split", split);
end

function value = readFlat(filePath, basePath)
flat = h5read(filePath, basePath + "_values");
shape = double(h5read(filePath, basePath + "_shape"));
value = reshape(flat, shape(:).');
end

function value = readJson(filePath, datasetPath)
bytes = uint8(h5read(filePath, datasetPath));
text = native2unicode(bytes(:).', "UTF-8");
value = jsondecode(text);
end

function normalization = readNormalization(filePath, metadata)
normalization = struct();
if ~datasetExists(filePath, "/normalization/mean_values")
    return;
end
normalization = metadata.normalization;
normalization.parameter_names = string( ...
    normalization.parameter_names);
normalization.training_group_id = string( ...
    normalization.training_group_id);
normalization.mean = readFlat(filePath, "/normalization/mean");
normalization.standard_deviation = readFlat(filePath, ...
    "/normalization/standard_deviation");
normalization.raw_standard_deviation = readFlat(filePath, ...
    "/normalization/raw_standard_deviation");
normalization.physical_bounds = readFlat(filePath, ...
    "/normalization/physical_bounds");
normalization.zero_variance = logical(readFlat(filePath, ...
    "/normalization/zero_variance"));
normalization.integer_parameter = logical(readFlat(filePath, ...
    "/normalization/integer_parameter"));
end

function exists = datasetExists(filePath, datasetPath)
try
    h5info(filePath, datasetPath);
    exists = true;
catch
    exists = false;
end
end

function values = jsonStringColumn(value)
if isempty(value)
    values = strings(0, 1);
elseif ischar(value)
    values = string(value);
else
    values = string(value(:));
end
values = values(:);
end
