function report = validate_predictor_data_config(config)
%VALIDATE_PREDICTOR_DATA_CONFIG Validate frozen Step 9 preparation rules.

errors = strings(0, 1);
warnings = strings(0, 1);
required = ["schema_version", "supported_parameter_names", ...
    "standard_parameter_names", "local_fit_window", ...
    "extrapolation", "interpolation", "split", ...
    "normalization", "fine_tuning", "storage"];
for name = required
    if ~isfield(config, name)
        errors(end + 1, 1) = "Missing config field: " + name; %#ok<AGROW>
    end
end
if ~isempty(errors)
    report = finishReport(errors, warnings);
    return;
end
if string(config.schema_version) ~= "v3.0-predictor-data-config.1"
    errors(end + 1, 1) = "Unsupported predictor-data config schema.";
end
supported = string(config.supported_parameter_names(:)).';
standard = string(config.standard_parameter_names(:)).';
if isempty(supported) || numel(unique(supported)) ~= numel(supported)
    errors(end + 1, 1) = ...
        "supported_parameter_names must be nonempty and unique.";
end
if isempty(standard) || ~all(ismember(standard, supported))
    errors(end + 1, 1) = ...
        "standard_parameter_names must be a nonempty supported subset.";
end
integerFields = [ ...
    double(config.local_fit_window.length), ...
    double(config.local_fit_window.stride), ...
    double(config.extrapolation.context_length), ...
    double(config.extrapolation.target_length), ...
    double(config.interpolation.left_context_length), ...
    double(config.interpolation.right_context_length), ...
    double(config.interpolation.target_length)];
if any(~isfinite(integerFields) | integerFields < 1 | ...
        integerFields ~= round(integerFields))
    errors(end + 1, 1) = ...
        "Every window, context, target, and stride length must be a positive integer.";
end
fractions = double(config.split.fractions(:)).';
if numel(fractions) ~= 3 || any(~isfinite(fractions) | fractions < 0) || ...
        abs(sum(fractions) - 1) > 1e-12
    errors(end + 1, 1) = ...
        "Split fractions must contain three nonnegative values summing to one.";
end
if string(config.split.strategy) ~= "ordered_group"
    errors(end + 1, 1) = ...
        "Step 9 supports only deterministic ordered_group splitting.";
end
if string(config.normalization.method) ~= "zscore_train_only" || ...
        ~isscalar(config.normalization.epsilon) || ...
        ~isfinite(config.normalization.epsilon) || ...
        config.normalization.epsilon <= 0
    errors(end + 1, 1) = ...
        "Normalization must be zscore_train_only with positive finite epsilon.";
end
requiredModes = ["pretrain", "auto", "off", "force"];
modes = string(config.fine_tuning.supported_modes(:)).';
if ~isequal(sort(modes), sort(requiredModes)) || ...
        ~ismember(string(config.fine_tuning.default_mode), modes)
    errors(end + 1, 1) = ...
        "Fine-tuning modes must be pretrain/auto/off/force with a valid default.";
end
report = finishReport(errors, warnings);
end

function report = finishReport(errors, warnings)
if ~isempty(errors)
    status = "FAIL";
elseif ~isempty(warnings)
    status = "WARNING";
else
    status = "PASS";
end
report = struct( ...
    "status", status, ...
    "is_valid", isempty(errors), ...
    "errors", errors, ...
    "warnings", warnings);
end
