function write_predictor_data_hdf5(filePath, bundle)
%WRITE_PREDICTOR_DATA_HDF5 Write the portable Step 9 MATLAB/Python file.

arguments
    filePath (1, 1) string
    bundle (1, 1) struct
end
if isfile(filePath)
    error("write_predictor_data_hdf5:FileExists", ...
        "Refusing to overwrite existing file: %s", filePath);
end
required = ["parameter_sequence", "dataset", "split"];
for name = required
    if ~isfield(bundle, name)
        error("write_predictor_data_hdf5:MissingField", ...
            "Bundle is missing %s.", name);
    end
end
sequence = bundle.parameter_sequence;
dataset = bundle.dataset;
split = bundle.split;
datasetReport = validate_predictor_dataset(dataset);
if ~datasetReport.is_valid
    error("write_predictor_data_hdf5:InvalidDataset", ...
        "%s", strjoin(datasetReport.errors, " | "));
end
if dataset.summary.N_example < 1
    error("write_predictor_data_hdf5:NoExamples", ...
        "At least one complete predictor example is required.");
end
report = validate_parameter_sequence(sequence);
if ~report.is_valid
    error("write_predictor_data_hdf5:InvalidSequence", ...
        "%s", strjoin(report.errors, " | "));
end

writeFlat(filePath, "/parameter_sequence/values", sequence.values);
writeFlat(filePath, "/parameter_sequence/parameter_bounds", ...
    sequence.parameter_bounds);
for name = ["parameter_sample_index", "raw_window_start", ...
        "raw_window_end", "raw_window_center", "fit_score"]
    writeFlat(filePath, "/parameter_sequence/" + name, ...
        sequence.(name));
end
writeFlat(filePath, "/predictor/inputs", dataset.inputs, [ ...
    dataset.summary.N_example, dataset.summary.N_context, ...
    dataset.summary.P]);
writeFlat(filePath, "/predictor/targets", dataset.targets, [ ...
    dataset.summary.N_example, dataset.summary.N_target, ...
    dataset.summary.P]);
writeFlat(filePath, "/predictor/input_parameter_sample_index", ...
    dataset.input_parameter_sample_index);
writeFlat(filePath, "/predictor/target_parameter_sample_index", ...
    dataset.target_parameter_sample_index);
writeFlat(filePath, "/split/example_partition_code", ...
    split.example_partition_code);
if isfield(dataset, "normalization") && ...
        isfield(dataset.normalization, "mean")
    normalization = dataset.normalization;
    writeFlat(filePath, "/normalization/mean", normalization.mean);
    writeFlat(filePath, "/normalization/standard_deviation", ...
        normalization.standard_deviation);
    writeFlat(filePath, "/normalization/raw_standard_deviation", ...
        normalization.raw_standard_deviation);
    writeFlat(filePath, "/normalization/physical_bounds", ...
        normalization.physical_bounds);
    writeFlat(filePath, "/normalization/zero_variance", ...
        uint8(normalization.zero_variance));
    writeFlat(filePath, "/normalization/integer_parameter", ...
        uint8(normalization.integer_parameter));
else
    normalization = struct();
end

metadata = struct( ...
    "parameter_names", sequence.parameter_names, ...
    "parameter_units", sequence.parameter_units, ...
    "group_id", sequence.group_id, ...
    "label_source", sequence.label_source, ...
    "quality_status", sequence.quality_status, ...
    "sequence_provenance", sequence.provenance, ...
    "task_type", dataset.task_type, ...
    "context_layout", dataset.context_layout, ...
    "input_dimension_order", dataset.input_dimension_order, ...
    "target_dimension_order", dataset.target_dimension_order, ...
    "example_group_id", dataset.example_group_id, ...
    "example_label_source", dataset.example_label_source, ...
    "fine_tuning", dataset.fine_tuning, ...
    "dataset_summary", dataset.summary, ...
    "split_strategy", split.strategy, ...
    "partition_names", split.partition_names, ...
    "requested_fractions", split.requested_fractions, ...
    "train_group_id", split.train_group_id, ...
    "validation_group_id", split.validation_group_id, ...
    "test_group_id", split.test_group_id, ...
    "split_status", split.status, ...
    "split_warnings", split.warnings, ...
    "normalization", removeNumericNormalization(normalization));
writeJson(filePath, "/metadata/json_utf8", metadata);
h5writeatt(filePath, "/", "schema_version", ...
    "v3.0-predictor-data-hdf5.1");
h5writeatt(filePath, "/", "flatten_order", "MATLAB_column_major");
h5writeatt(filePath, "/", "tensor_order", ...
    "N_example,N_context_or_target,P");
end

function writeFlat(filePath, basePath, value, explicitShape)
if nargin < 4
    explicitShape = [];
end
flat = value(:);
if isempty(explicitShape)
    shape = uint64(size(value));
elseif prod(explicitShape) ~= numel(value)
    error("write_predictor_data_hdf5:ExplicitShapeMismatch", ...
        "Explicit shape for %s does not match its element count.", ...
        basePath);
else
    shape = uint64(explicitShape);
end
if isscalar(value) && isempty(explicitShape)
    shape = uint64([1, 1]);
end
h5create(filePath, basePath + "_values", size(flat), ...
    "Datatype", class(flat));
h5write(filePath, basePath + "_values", flat);
h5create(filePath, basePath + "_shape", size(shape), ...
    "Datatype", "uint64");
h5write(filePath, basePath + "_shape", shape);
end

function writeJson(filePath, datasetPath, value)
bytes = unicode2native(jsonencode(value), "UTF-8").';
h5create(filePath, datasetPath, size(bytes), "Datatype", "uint8");
h5write(filePath, datasetPath, uint8(bytes));
end

function value = removeNumericNormalization(normalization)
value = normalization;
for name = ["mean", "standard_deviation", ...
        "raw_standard_deviation", "physical_bounds", "zero_variance", ...
        "integer_parameter"]
    if isfield(value, name)
        value = rmfield(value, name);
    end
end
end
