function manifestPath = write_step9_standard_fixtures(outputDirectory)
%WRITE_STEP9_STANDARD_FIXTURES Write two small deterministic public HDF5 files.

arguments
    outputDirectory (1, 1) string
end
if ~isfolder(outputDirectory)
    mkdir(outputDirectory);
end
fixture = create_step9_standard_fixture();
taskTypes = ["extrapolation", "interpolation"];
for index = 1:numel(taskTypes)
    taskType = taskTypes(index);
    path = fullfile(outputDirectory, ...
        "step9_" + taskType + "_standard.h5");
    if isfile(path)
        error("write_step9_standard_fixtures:FileExists", ...
            "Refusing to overwrite existing fixture: %s", path);
    end
    taskBundle = fixture.(taskType);
    write_predictor_data_hdf5(path, struct( ...
        "parameter_sequence", fixture.parameter_sequence, ...
        "dataset", taskBundle.dataset, ...
        "split", taskBundle.split));
end
tasks = cell(numel(taskTypes), 1);
for index = 1:numel(taskTypes)
    taskType = taskTypes(index);
    taskBundle = fixture.(taskType);
    tasks{index} = struct( ...
        "task_type", taskType, ...
        "file", "step9_" + taskType + "_standard.h5", ...
        "input_shape", [ ...
            taskBundle.dataset.summary.N_example, ...
            taskBundle.dataset.summary.N_context, ...
            taskBundle.dataset.summary.P], ...
        "target_shape", [ ...
            taskBundle.dataset.summary.N_example, ...
            taskBundle.dataset.summary.N_target, ...
            taskBundle.dataset.summary.P]);
end
manifest = struct( ...
    "schema_version", fixture.schema_version, ...
    "generated_utc", "deterministic-no-runtime-timestamp", ...
    "scientific_evidence", false, ...
    "parameter_names", fixture.config.standard_parameter_names, ...
    "parameter_sequence_shape", size(fixture.parameter_sequence.values), ...
    "tasks", [tasks{:}], ...
    "notes", [ ...
        "Deterministic synthetic contract fixture."; ...
        "Not measured data and not prediction-accuracy evidence."; ...
        "MATLAB arrays use column-major flattening in HDF5."]);
manifestPath = fullfile(outputDirectory, "manifest.json");
fileId = fopen(manifestPath, "w", "n", "UTF-8");
if fileId < 0
    error("write_step9_standard_fixtures:ManifestOpenFailed", ...
        "Cannot create manifest: %s", manifestPath);
end
cleanup = onCleanup(@() fclose(fileId));
fprintf(fileId, "%s\n", jsonencode(manifest, PrettyPrint=true));
clear cleanup
end
